/**
 * Articulations. Each joint points at the rig node whose rotation expresses its motion,
 * so clicking a joint marker in the scene also selects the thing you can pose.
 */

import type { JointDef, Vec3 } from './types';

const neg = (v: Vec3): Vec3 => [-v[0], v[1], v[2]];

const LEFT_JOINTS: JointDef[] = [
  {
    id: 'l_sternoclavicular',
    name: 'Sternoclavicular joint',
    latin: 'Articulatio sternoclavicularis',
    side: 'left',
    jointClass: 'saddle',
    node: 'l_clavicle',
    marker: [0, 0, 0],
    markerRadius: 0.014,
    bones: ['l_clavicle', 'sternum'],
    ligaments: ['Anterior and posterior sternoclavicular', 'Interclavicular', 'Costoclavicular'],
    movements: ['elevation', 'depression', 'protraction', 'retraction', 'rotation'],
    rangeOfMotion: ['Elevation ~30–35°', 'Protraction/retraction ~25° each', 'Axial rotation ~45°'],
    notes:
      'The only true synovial joint between the upper limb and the axial skeleton. A fibrocartilaginous disc splits it into two compartments and makes it remarkably hard to dislocate.',
    clinical:
      'Because the costoclavicular ligament is so strong, force transmitted along the clavicle fractures the bone rather than dislocating this joint.',
  },
  {
    id: 'l_acromioclavicular',
    name: 'Acromioclavicular joint',
    latin: 'Articulatio acromioclavicularis',
    side: 'left',
    jointClass: 'plane',
    node: 'l_scapula',
    marker: [0.07, 0.07, 0.055],
    markerRadius: 0.013,
    bones: ['l_clavicle', 'l_scapula'],
    ligaments: ['Acromioclavicular', 'Coracoclavicular (conoid + trapezoid)', 'Coracoacromial'],
    movements: ['gliding', 'internal rotation', 'external rotation', 'upward rotation'],
    rangeOfMotion: ['~20–30° of combined rotation across full elevation of the arm'],
    notes:
      'A small gliding joint that lets the scapula rotate relative to the clavicle as the arm goes overhead. The coracoclavicular ligament, not the joint capsule, is the real suspension.',
    clinical:
      'A fall onto the point of the shoulder sprains this joint — the graded "separated shoulder", with a step deformity when the coracoclavicular ligament tears.',
  },
  {
    id: 'l_scapulothoracic',
    name: 'Scapulothoracic articulation',
    side: 'left',
    jointClass: 'functional',
    node: 'l_scapula',
    marker: [0.0, -0.05, -0.03],
    markerRadius: 0.014,
    bones: ['l_scapula', 'ribcage'],
    ligaments: ['None — a muscular interface, not a capsule'],
    movements: ['elevation', 'depression', 'protraction', 'retraction', 'upward rotation', 'downward rotation'],
    rangeOfMotion: ['Upward rotation ~60° during full arm elevation', 'Protraction/retraction ~10 cm of excursion'],
    notes:
      'Not a synovial joint at all: the scapula slides on the thoracic wall on a bed of muscle. Full arm elevation is roughly two parts glenohumeral to one part scapulothoracic — the scapulohumeral rhythm.',
    clinical:
      'Loss of upward rotation (weak serratus anterior or lower trapezius) reduces subacromial space and is a major driver of shoulder impingement.',
  },
  {
    id: 'l_glenohumeral',
    name: 'Glenohumeral (shoulder) joint',
    latin: 'Articulatio humeri',
    side: 'left',
    jointClass: 'ball and socket',
    node: 'l_shoulder',
    marker: [0, 0, 0],
    markerRadius: 0.021,
    bones: ['l_humerus', 'l_scapula'],
    ligaments: [
      'Glenohumeral ligaments (superior, middle, inferior)',
      'Coracohumeral',
      'Transverse humeral',
      'Glenoid labrum (fibrocartilage rim)',
    ],
    movements: ['flexion', 'extension', 'abduction', 'adduction', 'internal rotation', 'external rotation', 'circumduction'],
    rangeOfMotion: [
      'Flexion 0–170°',
      'Extension 0–60°',
      'Abduction 0–175° (with scapular contribution)',
      'Internal rotation 0–90°, external rotation 0–90°',
    ],
    notes:
      'The most mobile joint in the body and, necessarily, the least stable — the humeral head is about three times the area of the glenoid. Stability comes from the rotator cuff compressing the head into the socket rather than from bone.',
    clinical:
      'Over 95% of dislocations are anterior-inferior, where the capsule is weakest, risking axillary nerve injury. A positive empty-can test suggests supraspinatus pathology.',
  },
  {
    id: 'l_elbow',
    name: 'Elbow joint (humeroulnar + humeroradial)',
    latin: 'Articulatio cubiti',
    side: 'left',
    jointClass: 'hinge',
    node: 'l_elbow',
    marker: [0, 0, 0],
    markerRadius: 0.018,
    bones: ['l_humerus', 'l_ulna', 'l_radius'],
    ligaments: ['Ulnar (medial) collateral', 'Radial (lateral) collateral', 'Annular ligament of the radius'],
    movements: ['flexion', 'extension'],
    rangeOfMotion: ['Flexion 0–150°', 'Extension 0° (up to 5–10° hyperextension is normal in some people)'],
    notes:
      'A true uniaxial hinge sharing one capsule with the proximal radioulnar joint. The trochlea–trochlear notch fit is so deep that the elbow is very stable in extension.',
    clinical:
      'Lateral epicondyle pain ("tennis elbow") is really a tendinopathy of extensor carpi radialis brevis; medial epicondyle pain is the wrist-flexor equivalent.',
  },
  {
    id: 'l_radioulnar',
    name: 'Radioulnar joints (proximal + distal)',
    side: 'left',
    jointClass: 'pivot',
    node: 'l_radioulnar',
    marker: [0.014, -0.008, 0.004],
    markerRadius: 0.014,
    bones: ['l_radius', 'l_ulna'],
    ligaments: ['Annular ligament', 'Interosseous membrane', 'Ulnar collateral of the wrist', 'Triangular fibrocartilage complex'],
    movements: ['pronation', 'supination'],
    rangeOfMotion: ['Pronation 0–90°', 'Supination 0–90°'],
    notes:
      'The radius pivots around a fixed ulna, carrying the hand with it. Supination is the stronger action because biceps brachii assists supinator — which is why screws and jar lids are designed for a right-handed supinating twist.',
    clinical:
      "Pulled elbow (radial head subluxation from the annular ligament) is a common toddler injury from a yank on the arm.",
  },
  {
    id: 'l_wrist',
    name: 'Radiocarpal (wrist) joint',
    latin: 'Articulatio radiocarpalis',
    side: 'left',
    jointClass: 'condyloid',
    node: 'l_wrist',
    marker: [0, 0, 0],
    markerRadius: 0.015,
    bones: ['l_radius', 'l_carpals'],
    ligaments: ['Palmar and dorsal radiocarpal', 'Radial and ulnar collateral', 'Triangular fibrocartilage complex'],
    movements: ['flexion', 'extension', 'radial deviation', 'ulnar deviation', 'circumduction'],
    rangeOfMotion: ['Flexion 0–80°', 'Extension 0–70°', 'Ulnar deviation 0–35°', 'Radial deviation 0–20°'],
    notes:
      'Formed by the radius and the disc against the proximal carpal row — the ulna itself does not participate. Ulnar deviation exceeds radial deviation because the radial styloid descends further and blocks it.',
    clinical:
      "Tenderness in the anatomical snuffbox after a fall means a suspected scaphoid fracture even with normal initial X-rays.",
  },
  {
    id: 'l_midcarpal',
    name: 'Midcarpal joint',
    side: 'left',
    jointClass: 'plane',
    node: 'l_wrist',
    marker: [0, -0.028, 0.006],
    markerRadius: 0.012,
    bones: ['l_carpals'],
    ligaments: ['Intercarpal, palmar and dorsal', 'Interosseous intercarpal'],
    movements: ['flexion', 'extension', 'gliding'],
    rangeOfMotion: ['Contributes roughly half of total wrist flexion and extension'],
    notes:
      'The S-shaped line between the carpal rows. Wrist motion is shared between here and the radiocarpal joint, which is why a fused radiocarpal joint still leaves useful movement.',
  },
  {
    id: 'l_thumb_cmc',
    name: 'First carpometacarpal (thumb) joint',
    side: 'left',
    jointClass: 'saddle',
    node: 'l_thumb',
    marker: [0, 0, 0],
    markerRadius: 0.011,
    bones: ['l_carpals', 'l_thumb'],
    ligaments: ['Anterior oblique (beak)', 'Dorsoradial', 'Intermetacarpal'],
    movements: ['flexion', 'extension', 'abduction', 'adduction', 'opposition', 'circumduction'],
    rangeOfMotion: ['Abduction 0–45°', 'Flexion 0–55°', 'Opposition — pad of thumb to pad of little finger'],
    notes:
      'A reciprocal saddle between the trapezium and the 1st metacarpal. Two axes plus axial rotation give opposition, the movement that separates the human hand from every other primate hand.',
    clinical:
      'Grind test pain here indicates thumb-base osteoarthritis, the commonest hand arthritis in women over 50.',
  },
  {
    id: 'l_mcp',
    name: 'Metacarpophalangeal joints',
    side: 'left',
    jointClass: 'condyloid',
    node: 'l_fingers',
    marker: [0, 0, 0],
    markerRadius: 0.012,
    bones: ['l_metacarpals', 'l_phalanges_hand'],
    ligaments: ['Palmar plates', 'Collateral ligaments', 'Deep transverse metacarpal'],
    movements: ['flexion', 'extension', 'abduction', 'adduction'],
    rangeOfMotion: ['Flexion 0–95°', 'Extension 0–35°'],
    notes:
      'Knuckle joints. Their collateral ligaments are slack in extension and taut in flexion — the reason a hand is splinted in the "safe" flexed position to avoid stiffness.',
  },
  {
    id: 'l_pip',
    name: 'Interphalangeal joints',
    side: 'left',
    jointClass: 'hinge',
    node: 'l_fingers',
    marker: [0.01, -0.035, 0.01],
    markerRadius: 0.01,
    bones: ['l_phalanges_hand'],
    ligaments: ['Collateral ligaments', 'Volar plates'],
    movements: ['flexion', 'extension'],
    rangeOfMotion: ['PIP flexion 0–110°', 'DIP flexion 0–90°'],
    notes:
      'Pure hinges. Flexor digitorum superficialis drives the PIP joints and flexor digitorum profundus the DIP joints — the basis of the standard tendon-isolation tests.',
  },
  {
    id: 'l_hip',
    name: 'Hip joint',
    latin: 'Articulatio coxae',
    side: 'left',
    jointClass: 'ball and socket',
    node: 'l_hip',
    marker: [0, 0, 0],
    markerRadius: 0.024,
    bones: ['l_femur', 'l_hipbone'],
    ligaments: [
      'Iliofemoral (Y ligament — strongest in the body)',
      'Pubofemoral',
      'Ischiofemoral',
      'Ligamentum teres',
      'Acetabular labrum',
    ],
    movements: ['flexion', 'extension', 'abduction', 'adduction', 'internal rotation', 'external rotation', 'circumduction'],
    rangeOfMotion: [
      'Flexion 0–125° (knee bent)',
      'Extension 0–30°',
      'Abduction 0–50°, adduction 0–30°',
      'Internal rotation 0–40°, external rotation 0–50°',
    ],
    notes:
      'Mobility traded for stability compared with the shoulder: the acetabulum is deep, the labrum seals it, and the iliofemoral ligament makes standing almost passive — you can hang on your hip ligaments without muscle work.',
    clinical:
      'A positive Trendelenburg sign (pelvis drops on the unsupported side) indicates gluteus medius weakness on the stance side. FADIR pain suggests femoroacetabular impingement or a labral tear.',
  },
  {
    id: 'l_knee',
    name: 'Knee joint (tibiofemoral)',
    latin: 'Articulatio genus',
    side: 'left',
    jointClass: 'hinge',
    node: 'l_knee',
    marker: [0, 0, 0],
    markerRadius: 0.024,
    bones: ['l_femur', 'l_tibia', 'l_patella'],
    ligaments: [
      'Anterior cruciate (ACL)',
      'Posterior cruciate (PCL)',
      'Medial collateral (MCL)',
      'Lateral collateral (LCL)',
      'Medial and lateral menisci',
      'Oblique and arcuate popliteal',
    ],
    movements: ['flexion', 'extension', 'internal rotation', 'external rotation'],
    rangeOfMotion: [
      'Flexion 0–150°',
      'Extension 0° (5–10° hyperextension common)',
      'Rotation ~20° each way, only when flexed',
    ],
    notes:
      'A modified hinge, not a true one. In the last 30° of extension the femur rolls and spins to "screw home", locking the joint; popliteus unlocks it to start flexion.',
    clinical:
      'A non-contact pivot injury with an audible pop and immediate swelling suggests an ACL tear — test with Lachman. Joint-line tenderness with a positive Thessaly test suggests a meniscal tear.',
  },
  {
    id: 'l_patellofemoral',
    name: 'Patellofemoral joint',
    side: 'left',
    jointClass: 'plane',
    node: 'l_knee',
    marker: [0.001, 0.03, 0.043],
    markerRadius: 0.014,
    bones: ['l_patella', 'l_femur'],
    ligaments: ['Medial and lateral patellar retinacula', 'Patellar tendon (ligament)', 'Medial patellofemoral ligament'],
    movements: ['gliding', 'flexion', 'extension'],
    rangeOfMotion: ['The patella travels ~7 cm along the trochlear groove from full extension to full flexion'],
    notes:
      'Compressive loads here reach several times body weight in a deep squat — the patella is the highest-pressure joint surface in the body per unit area.',
    clinical:
      'Anterior knee pain aggravated by stairs and prolonged sitting is the classic patellofemoral pain presentation; hip abductor strengthening usually helps more than knee exercises alone.',
  },
  {
    id: 'l_tibiofibular',
    name: 'Tibiofibular joints',
    side: 'left',
    jointClass: 'plane',
    node: 'l_knee',
    marker: [0.024, -0.022, -0.006],
    markerRadius: 0.011,
    bones: ['l_tibia', 'l_fibula'],
    ligaments: ['Anterior and posterior tibiofibular', 'Interosseous membrane', 'Syndesmosis distally'],
    movements: ['gliding'],
    rangeOfMotion: ['A few millimetres of fibular glide and rotation with each step'],
    notes:
      'The fibula rises and rotates slightly with ankle dorsiflexion — the syndesmosis has to give a little for the wider anterior talus to enter the mortise.',
    clinical:
      'A high ankle sprain is a syndesmosis injury; it is slower to heal than a lateral ligament sprain and is provoked by the squeeze test.',
  },
  {
    id: 'l_ankle',
    name: 'Talocrural (ankle) joint',
    latin: 'Articulatio talocruralis',
    side: 'left',
    jointClass: 'hinge',
    node: 'l_ankle',
    marker: [0, 0, 0],
    markerRadius: 0.018,
    bones: ['l_tibia', 'l_fibula', 'l_tarsals'],
    ligaments: [
      'Deltoid (medial) ligament',
      'Anterior talofibular',
      'Calcaneofibular',
      'Posterior talofibular',
    ],
    movements: ['dorsiflexion', 'plantarflexion'],
    rangeOfMotion: ['Dorsiflexion 0–25°', 'Plantarflexion 0–50°'],
    notes:
      'A mortise-and-tenon hinge. It is most stable in dorsiflexion, when the wider front of the talus is wedged into the mortise — so sprains happen in plantarflexion.',
    clinical:
      'Limited dorsiflexion (< ~10°) alters squat depth and is a risk factor for knee and Achilles problems. The lateral ligaments account for ~85% of ankle sprains.',
  },
  {
    id: 'l_subtalar',
    name: 'Subtalar joint',
    latin: 'Articulatio talocalcanea',
    side: 'left',
    jointClass: 'plane',
    node: 'l_ankle',
    marker: [0, -0.036, -0.005],
    markerRadius: 0.013,
    bones: ['l_tarsals'],
    ligaments: ['Interosseous talocalcaneal', 'Cervical ligament', 'Calcaneofibular'],
    movements: ['inversion', 'eversion'],
    rangeOfMotion: ['Inversion 0–35°', 'Eversion 0–20°'],
    notes:
      'The foot\'s adaptor: it converts rotation of the leg into pronation and supination of the foot, letting the sole stay flat on uneven ground.',
    clinical:
      'Excessive pronation here is associated with medial tibial stress syndrome and plantar heel pain.',
  },
  {
    id: 'l_midfoot',
    name: 'Midfoot joints (talonavicular, calcaneocuboid, tarsometatarsal)',
    side: 'left',
    jointClass: 'plane',
    node: 'l_ankle',
    marker: [0, -0.048, 0.05],
    markerRadius: 0.012,
    bones: ['l_tarsals', 'l_metatarsals'],
    ligaments: ['Plantar calcaneonavicular (spring)', 'Long and short plantar', 'Plantar fascia', 'Lisfranc ligament'],
    movements: ['gliding', 'inversion', 'eversion'],
    rangeOfMotion: ['Small individual excursions that sum to a supple or rigid foot depending on hindfoot position'],
    notes:
      'These joints lock when the hindfoot supinates, turning the foot into a rigid lever for push-off, and unlock when it pronates so the foot can absorb landing.',
    clinical: 'A Lisfranc injury (tarsometatarsal disruption) is easily missed and needs weight-bearing films.',
  },
  {
    id: 'l_mtp',
    name: 'Metatarsophalangeal joints',
    side: 'left',
    jointClass: 'condyloid',
    node: 'l_forefoot',
    marker: [0, 0, 0],
    markerRadius: 0.012,
    bones: ['l_metatarsals', 'l_phalanges_foot'],
    ligaments: ['Plantar plates', 'Collateral ligaments', 'Deep transverse metatarsal'],
    movements: ['flexion', 'extension', 'abduction', 'adduction'],
    rangeOfMotion: ['Extension 0–70° (needed at push-off)', 'Flexion 0–40°'],
    notes:
      'First-MTP extension tensions the plantar fascia and raises the arch — the windlass mechanism that stiffens the foot at toe-off.',
    clinical:
      'Loss of 1st MTP extension is hallux rigidus; a laterally deviated hallux is hallux valgus. Both change push-off mechanics and load the lesser metatarsals.',
  },
];

const CENTER_JOINTS: JointDef[] = [
  {
    id: 'atlantooccipital',
    name: 'Atlanto-occipital joint',
    side: 'center',
    jointClass: 'condyloid',
    node: 'head',
    marker: [0, -0.005, -0.02],
    markerRadius: 0.016,
    bones: ['skull', 'cervical_vertebrae'],
    ligaments: ['Anterior and posterior atlanto-occipital membranes', 'Alar and apical ligaments of the dens'],
    movements: ['flexion', 'extension', 'left lateral flexion', 'right lateral flexion'],
    rangeOfMotion: ['Flexion/extension ~15–20° total (the "yes" joint)', 'Lateral flexion ~8°'],
    notes:
      'The nodding joint. It contributes almost no rotation, which is deliberate — the vertebral arteries and brainstem sit right here.',
    clinical:
      'Deep upper cervical flexor endurance (chin tuck) is the standard rehabilitation target for cervicogenic headache.',
  },
  {
    id: 'atlantoaxial',
    name: 'Atlanto-axial joint',
    side: 'center',
    jointClass: 'pivot',
    node: 'head',
    marker: [0, -0.03, -0.018],
    markerRadius: 0.014,
    bones: ['cervical_vertebrae'],
    ligaments: ['Transverse ligament of the atlas', 'Alar ligaments', 'Cruciate ligament complex'],
    movements: ['right rotation', 'left rotation'],
    rangeOfMotion: ['Rotation ~40° each way — roughly half of all cervical rotation'],
    notes:
      'The atlas spins on the dens of the axis like a ring on a peg. The transverse ligament holds the dens against the anterior arch; if it fails, the cord is at risk.',
    clinical:
      'Rheumatoid arthritis and Down syndrome can render this joint unstable — a reason to check before intubation or contact sport.',
  },
  {
    id: 'cervical_spine',
    name: 'Cervical spine (C2–C7 facet and disc joints)',
    side: 'center',
    jointClass: 'plane',
    node: 'neck',
    marker: [0, 0.05, -0.02],
    markerRadius: 0.018,
    bones: ['cervical_vertebrae'],
    ligaments: ['Anterior and posterior longitudinal', 'Ligamentum flavum', 'Interspinous', 'Nuchal ligament'],
    movements: ['flexion', 'extension', 'left lateral flexion', 'right lateral flexion', 'left rotation', 'right rotation'],
    rangeOfMotion: ['Flexion 0–50°', 'Extension 0–55°', 'Lateral flexion 0–42°', 'Rotation 0–75°'],
    notes:
      'Facet joints angled at about 45° allow generous motion in every plane, and always couple lateral flexion with rotation to the same side.',
    clinical:
      'Whiplash loads these facet joints; the C5–C6 level is the commonest site of degenerative change because it is the mobility peak.',
  },
  {
    id: 'thoracic_spine',
    name: 'Thoracic spine (facet and disc joints)',
    side: 'center',
    jointClass: 'plane',
    node: 'thorax',
    marker: [0, 0.1, -0.035],
    markerRadius: 0.019,
    bones: ['thoracic_vertebrae', 'ribcage'],
    ligaments: ['Anterior and posterior longitudinal', 'Ligamentum flavum', 'Costotransverse', 'Intertransverse'],
    movements: ['flexion', 'extension', 'left rotation', 'right rotation', 'left lateral flexion', 'right lateral flexion'],
    rangeOfMotion: ['Rotation 0–35° (the most of any region)', 'Flexion 0–35°', 'Extension 0–20°'],
    notes:
      'Nearly vertical facets favour rotation and restrain flexion; the rib attachments do the rest. Thoracic stiffness is usually compensated for by the lumbar spine and shoulder, both of which pay for it.',
    clinical:
      'Restoring thoracic extension and rotation reduces load on the lumbar spine in rotational sports and improves overhead shoulder range.',
  },
  {
    id: 'lumbar_spine',
    name: 'Lumbar spine (facet and disc joints)',
    side: 'center',
    jointClass: 'plane',
    node: 'lumbar',
    marker: [0, 0.06, -0.025],
    markerRadius: 0.021,
    bones: ['lumbar_vertebrae'],
    ligaments: [
      'Anterior longitudinal',
      'Posterior longitudinal',
      'Ligamentum flavum',
      'Supraspinous and interspinous',
      'Iliolumbar',
    ],
    movements: ['flexion', 'extension', 'left lateral flexion', 'right lateral flexion', 'left rotation', 'right rotation'],
    rangeOfMotion: ['Flexion 0–55°', 'Extension 0–25°', 'Lateral flexion 0–30°', 'Rotation only 0–13° total'],
    notes:
      'Sagittally oriented facets almost eliminate rotation while permitting large flexion and extension. Combined end-range flexion with rotation under load is the classic disc-injury mechanism.',
    clinical:
      'Repeated end-range extension in adolescent athletes causes pars interarticularis stress fracture (spondylolysis), typically at L5.',
  },
  {
    id: 'sacroiliac',
    name: 'Sacroiliac joint',
    side: 'center',
    jointClass: 'plane',
    node: 'pelvis',
    marker: [0.04, 0.02, -0.045],
    markerRadius: 0.015,
    bones: ['sacrum', 'l_hipbone', 'r_hipbone'],
    ligaments: [
      'Anterior, interosseous and posterior sacroiliac',
      'Sacrotuberous',
      'Sacrospinous',
      'Iliolumbar',
    ],
    movements: ['nutation (anterior tilt)', 'counter-nutation (posterior tilt)'],
    rangeOfMotion: ['2–4° of rotation and ~1–2 mm of translation'],
    notes:
      'Barely mobile by design: it transfers the entire load of the trunk to the legs. Stability comes from the wedge shape of the sacrum plus force closure from the gluteals, latissimus dorsi and thoracolumbar fascia.',
    clinical:
      'Pain here is common in late pregnancy as relaxin softens the ligaments. Three or more positive provocation tests support the diagnosis.',
  },
  {
    id: 'pubic_symphysis',
    name: 'Pubic symphysis',
    side: 'center',
    jointClass: 'cartilaginous',
    node: 'pelvis',
    marker: [0, -0.035, 0.075],
    markerRadius: 0.013,
    bones: ['l_hipbone', 'r_hipbone'],
    ligaments: ['Superior and inferior (arcuate) pubic', 'Interpubic disc'],
    movements: ['minimal gliding'],
    rangeOfMotion: ['~2 mm of translation and 1° rotation; more in pregnancy'],
    notes: 'The anterior closure of the pelvic ring, taking the tension the sacroiliac joints generate behind.',
    clinical:
      'Osteitis pubis / adductor-related groin pain is common in kicking and change-of-direction sports.',
  },
  {
    id: 'sacrococcygeal',
    name: 'Sacrococcygeal joint',
    side: 'center',
    jointClass: 'cartilaginous',
    node: 'pelvis',
    marker: [0, -0.04, -0.055],
    markerRadius: 0.01,
    bones: ['sacrum', 'coccyx'],
    ligaments: ['Anterior, posterior and lateral sacrococcygeal'],
    movements: ['flexion', 'extension'],
    rangeOfMotion: ['A few degrees, increasing during childbirth'],
    notes: 'Allows the coccyx to move back during defecation and delivery.',
  },
  {
    id: 'costovertebral',
    name: 'Costovertebral and costotransverse joints',
    side: 'center',
    jointClass: 'plane',
    node: 'thorax',
    marker: [0.035, 0.1, -0.03],
    markerRadius: 0.012,
    bones: ['ribcage', 'thoracic_vertebrae'],
    ligaments: ['Radiate', 'Costotransverse', 'Lateral and superior costotransverse'],
    movements: ['elevation', 'depression', 'rotation'],
    rangeOfMotion: ['A few degrees per rib, summing to ~5 cm of chest expansion'],
    notes:
      'The hinge axis differs by level: upper ribs swing like a pump handle (raising the sternum), lower ribs like a bucket handle (widening the chest).',
    clinical: 'A stiff costovertebral joint is a common cause of "rib" pain and of pain on deep inspiration.',
  },
  {
    id: 'sternocostal',
    name: 'Sternocostal joints',
    side: 'center',
    jointClass: 'cartilaginous',
    node: 'chest',
    marker: [0.025, -0.055, 0.085],
    markerRadius: 0.011,
    bones: ['sternum', 'ribcage'],
    ligaments: ['Radiate sternocostal', 'Costoxiphoid', 'Intra-articular sternocostal'],
    movements: ['elevation', 'depression'],
    rangeOfMotion: ['Small, elastic — the costal cartilages themselves deform'],
    notes: 'The elasticity of the costal cartilage, not joint movement, provides most of the ribcage\'s springiness.',
    clinical: 'Costochondritis: reproducible tenderness at one or two of these junctions, benign but persistent.',
  },
  {
    id: 'temporomandibular',
    name: 'Temporomandibular joint',
    side: 'center',
    jointClass: 'condyloid',
    node: 'jaw',
    marker: [0.048, 0.02, -0.03],
    markerRadius: 0.012,
    bones: ['mandible', 'skull'],
    ligaments: ['Lateral (temporomandibular)', 'Sphenomandibular', 'Stylomandibular', 'Articular disc'],
    movements: ['depression', 'elevation', 'protraction', 'retraction', 'lateral deviation'],
    rangeOfMotion: ['Opening 40–50 mm between incisors', 'Protrusion ~10 mm', 'Lateral deviation ~10 mm'],
    notes:
      'The only joint with an obligatory two-phase motion: the condyle first rotates in the fossa, then translates forward onto the articular eminence to complete opening.',
    clinical:
      'Clicking with deviation on opening suggests disc displacement with reduction; masseter and temporalis trigger points refer pain to the teeth and temple.',
  },
];

function mirrorJoint(j: JointDef): JointDef {
  const swap = (s: string) => s.replace(/^l_/, 'r_');
  return {
    ...j,
    id: swap(j.id),
    name: j.name,
    side: 'right',
    node: j.node.startsWith('l_') ? swap(j.node) : j.node,
    marker: neg(j.marker),
    bones: j.bones.map((b) => (b.startsWith('l_') ? swap(b) : b)),
  };
}

export const JOINTS: JointDef[] = [
  ...CENTER_JOINTS,
  ...LEFT_JOINTS,
  ...LEFT_JOINTS.map(mirrorJoint),
];
