/**
 * Muscles of the neck, spine, abdominal wall and respiratory apparatus.
 * Left-side entries are mirrored by `bilateral()`; entries marked `side: 'center'` are not.
 */

import { p, via } from './muscleHelpers';
import type { MuscleDef } from './types';

export const TRUNK_MUSCLES: MuscleDef[] = [
  // ======================================================================== NECK
  {
    id: 'l_sternocleidomastoid',
    name: 'Sternocleidomastoid',
    latin: 'Musculus sternocleidomastoideus',
    side: 'left',
    group: 'Anterior neck',
    region: 'neck',
    layer: 1,
    girth: 0.014,
    path: [
      p('chest', [0.018, 1.378, 0.076]),
      via('neck', [0.042, 1.46, 0.03]),
      p('head', [0.055, 1.545, -0.04]),
    ],
    originDesc: 'Sternal head from the manubrium; clavicular head from the medial third of the clavicle',
    insertionDesc: 'Mastoid process of the temporal bone and the lateral superior nuchal line',
    actions: [
      { joint: 'cervical_spine', motion: 'right rotation', role: 'prime' },
      { joint: 'cervical_spine', motion: 'left lateral flexion', role: 'prime' },
      { joint: 'cervical_spine', motion: 'flexion', role: 'assist' },
      { joint: 'atlantooccipital', motion: 'extension', role: 'assist' },
    ],
    innervation: 'Accessory nerve (CN XI) for motor; C2–C3 for proprioception',
    nerve: 'l_accessory',
    bloodSupply: 'Occipital and superior thyroid arteries',
    palpation: 'Turn the head to the opposite side — the strap standing out from sternum to behind the ear.',
    exercises: [
      {
        name: 'Supine head lift (chin tuck first)',
        kind: 'activation',
        equipment: 'Bodyweight',
        cue: 'Tuck the chin, then lift the head. Leading with the chin instead lets SCM dominate over the deep flexors — the pattern to avoid in neck rehab.',
        motion: 'Cervical flexion',
      },
      {
        name: 'Resisted cervical rotation',
        kind: 'isolation',
        equipment: 'Hand or band',
        cue: 'Turn the head against your own palm. The left SCM turns the head to the right — it rotates contralaterally.',
        motion: 'Cervical rotation',
      },
      {
        name: 'SCM stretch',
        kind: 'stretch',
        equipment: 'None',
        cue: 'Side-bend away, rotate toward the tight side, then look up. Hold 30 s.',
        motion: 'Cervical extension + contralateral side-bend',
      },
    ],
    antagonists: ['l_splenius_capitis', 'l_semispinalis_capitis'],
    synergists: ['l_scalenes', 'l_longus_colli'],
    clinical:
      'Acting alone it rotates the head to the *opposite* side and side-bends to its own — an unusual combination worth remembering. It is the key landmark dividing the anterior and posterior triangles of the neck.',
  },
  {
    id: 'l_scalenes',
    name: 'Scalene group (anterior, middle, posterior)',
    latin: 'Musculi scaleni',
    side: 'left',
    group: 'Deep anterior neck',
    region: 'neck',
    layer: 2,
    girth: 0.011,
    path: [
      p('neck', [0.028, 1.482, -0.008]),
      via('neck', [0.04, 1.43, 0.008]),
      p('thorax', [0.05, 1.368, 0.03]),
    ],
    originDesc: 'Transverse processes of C2–C7',
    insertionDesc: 'Anterior and middle scalene to the 1st rib; posterior scalene to the 2nd rib',
    actions: [
      { joint: 'cervical_spine', motion: 'left lateral flexion', role: 'prime' },
      { joint: 'cervical_spine', motion: 'flexion', role: 'assist' },
      { joint: 'costovertebral', motion: 'elevation', role: 'assist' },
    ],
    innervation: 'Anterior rami of C3–C8',
    bloodSupply: 'Ascending cervical and inferior thyroid arteries',
    exercises: [
      {
        name: 'Lateral neck flexion against resistance',
        kind: 'isolation',
        equipment: 'Hand or light band',
        cue: 'Ear toward shoulder without shrugging.',
        motion: 'Cervical lateral flexion',
      },
      {
        name: 'Diaphragmatic breathing drill',
        kind: 'activation',
        equipment: 'None',
        cue: 'The aim here is the opposite — to *stop* the scalenes acting as accessory breathing muscles. Breathe into the lower ribs with a quiet neck.',
        motion: 'Rib elevation (to be minimised)',
      },
      {
        name: 'Scalene stretch',
        kind: 'stretch',
        equipment: 'None',
        cue: 'Depress the first rib by holding the shoulder down, then side-bend and rotate the head away.',
        motion: 'Cervical side-bend',
      },
    ],
    synergists: ['l_sternocleidomastoid'],
    clinical:
      'The brachial plexus and subclavian artery pass between the anterior and middle scalenes — the interscalene triangle, and the commonest site of thoracic outlet compression.',
  },
  {
    id: 'l_longus_colli',
    name: 'Longus colli and longus capitis (deep cervical flexors)',
    latin: 'Musculus longus colli et longus capitis',
    side: 'left',
    group: 'Deep anterior neck',
    region: 'neck',
    layer: 3,
    girth: 0.008,
    path: [
      p('thorax', [0.012, 1.36, -0.028]),
      via('neck', [0.014, 1.44, -0.02]),
      p('neck', [0.013, 1.522, -0.018]),
    ],
    originDesc: 'Anterior bodies of T1–T3 and the transverse processes of C3–C6',
    insertionDesc: 'Anterior arch of the atlas and the bodies of C2–C4; longus capitis to the basilar occiput',
    actions: [
      { joint: 'cervical_spine', motion: 'flexion', role: 'prime' },
      { joint: 'atlantooccipital', motion: 'flexion', role: 'prime' },
      { joint: 'cervical_spine', motion: 'left lateral flexion', role: 'assist' },
    ],
    innervation: 'Anterior rami of C2–C6',
    bloodSupply: 'Vertebral and ascending pharyngeal arteries',
    exercises: [
      {
        name: 'Chin tuck (cranio-cervical flexion)',
        kind: 'activation',
        equipment: 'Bodyweight, or a pressure biofeedback cuff',
        cue: 'A gentle nod as if making a double chin, without lifting the head. The single most evidence-supported exercise for neck pain and cervicogenic headache.',
        motion: 'Upper cervical flexion',
      },
      {
        name: 'Supine chin-tuck head lift, 10 s holds',
        kind: 'isolation',
        equipment: 'Bodyweight',
        cue: 'Hold the tuck, lift the head 2 cm. If the chin pokes forward, the SCM has taken over — reset.',
        motion: 'Cervical flexion',
      },
    ],
    antagonists: ['l_semispinalis_capitis', 'l_splenius_capitis', 'l_suboccipitals'],
    clinical:
      'Selectively atrophies and loses endurance after whiplash and in chronic neck pain — retraining it is the core of modern cervical rehabilitation.',
  },
  {
    id: 'l_splenius_capitis',
    name: 'Splenius capitis and cervicis',
    latin: 'Musculus splenius capitis et cervicis',
    side: 'left',
    group: 'Posterior neck',
    region: 'neck',
    layer: 2,
    girth: 0.011,
    path: [
      p('thorax', [0.008, 1.358, -0.062]),
      via('neck', [0.03, 1.47, -0.06]),
      p('head', [0.046, 1.564, -0.058]),
    ],
    originDesc: 'Nuchal ligament and the spinous processes of C7–T4',
    insertionDesc: 'Mastoid process and lateral third of the superior nuchal line',
    actions: [
      { joint: 'cervical_spine', motion: 'extension', role: 'prime' },
      { joint: 'cervical_spine', motion: 'left rotation', role: 'prime' },
      { joint: 'cervical_spine', motion: 'left lateral flexion', role: 'assist' },
    ],
    innervation: 'Posterior rami of the middle cervical nerves',
    bloodSupply: 'Occipital artery',
    exercises: [
      {
        name: 'Prone neck extension holds',
        kind: 'isolation',
        equipment: 'Bench, bodyweight',
        cue: 'Face down with the head off the end; lift to neutral, not into full extension. Build endurance, not range.',
        motion: 'Cervical extension',
      },
      {
        name: 'Resisted ipsilateral rotation',
        kind: 'isolation',
        equipment: 'Hand or band',
        cue: 'Unlike SCM, splenius rotates the head to its *own* side.',
        motion: 'Cervical rotation',
      },
    ],
    antagonists: ['l_sternocleidomastoid', 'l_longus_colli'],
    synergists: ['l_semispinalis_capitis', 'l_trapezius_upper'],
  },
  {
    id: 'l_semispinalis_capitis',
    name: 'Semispinalis capitis',
    latin: 'Musculus semispinalis capitis',
    side: 'left',
    group: 'Posterior neck',
    region: 'neck',
    layer: 3,
    girth: 0.011,
    path: [
      p('thorax', [0.02, 1.3, -0.06]),
      via('neck', [0.022, 1.44, -0.062]),
      p('head', [0.023, 1.586, -0.072]),
    ],
    originDesc: 'Transverse processes of C7–T6',
    insertionDesc: 'Occipital bone between the superior and inferior nuchal lines',
    actions: [
      { joint: 'cervical_spine', motion: 'extension', role: 'prime' },
      { joint: 'atlantooccipital', motion: 'extension', role: 'prime' },
      { joint: 'cervical_spine', motion: 'right rotation', role: 'assist' },
    ],
    innervation: 'Posterior rami of the cervical spinal nerves (greater occipital nerve, C2)',
    bloodSupply: 'Occipital and deep cervical arteries',
    exercises: [
      {
        name: 'Prone cervical extension with a chin tuck',
        kind: 'isolation',
        equipment: 'Bodyweight',
        cue: 'Keeping the chin tucked biases the deeper extensors over the upper trapezius.',
        motion: 'Cervical extension',
      },
      {
        name: 'Neck harness extension',
        kind: 'isolation',
        equipment: 'Neck harness',
        cue: 'Load slowly and through a mid range only; the cervical spine does not tolerate ballistic work.',
        motion: 'Cervical extension',
      },
    ],
    antagonists: ['l_longus_colli'],
    clinical:
      'The greater occipital nerve pierces it, which is why tightness here refers pain over the scalp to the vertex — a classic cervicogenic headache pattern.',
  },
  {
    id: 'l_suboccipitals',
    name: 'Suboccipital group',
    latin: 'Musculi suboccipitales',
    side: 'left',
    group: 'Posterior neck',
    region: 'neck',
    layer: 3,
    girth: 0.008,
    path: [
      p('neck', [0.014, 1.486, -0.05]),
      p('head', [0.026, 1.566, -0.068]),
    ],
    originDesc: 'Spinous process of the axis and the posterior arch of the atlas',
    insertionDesc: 'Inferior nuchal line and the transverse process of the atlas',
    actions: [
      { joint: 'atlantooccipital', motion: 'extension', role: 'prime' },
      { joint: 'atlantoaxial', motion: 'left rotation', role: 'prime' },
    ],
    innervation: 'Suboccipital nerve (posterior ramus of C1)',
    bloodSupply: 'Vertebral and deep cervical arteries',
    exercises: [
      {
        name: 'Suboccipital release',
        kind: 'stretch',
        equipment: 'Two tennis balls in a sock',
        cue: 'Lie on the balls just under the occiput and nod gently for 60–90 s.',
        motion: 'Upper cervical flexion',
      },
      {
        name: 'Slow nodding with eye tracking',
        kind: 'activation',
        equipment: 'None',
        cue: 'These muscles are extraordinarily rich in muscle spindles — they are proprioceptive organs as much as movers, and they respond to slow controlled work.',
        motion: 'Upper cervical nodding',
      },
    ],
    antagonists: ['l_longus_colli'],
    clinical:
      'A myodural bridge connects rectus capitis posterior minor to the dura — a proposed mechanism linking upper-cervical dysfunction to headache.',
  },
  // ======================================================================== JAW
  {
    id: 'l_masseter',
    name: 'Masseter',
    latin: 'Musculus masseter',
    side: 'left',
    group: 'Muscles of mastication',
    region: 'neck',
    layer: 1,
    girth: 0.013,
    path: [
      p('head', [0.056, 1.566, 0.02]),
      p('jaw', [0.05, 1.492, 0.0]),
    ],
    originDesc: 'Inferior border and medial surface of the zygomatic arch',
    insertionDesc: 'Lateral surface of the ramus and angle of the mandible',
    actions: [
      { joint: 'temporomandibular', motion: 'elevation', role: 'prime' },
      { joint: 'temporomandibular', motion: 'protraction', role: 'assist' },
    ],
    innervation: 'Masseteric branch of the mandibular nerve (CN V3)',
    bloodSupply: 'Masseteric artery',
    palpation: 'Clench the teeth — the square bulge over the angle of the jaw.',
    exercises: [
      {
        name: 'Jaw relaxation / tongue-to-palate rest position',
        kind: 'activation',
        equipment: 'None',
        cue: 'Teeth apart, lips together, tongue on the palate. For most people the masseter needs downtraining, not strengthening.',
        motion: 'Jaw rest position',
      },
      {
        name: 'Controlled opening against light resistance',
        kind: 'isolation',
        equipment: 'Fingers under the chin',
        cue: 'Open in a straight line without deviation; deviation suggests disc or capsular restriction.',
        motion: 'Jaw depression',
      },
    ],
    antagonists: ['l_digastric'],
    clinical:
      'Weight for weight the strongest muscle in the body. Chronic overactivity (bruxism) causes facial pain and tooth wear, and refers to the ear and temple.',
  },
  {
    id: 'l_temporalis',
    name: 'Temporalis',
    latin: 'Musculus temporalis',
    side: 'left',
    group: 'Muscles of mastication',
    region: 'neck',
    layer: 2,
    girth: 0.012,
    path: [
      p('head', [0.056, 1.606, -0.008]),
      via('head', [0.056, 1.562, 0.008]),
      p('jaw', [0.04, 1.532, 0.012]),
    ],
    originDesc: 'Temporal fossa and the temporal fascia',
    insertionDesc: 'Coronoid process and anterior border of the ramus of the mandible',
    actions: [
      { joint: 'temporomandibular', motion: 'elevation', role: 'prime' },
      { joint: 'temporomandibular', motion: 'retraction', role: 'prime' },
    ],
    innervation: 'Deep temporal branches of the mandibular nerve (CN V3)',
    bloodSupply: 'Deep temporal arteries',
    exercises: [
      {
        name: 'Temporalis self-release',
        kind: 'stretch',
        equipment: 'Fingertips',
        cue: 'Small circles over the temple with the jaw slightly open; a common source of "tension headache".',
        motion: 'Jaw depression',
      },
    ],
    antagonists: ['l_digastric'],
    clinical:
      'Its posterior fibres retract the jaw, so temporalis pain is often provoked by a habitual forward-jaw posture.',
  },
  {
    id: 'l_digastric',
    name: 'Suprahyoid group (digastric, mylohyoid, geniohyoid)',
    latin: 'Musculi suprahyoidei',
    side: 'left',
    group: 'Muscles of mastication',
    region: 'neck',
    layer: 2,
    girth: 0.008,
    path: [
      p('jaw', [0.02, 1.484, 0.055]),
      via('neck', [0.03, 1.472, 0.014]),
      p('head', [0.05, 1.526, -0.032]),
    ],
    originDesc: 'Anterior belly from the digastric fossa of the mandible; posterior belly from the mastoid notch',
    insertionDesc: 'Intermediate tendon slung from the hyoid bone',
    actions: [
      { joint: 'temporomandibular', motion: 'depression', role: 'prime' },
      { joint: 'cervical_spine', motion: 'flexion', role: 'assist' },
    ],
    innervation: 'Anterior belly by CN V3 (mylohyoid nerve); posterior belly by CN VII',
    bloodSupply: 'Facial and occipital arteries',
    exercises: [
      {
        name: 'Resisted jaw opening',
        kind: 'isolation',
        equipment: 'Fingers under the chin',
        cue: 'Open the mouth against gentle resistance; used in temporomandibular rehab.',
        motion: 'Jaw depression',
      },
    ],
    antagonists: ['l_masseter', 'l_temporalis'],
    clinical:
      'A rare muscle group with two different cranial nerve supplies, reflecting its development from two pharyngeal arches.',
  },
  // ================================================================ SPINAL EXTENSORS
  {
    id: 'l_iliocostalis',
    name: 'Iliocostalis (erector spinae, lateral column)',
    latin: 'Musculus iliocostalis',
    side: 'left',
    group: 'Erector spinae',
    region: 'back',
    layer: 2,
    girth: 0.015,
    path: [
      p('pelvis', [0.046, 0.99, -0.05]),
      via('lumbar', [0.058, 1.12, -0.058]),
      via('thorax', [0.07, 1.26, -0.055]),
      p('thorax', [0.062, 1.35, -0.05]),
    ],
    originDesc: 'Sacrum, iliac crest and the thoracolumbar fascia via the common erector tendon',
    insertionDesc: 'Angles of the lower ribs, then successively upward to the cervical transverse processes',
    actions: [
      { joint: 'lumbar_spine', motion: 'extension', role: 'prime' },
      { joint: 'thoracic_spine', motion: 'extension', role: 'prime' },
      { joint: 'lumbar_spine', motion: 'left lateral flexion', role: 'prime' },
    ],
    innervation: 'Posterior rami of the spinal nerves',
    nerve: 'l_dorsal_rami',
    bloodSupply: 'Posterior intercostal and lumbar arteries',
    palpation: 'The lateral of the two long ridges either side of the spine.',
    exercises: [
      {
        name: 'Back extension (45° or horizontal)',
        kind: 'isolation',
        equipment: 'Roman chair / GHD',
        cue: 'Round down and extend segment by segment rather than hinging at the hip — hinging turns it into a hamstring exercise.',
        motion: 'Spinal extension',
      },
      {
        name: 'Suitcase carry',
        kind: 'activation',
        equipment: 'One heavy dumbbell',
        cue: 'Loaded on one side only; the contralateral iliocostalis and quadratus lumborum resist side-bending.',
        motion: 'Lateral flexion (anti-)',
      },
      {
        name: 'Deadlift',
        kind: 'compound',
        equipment: 'Barbell',
        cue: 'The erectors work isometrically to hold spinal position — that is the point of the lift, not the movement.',
        motion: 'Spinal extension (isometric)',
      },
    ],
    antagonists: ['l_rectus_abdominis', 'l_external_oblique'],
    synergists: ['l_longissimus', 'l_spinalis', 'l_multifidus'],
    clinical:
      'The erector group generates the largest extensor moment in the body but has a short moment arm, so lumbar compression forces in a heavy deadlift are enormous — technique matters more than tissue strength.',
  },
  {
    id: 'l_longissimus',
    name: 'Longissimus (erector spinae, intermediate column)',
    latin: 'Musculus longissimus',
    side: 'left',
    group: 'Erector spinae',
    region: 'back',
    layer: 2,
    girth: 0.016,
    path: [
      p('pelvis', [0.028, 0.99, -0.055]),
      via('lumbar', [0.036, 1.12, -0.06]),
      via('thorax', [0.042, 1.28, -0.06]),
      p('neck', [0.04, 1.5, -0.05]),
    ],
    originDesc: 'Common erector tendon from the sacrum and iliac crest, and the lumbar transverse processes',
    insertionDesc: 'Thoracic and cervical transverse processes; longissimus capitis reaches the mastoid process',
    actions: [
      { joint: 'lumbar_spine', motion: 'extension', role: 'prime' },
      { joint: 'thoracic_spine', motion: 'extension', role: 'prime' },
      { joint: 'cervical_spine', motion: 'extension', role: 'assist' },
      { joint: 'lumbar_spine', motion: 'left lateral flexion', role: 'assist' },
    ],
    innervation: 'Posterior rami of the spinal nerves',
    nerve: 'l_dorsal_rami',
    bloodSupply: 'Lumbar and posterior intercostal arteries',
    exercises: [
      {
        name: 'Romanian deadlift',
        kind: 'compound',
        equipment: 'Barbell or dumbbells',
        cue: 'Holds the spine in extension against a long lever — the classic isometric erector challenge.',
        motion: 'Spinal extension (isometric)',
      },
      {
        name: 'Bird dog',
        kind: 'activation',
        equipment: 'Bodyweight',
        cue: 'Opposite arm and leg, no rotation of the pelvis. Trains the erectors and multifidus in their real stabilising role.',
        motion: 'Anti-rotation + extension',
      },
      {
        name: 'Prone extension holds',
        kind: 'isolation',
        equipment: 'Bodyweight',
        cue: 'Small lift, long holds. Endurance of the extensors predicts low back pain better than their peak strength.',
        motion: 'Spinal extension',
      },
    ],
    antagonists: ['l_rectus_abdominis'],
    synergists: ['l_iliocostalis', 'l_multifidus'],
  },
  {
    id: 'l_spinalis',
    name: 'Spinalis (erector spinae, medial column)',
    latin: 'Musculus spinalis',
    side: 'left',
    group: 'Erector spinae',
    region: 'back',
    layer: 3,
    girth: 0.011,
    path: [
      p('lumbar', [0.015, 1.05, -0.055]),
      via('thorax', [0.016, 1.2, -0.06]),
      p('thorax', [0.016, 1.32, -0.062]),
    ],
    originDesc: 'Spinous processes of T11–L2',
    insertionDesc: 'Spinous processes of T2–T8',
    actions: [
      { joint: 'thoracic_spine', motion: 'extension', role: 'prime' },
      { joint: 'lumbar_spine', motion: 'extension', role: 'assist' },
    ],
    innervation: 'Posterior rami of the spinal nerves',
    nerve: 'l_dorsal_rami',
    bloodSupply: 'Posterior intercostal arteries',
    exercises: [
      {
        name: 'Thoracic extension over a foam roller',
        kind: 'stretch',
        equipment: 'Foam roller',
        cue: 'Roller across the mid back, extend over it segment by segment; restores the thoracic extension that spinalis controls.',
        motion: 'Thoracic extension',
      },
      {
        name: 'Prone "cobra" hold',
        kind: 'isolation',
        equipment: 'Bodyweight',
        cue: 'Lift the chest with the arms rotated out; targets the mid-thoracic extensors specifically.',
        motion: 'Thoracic extension',
      },
    ],
    synergists: ['l_longissimus'],
  },
  {
    id: 'l_multifidus',
    name: 'Multifidus',
    latin: 'Musculus multifidus',
    side: 'left',
    group: 'Transversospinalis',
    region: 'back',
    layer: 3,
    girth: 0.012,
    path: [
      p('pelvis', [0.02, 0.986, -0.048]),
      via('lumbar', [0.022, 1.09, -0.05]),
      p('thorax', [0.012, 1.17, -0.052]),
    ],
    originDesc: 'Sacrum, mamillary processes of the lumbar vertebrae, transverse processes of the thoracic vertebrae',
    insertionDesc: 'Spinous processes two to four segments above',
    actions: [
      { joint: 'lumbar_spine', motion: 'extension', role: 'assist' },
      { joint: 'lumbar_spine', motion: 'right rotation', role: 'assist' },
      { joint: 'lumbar_spine', motion: 'flexion', role: 'stabilise' },
      { joint: 'sacroiliac', motion: 'posterior tilt', role: 'stabilise' },
    ],
    innervation: 'Posterior rami of the spinal nerves (segmental)',
    nerve: 'l_dorsal_rami',
    bloodSupply: 'Lumbar arteries',
    exercises: [
      {
        name: 'Bird dog',
        kind: 'activation',
        equipment: 'Bodyweight',
        cue: 'Multifidus fires before limb movement in healthy people. Slow, controlled reps with a level pelvis retrain that timing.',
        motion: 'Segmental stabilisation',
      },
      {
        name: 'Prone segmental extension (quadruped rocking)',
        kind: 'activation',
        equipment: 'Bodyweight',
        cue: 'Small range, low load, high repetition — multifidus is an endurance stabiliser, not a mover.',
        motion: 'Segmental extension',
      },
      {
        name: 'Side plank',
        kind: 'activation',
        equipment: 'Bodyweight',
        cue: 'One of the highest multifidus-activation exercises measured, with low spinal compression.',
        motion: 'Lateral stabilisation',
      },
    ],
    synergists: ['l_transversus_abdominis', 'l_longissimus'],
    clinical:
      'Selectively atrophies at the affected segment within days of an episode of low back pain, and does not recover spontaneously — a specific reason to train it deliberately.',
  },
  {
    id: 'l_quadratus_lumborum',
    name: 'Quadratus lumborum',
    latin: 'Musculus quadratus lumborum',
    side: 'left',
    group: 'Posterior abdominal wall',
    region: 'back',
    layer: 3,
    girth: 0.013,
    path: [
      p('pelvis', [0.056, 1.006, -0.04]),
      via('lumbar', [0.05, 1.08, -0.038]),
      p('thorax', [0.045, 1.15, -0.035]),
    ],
    originDesc: 'Posterior iliac crest and the iliolumbar ligament',
    insertionDesc: '12th rib and the transverse processes of L1–L4',
    actions: [
      { joint: 'lumbar_spine', motion: 'left lateral flexion', role: 'prime' },
      { joint: 'lumbar_spine', motion: 'extension', role: 'assist' },
      { joint: 'sacroiliac', motion: 'anterior tilt', role: 'assist' },
      { joint: 'costovertebral', motion: 'depression', role: 'assist' },
    ],
    innervation: 'Subcostal nerve (T12) and the lumbar plexus (L1–L4)',
    bloodSupply: 'Lumbar arteries',
    palpation: 'Deep, between the 12th rib and the iliac crest lateral to the erector mass.',
    exercises: [
      {
        name: 'Suitcase carry',
        kind: 'activation',
        equipment: 'One heavy dumbbell or kettlebell',
        cue: 'The best functional loading: the QL on the *unloaded* side works isometrically to keep the trunk upright.',
        motion: 'Anti-lateral flexion',
      },
      {
        name: 'Side plank',
        kind: 'activation',
        equipment: 'Bodyweight',
        cue: 'Hips stacked and lifted; QL works with the obliques.',
        motion: 'Lateral flexion (isometric)',
      },
      {
        name: 'Standing side bend',
        kind: 'isolation',
        equipment: 'Dumbbell',
        cue: 'Slow and controlled; direct concentric loading of the QL, though carries load it less riskily.',
        motion: 'Lateral flexion',
      },
      {
        name: 'QL stretch (side-lying over a roller)',
        kind: 'stretch',
        equipment: 'Foam roller',
        cue: 'Lengthen from the iliac crest to the 12th rib; commonly tight with a leg-length difference or one-sided carrying habits.',
        motion: 'Contralateral side-bend',
      },
    ],
    antagonists: ['l_external_oblique'],
    synergists: ['l_iliocostalis', 'l_internal_oblique'],
    clinical:
      'A frequent source of deep, one-sided low back pain that worsens with standing and is missed because it lies deep to the erectors.',
  },
  {
    id: 'l_serratus_posterior_inferior',
    name: 'Serratus posterior inferior',
    latin: 'Musculus serratus posterior inferior',
    side: 'left',
    group: 'Respiratory',
    region: 'back',
    layer: 3,
    girth: 0.008,
    path: [
      p('lumbar', [0.012, 1.1, -0.055]),
      p('thorax', [0.07, 1.19, -0.045]),
    ],
    originDesc: 'Spinous processes of T11–L2 via the thoracolumbar fascia',
    insertionDesc: 'Inferior borders of ribs 9–12',
    actions: [
      { joint: 'costovertebral', motion: 'depression', role: 'assist' },
    ],
    innervation: 'Anterior rami of T9–T12',
    bloodSupply: 'Posterior intercostal arteries',
    exercises: [
      {
        name: 'Forced exhalation drill',
        kind: 'activation',
        equipment: 'None',
        cue: 'Long slow exhale through pursed lips; the lower ribs draw down and in.',
        motion: 'Rib depression',
      },
    ],
    clinical:
      'Its role is debated — it may act more as a proprioceptive organ for the thoracolumbar fascia than as a mover of ribs.',
  },
  // ================================================================== ABDOMINAL WALL
  {
    id: 'l_rectus_abdominis',
    name: 'Rectus abdominis',
    latin: 'Musculus rectus abdominis',
    side: 'left',
    group: 'Anterior abdominal wall',
    region: 'abdomen',
    layer: 1,
    girth: 0.022,
    path: [
      p('pelvis', [0.028, 0.886, 0.07]),
      via('lumbar', [0.03, 1.02, 0.085]),
      p('thorax', [0.03, 1.245, 0.085]),
    ],
    originDesc: 'Pubic crest and pubic symphysis',
    insertionDesc: 'Costal cartilages 5–7 and the xiphoid process',
    actions: [
      { joint: 'lumbar_spine', motion: 'flexion', role: 'prime' },
      { joint: 'thoracic_spine', motion: 'flexion', role: 'prime' },
      { joint: 'sacroiliac', motion: 'posterior tilt', role: 'assist' },
      { joint: 'costovertebral', motion: 'depression', role: 'assist' },
    ],
    innervation: 'Anterior rami of T7–T12 (thoracoabdominal nerves)',
    nerve: 'intercostal',
    bloodSupply: 'Superior and inferior epigastric arteries',
    palpation: 'The "six-pack"; the tendinous intersections create the visible segments.',
    exercises: [
      {
        name: 'Cable crunch',
        kind: 'isolation',
        equipment: 'High cable, rope',
        cue: 'Flex the *spine*, curling the ribs toward the pelvis, rather than hinging at the hip. Loadable progressively, unlike most ab work.',
        motion: 'Spinal flexion',
      },
      {
        name: 'Hanging leg raise (with a posterior pelvic tilt)',
        kind: 'isolation',
        equipment: 'Bar',
        cue: 'The rectus only works once the pelvis starts to tilt back — raising the legs to 90° without that is pure hip flexor work.',
        motion: 'Posterior pelvic tilt + spinal flexion',
      },
      {
        name: 'Ab wheel rollout',
        kind: 'compound',
        equipment: 'Ab wheel',
        cue: 'Resists extension eccentrically; keep the ribs down and the pelvis tucked throughout.',
        motion: 'Anti-extension',
      },
      {
        name: 'Cobra / prone press-up stretch',
        kind: 'stretch',
        equipment: 'Floor',
        cue: 'Lengthens the whole anterior wall from pubis to ribs.',
        motion: 'Spinal extension',
      },
    ],
    antagonists: ['l_iliocostalis', 'l_longissimus', 'l_spinalis'],
    synergists: ['l_external_oblique', 'l_internal_oblique'],
    clinical:
      'The tendinous intersections attach to the anterior rectus sheath only, which is why the "abs" show as blocks. Separation at the linea alba is diastasis recti, common post-partum.',
  },
  {
    id: 'l_external_oblique',
    name: 'External oblique',
    latin: 'Musculus obliquus externus abdominis',
    side: 'left',
    group: 'Lateral abdominal wall',
    region: 'abdomen',
    layer: 1,
    girth: 0.022,
    path: [
      p('thorax', [0.076, 1.24, 0.05]),
      via('lumbar', [0.086, 1.12, 0.055]),
      p('pelvis', [0.032, 0.986, 0.07]),
    ],
    originDesc: 'Outer surfaces of ribs 5–12, interdigitating with serratus anterior and latissimus dorsi',
    insertionDesc: 'Anterior half of the iliac crest, the pubic tubercle and the linea alba via a broad aponeurosis',
    actions: [
      { joint: 'lumbar_spine', motion: 'flexion', role: 'prime' },
      { joint: 'lumbar_spine', motion: 'right rotation', role: 'prime' },
      { joint: 'lumbar_spine', motion: 'left lateral flexion', role: 'assist' },
      { joint: 'thoracic_spine', motion: 'right rotation', role: 'prime' },
    ],
    innervation: 'Anterior rami of T7–T12',
    nerve: 'intercostal',
    bloodSupply: 'Lower posterior intercostal and deep circumflex iliac arteries',
    palpation: 'Fibres run "hands into pockets" — inferomedially — on the side of the abdomen.',
    exercises: [
      {
        name: 'Cable woodchop (high to low)',
        kind: 'isolation',
        equipment: 'Cable',
        cue: 'Rotate from the ribcage, not the arms. The left external oblique turns you to the *right* — it rotates contralaterally.',
        motion: 'Trunk rotation',
      },
      {
        name: 'Pallof press',
        kind: 'activation',
        equipment: 'Cable or band',
        cue: 'Anti-rotation: resist the pull rather than producing rotation. Trains the obliques the way they actually work in sport.',
        motion: 'Anti-rotation',
      },
      {
        name: 'Side plank',
        kind: 'activation',
        equipment: 'Bodyweight',
        cue: 'Loads both obliques and QL isometrically with very low spinal compression.',
        motion: 'Lateral stabilisation',
      },
      {
        name: 'Bicycle crunch',
        kind: 'isolation',
        equipment: 'Bodyweight',
        cue: 'Opposite elbow toward opposite knee — pairs the external oblique on one side with the internal oblique on the other.',
        motion: 'Flexion + rotation',
      },
    ],
    antagonists: ['l_iliocostalis', 'l_internal_oblique'],
    synergists: ['l_internal_oblique', 'l_rectus_abdominis'],
    clinical:
      'The external oblique on one side and the internal oblique on the other form a functional rotation couple — the anatomical basis of throwing and striking mechanics.',
  },
  {
    id: 'l_internal_oblique',
    name: 'Internal oblique',
    latin: 'Musculus obliquus internus abdominis',
    side: 'left',
    group: 'Lateral abdominal wall',
    region: 'abdomen',
    layer: 2,
    girth: 0.015,
    path: [
      p('pelvis', [0.08, 1.0, 0.04]),
      via('lumbar', [0.085, 1.1, 0.06]),
      p('thorax', [0.03, 1.22, 0.07]),
    ],
    originDesc: 'Thoracolumbar fascia, anterior two-thirds of the iliac crest and the lateral inguinal ligament',
    insertionDesc: 'Inferior borders of ribs 10–12, the linea alba and the pubic crest (conjoint tendon)',
    actions: [
      { joint: 'lumbar_spine', motion: 'left rotation', role: 'prime' },
      { joint: 'lumbar_spine', motion: 'flexion', role: 'assist' },
      { joint: 'lumbar_spine', motion: 'left lateral flexion', role: 'prime' },
      { joint: 'thoracic_spine', motion: 'left rotation', role: 'prime' },
    ],
    innervation: 'Anterior rami of T7–T12, iliohypogastric and ilioinguinal nerves (L1)',
    nerve: 'intercostal',
    bloodSupply: 'Deep circumflex iliac and lower intercostal arteries',
    exercises: [
      {
        name: 'Cable woodchop (low to high)',
        kind: 'isolation',
        equipment: 'Cable',
        cue: 'The left internal oblique rotates you to the *left* — ipsilateral rotation, the opposite of the external oblique.',
        motion: 'Trunk rotation',
      },
      {
        name: 'Landmine rotation',
        kind: 'compound',
        equipment: 'Barbell in a landmine',
        cue: 'Controlled rotation with the hips driving; keeps load off end-range lumbar rotation.',
        motion: 'Trunk rotation',
      },
      {
        name: 'Side plank with rotation',
        kind: 'isolation',
        equipment: 'Bodyweight',
        cue: 'Thread the top arm under the body and back — combines lateral stability with rotation.',
        motion: 'Lateral flexion + rotation',
      },
    ],
    antagonists: ['l_external_oblique'],
    synergists: ['l_transversus_abdominis', 'l_rectus_abdominis'],
    clinical:
      'Its lowest fibres form the conjoint tendon and the cremaster; weakness here contributes to inguinal hernia and to "sportsman\'s groin".',
  },
  {
    id: 'l_transversus_abdominis',
    name: 'Transversus abdominis',
    latin: 'Musculus transversus abdominis',
    side: 'left',
    group: 'Deep abdominal wall',
    region: 'abdomen',
    layer: 3,
    girth: 0.013,
    path: [
      p('pelvis', [0.07, 1.0, -0.008]),
      via('lumbar', [0.09, 1.06, 0.042]),
      p('lumbar', [0.012, 1.05, 0.082]),
    ],
    originDesc: 'Thoracolumbar fascia, iliac crest, lateral inguinal ligament and the inner surfaces of costal cartilages 7–12',
    insertionDesc: 'Linea alba, pubic crest and pecten pubis via the conjoint tendon',
    actions: [
      { joint: 'lumbar_spine', motion: 'flexion', role: 'stabilise' },
      { joint: 'sacroiliac', motion: 'posterior tilt', role: 'stabilise' },
      { joint: 'costovertebral', motion: 'depression', role: 'assist' },
    ],
    innervation: 'Anterior rami of T7–T12, iliohypogastric and ilioinguinal nerves',
    nerve: 'intercostal',
    bloodSupply: 'Deep circumflex iliac and lumbar arteries',
    exercises: [
      {
        name: 'Abdominal draw-in / hollowing',
        kind: 'activation',
        equipment: 'None',
        cue: 'Gently draw the navel toward the spine without holding the breath or moving the ribs. Its fibres run horizontally, so it acts as a corset rather than a mover.',
        motion: 'Abdominal compression',
      },
      {
        name: 'Dead bug',
        kind: 'activation',
        equipment: 'Bodyweight',
        cue: 'Keep the low back flat on the floor while the limbs move — direct training of the anticipatory stabilising role.',
        motion: 'Anti-extension',
      },
      {
        name: 'Diaphragmatic breathing with 360° expansion',
        kind: 'activation',
        equipment: 'None',
        cue: 'TVA works with the diaphragm and pelvic floor to manage intra-abdominal pressure; coordinating them beats training any one alone.',
        motion: 'Pressure regulation',
      },
    ],
    synergists: ['l_multifidus', 'l_internal_oblique', 'pelvic_floor', 'diaphragm'],
    clinical:
      'In healthy people it activates milliseconds *before* a limb moves; that feed-forward timing is delayed in chronic low back pain and is the rationale behind motor-control training.',
  },
  {
    id: 'l_intercostals',
    name: 'Intercostal muscles (external and internal)',
    latin: 'Musculi intercostales',
    side: 'left',
    group: 'Respiratory',
    region: 'abdomen',
    layer: 2,
    girth: 0.009,
    path: [
      p('thorax', [0.06, 1.29, 0.03]),
      via('thorax', [0.072, 1.27, 0.036]),
      p('thorax', [0.066, 1.245, 0.042]),
    ],
    originDesc: 'Inferior border of each rib',
    insertionDesc: 'Superior border of the rib below',
    actions: [
      { joint: 'costovertebral', motion: 'elevation', role: 'prime' },
      { joint: 'thoracic_spine', motion: 'right rotation', role: 'stabilise' },
    ],
    innervation: 'Intercostal nerves (T1–T11)',
    nerve: 'intercostal',
    bloodSupply: 'Posterior and anterior intercostal arteries',
    exercises: [
      {
        name: 'Ribcage expansion breathing',
        kind: 'activation',
        equipment: 'Band around the lower ribs',
        cue: 'Breathe into the band laterally; the external intercostals elevate the ribs on inspiration.',
        motion: 'Rib elevation',
      },
      {
        name: 'Side-lying thoracic opener',
        kind: 'stretch',
        equipment: 'Foam roller',
        cue: 'Reach the top arm overhead and breathe into the stretched side.',
        motion: 'Rib separation',
      },
    ],
    clinical:
      'The neurovascular bundle runs in the costal groove at the lower border of each rib — the reason procedures enter just above the rib below.',
  },
  {
    id: 'diaphragm',
    name: 'Diaphragm',
    latin: 'Diaphragma',
    side: 'center',
    group: 'Respiratory',
    region: 'abdomen',
    layer: 3,
    girth: 0.02,
    path: [
      p('thorax', [-0.07, 1.235, 0.045]),
      via('thorax', [0.0, 1.275, 0.005]),
      p('thorax', [0.07, 1.235, 0.045]),
    ],
    originDesc: 'Xiphoid process, inner surfaces of the lower six costal cartilages, and the crura from L1–L3',
    insertionDesc: 'Central tendon',
    actions: [
      { joint: 'costovertebral', motion: 'elevation', role: 'prime' },
      { joint: 'lumbar_spine', motion: 'flexion', role: 'stabilise' },
    ],
    innervation: 'Phrenic nerve (C3, C4, C5 — "C3, 4, 5 keeps the diaphragm alive")',
    nerve: 'phrenic',
    bloodSupply: 'Inferior phrenic, musculophrenic and pericardiacophrenic arteries',
    exercises: [
      {
        name: 'Crocodile (prone) breathing',
        kind: 'activation',
        equipment: 'Floor',
        cue: 'Lying face down, feel the belly press into the floor with each inhale. Removes the option of shoulder-led breathing.',
        motion: 'Inspiration',
      },
      {
        name: '90/90 breathing with a wall',
        kind: 'activation',
        equipment: 'Wall, bodyweight',
        cue: 'Hips and knees at 90°, exhale fully to feel the lower ribs draw down before inhaling into the back and sides.',
        motion: 'Inspiration/expiration',
      },
      {
        name: 'Inspiratory muscle training',
        kind: 'isolation',
        equipment: 'Threshold trainer',
        cue: 'Resisted inhalation; genuinely improves endurance performance in trained athletes.',
        motion: 'Resisted inspiration',
      },
    ],
    synergists: ['l_transversus_abdominis', 'pelvic_floor'],
    clinical:
      'Its C3–C5 supply is why a high cervical cord injury stops breathing while a lower one does not. Irritation of its peritoneal surface refers pain to the shoulder tip via the phrenic nerve.',
  },
  {
    id: 'pelvic_floor',
    name: 'Pelvic floor (levator ani and coccygeus)',
    latin: 'Diaphragma pelvis',
    side: 'center',
    group: 'Pelvic floor',
    region: 'abdomen',
    layer: 3,
    girth: 0.012,
    path: [
      p('pelvis', [-0.045, 0.868, 0.03]),
      via('pelvis', [0.0, 0.852, -0.012]),
      p('pelvis', [0.045, 0.868, 0.03]),
    ],
    originDesc: 'Body of the pubis, tendinous arch of the obturator fascia and the ischial spine',
    insertionDesc: 'Perineal body, anococcygeal ligament and the coccyx',
    actions: [
      { joint: 'sacroiliac', motion: 'posterior tilt', role: 'stabilise' },
      { joint: 'lumbar_spine', motion: 'flexion', role: 'stabilise' },
    ],
    innervation: 'Nerve to levator ani (S3–S4) and the pudendal nerve (S2–S4)',
    nerve: 'pudendal',
    bloodSupply: 'Internal pudendal and inferior gluteal arteries',
    exercises: [
      {
        name: 'Pelvic floor contraction (Kegel)',
        kind: 'isolation',
        equipment: 'None',
        cue: 'Lift up and in as if stopping wind, without squeezing the glutes or holding the breath. Both quick flicks and long holds — the muscle has both fibre types.',
        motion: 'Pelvic floor elevation',
      },
      {
        name: 'Breath-coordinated pelvic floor work',
        kind: 'activation',
        equipment: 'None',
        cue: 'Exhale and lift, inhale and release. The floor moves reciprocally with the diaphragm — training them together works better than either alone.',
        motion: 'Pressure regulation',
      },
      {
        name: 'Deep squat with relaxation focus',
        kind: 'stretch',
        equipment: 'Bodyweight',
        cue: 'An overactive pelvic floor is as much of a problem as a weak one; learning to release it matters.',
        motion: 'Pelvic floor lengthening',
      },
    ],
    synergists: ['l_transversus_abdominis', 'diaphragm'],
    clinical:
      'Forms the bottom of the abdominal pressure canister with the diaphragm above and transversus abdominis around; dysfunction shows as incontinence, prolapse or persistent pelvic pain.',
  },
];
