/**
 * Muscles of the hip, thigh, leg and foot. Left side only — `bilateral()` mirrors them.
 */

import { p, via } from './muscleHelpers';
import type { MuscleDef } from './types';

export const LOWER_MUSCLES: MuscleDef[] = [
  // ======================================================================== GLUTEALS
  {
    id: 'l_gluteus_maximus',
    name: 'Gluteus maximus',
    latin: 'Musculus gluteus maximus',
    side: 'left',
    group: 'Gluteal group',
    region: 'hip',
    layer: 1,
    girth: 0.036,
    path: [
      p('pelvis', [0.052, 1.002, -0.062]),
      via('pelvis', [0.098, 0.938, -0.052]),
      p('l_hip', [0.124, 0.858, -0.022]),
    ],
    originDesc:
      'Posterior gluteal line of the ilium, posterior sacrum and coccyx, sacrotuberous ligament and the thoracolumbar fascia',
    insertionDesc: 'Iliotibial tract (upper three-quarters) and the gluteal tuberosity of the femur',
    actions: [
      { joint: 'l_hip', motion: 'extension', role: 'prime' },
      { joint: 'l_hip', motion: 'external rotation', role: 'prime' },
      { joint: 'l_hip', motion: 'abduction', role: 'assist' },
      { joint: 'l_knee', motion: 'extension', role: 'stabilise' },
      { joint: 'sacroiliac', motion: 'posterior tilt', role: 'assist' },
    ],
    innervation: 'Inferior gluteal nerve (L5, S1, S2)',
    nerve: 'l_inferior_gluteal',
    bloodSupply: 'Inferior and superior gluteal arteries',
    fiberType: 'Mixed; the largest muscle in the body by volume',
    palpation: 'Squeeze the buttocks — the whole superficial mass posterior to the hip.',
    exercises: [
      {
        name: 'Barbell hip thrust',
        kind: 'isolation',
        equipment: 'Barbell, bench',
        cue: 'Peak resistance occurs at full hip extension, exactly where the glute is strongest and where squats give almost nothing. Chin tucked, ribs down, and hold the top for a beat.',
        motion: 'Hip extension',
      },
      {
        name: 'Romanian deadlift',
        kind: 'compound',
        equipment: 'Barbell or dumbbells',
        cue: 'Push the hips back with a soft knee; loads the glutes and hamstrings in a lengthened position.',
        motion: 'Hip extension',
      },
      {
        name: 'Bulgarian split squat',
        kind: 'compound',
        equipment: 'Bench, dumbbells',
        cue: 'A longer stance and a forward torso lean shift load from the quads to the glutes.',
        motion: 'Hip extension',
      },
      {
        name: 'Cable hip extension / kickback',
        kind: 'isolation',
        equipment: 'Cable with an ankle strap',
        cue: 'Keep the pelvis square and stop when the hip reaches neutral — going further is lumbar extension, not glute work.',
        motion: 'Hip extension',
      },
      {
        name: 'Figure-4 (piriformis) stretch',
        kind: 'stretch',
        equipment: 'Chair or floor',
        cue: 'Ankle over the opposite knee and lean forward; stretches the deep and superficial external rotators together.',
        motion: 'Hip flexion + adduction + internal rotation',
      },
    ],
    antagonists: ['l_psoas_major', 'l_iliacus', 'l_rectus_femoris'],
    synergists: ['l_biceps_femoris_long', 'l_semitendinosus', 'l_adductor_magnus'],
    clinical:
      'Its upper fibres and the deep rotators are the main hip stabilisers in single-leg stance. Delayed gluteus maximus activation is associated with hamstring strain and with low back pain.',
  },
  {
    id: 'l_gluteus_medius',
    name: 'Gluteus medius',
    latin: 'Musculus gluteus medius',
    side: 'left',
    group: 'Gluteal group',
    region: 'hip',
    layer: 2,
    girth: 0.019,
    path: [
      p('pelvis', [0.1, 1.016, -0.012]),
      p('l_hip', [0.118, 0.926, -0.012]),
    ],
    originDesc: 'Outer surface of the ilium between the posterior and anterior gluteal lines',
    insertionDesc: 'Lateral surface of the greater trochanter',
    actions: [
      { joint: 'l_hip', motion: 'abduction', role: 'prime' },
      { joint: 'l_hip', motion: 'internal rotation', role: 'assist' },
      { joint: 'l_hip', motion: 'external rotation', role: 'assist' },
      { joint: 'sacroiliac', motion: 'left lateral flexion', role: 'stabilise' },
    ],
    innervation: 'Superior gluteal nerve (L4, L5, S1)',
    nerve: 'l_superior_gluteal',
    bloodSupply: 'Superior gluteal artery',
    palpation: 'Just below the iliac crest laterally; stand on one leg and feel it fire.',
    exercises: [
      {
        name: 'Side-lying hip abduction',
        kind: 'isolation',
        equipment: 'Bodyweight or ankle weight',
        cue: 'Lead with the heel and let the hip extend very slightly — if the leg drifts forward, TFL takes over.',
        motion: 'Hip abduction',
      },
      {
        name: 'Single-leg stance / Trendelenburg hold',
        kind: 'activation',
        equipment: 'Bodyweight',
        cue: 'Its real job is to stop the opposite side of the pelvis dropping. Hold 30 s and watch the pelvis stay level.',
        motion: 'Frontal-plane pelvic control',
      },
      {
        name: 'Banded lateral walk',
        kind: 'activation',
        equipment: 'Loop band around the knees or ankles',
        cue: 'Slight hip and knee bend, feet pointed straight, keep tension on the band throughout.',
        motion: 'Hip abduction',
      },
      {
        name: 'Copenhagen / side plank with leg lift',
        kind: 'isolation',
        equipment: 'Bench, bodyweight',
        cue: 'The top-leg abduction under a long lever produces very high gluteus medius activation.',
        motion: 'Hip abduction (loaded)',
      },
    ],
    antagonists: ['l_adductor_longus', 'l_adductor_magnus', 'l_gracilis'],
    synergists: ['l_gluteus_minimus', 'l_tensor_fasciae_latae'],
    clinical:
      'Weakness produces the Trendelenburg sign and a contralateral pelvic drop in running gait — a leading contributor to patellofemoral pain and iliotibial band syndrome.',
  },
  {
    id: 'l_gluteus_minimus',
    name: 'Gluteus minimus',
    latin: 'Musculus gluteus minimus',
    side: 'left',
    group: 'Gluteal group',
    region: 'hip',
    layer: 3,
    girth: 0.014,
    path: [
      p('pelvis', [0.098, 0.986, 0.006]),
      p('l_hip', [0.112, 0.922, 0.01]),
    ],
    originDesc: 'Outer ilium between the anterior and inferior gluteal lines',
    insertionDesc: 'Anterior border of the greater trochanter',
    actions: [
      { joint: 'l_hip', motion: 'abduction', role: 'prime' },
      { joint: 'l_hip', motion: 'internal rotation', role: 'prime' },
      { joint: 'l_hip', motion: 'flexion', role: 'assist' },
    ],
    innervation: 'Superior gluteal nerve (L4, L5, S1)',
    nerve: 'l_superior_gluteal',
    bloodSupply: 'Superior gluteal artery',
    exercises: [
      {
        name: 'Side-lying abduction with internal rotation',
        kind: 'isolation',
        equipment: 'Bodyweight',
        cue: 'Turning the toe slightly down biases gluteus minimus over the posterior fibres of medius.',
        motion: 'Hip abduction + internal rotation',
      },
      {
        name: 'Standing hip hitch',
        kind: 'activation',
        equipment: 'Step',
        cue: 'Stand on one leg on a step and lift the opposite pelvis; loads the abductors in their stabilising role.',
        motion: 'Pelvic elevation',
      },
    ],
    synergists: ['l_gluteus_medius', 'l_tensor_fasciae_latae'],
    clinical:
      'Tendinopathy of the gluteus medius and minimus at the greater trochanter is now understood to be the true cause of most "trochanteric bursitis".',
  },
  {
    id: 'l_tensor_fasciae_latae',
    name: 'Tensor fasciae latae and iliotibial band',
    latin: 'Musculus tensor fasciae latae',
    side: 'left',
    group: 'Gluteal group',
    region: 'hip',
    layer: 1,
    girth: 0.012,
    path: [
      p('pelvis', [0.104, 1.0, 0.062]),
      via('l_hip', [0.128, 0.86, 0.032]),
      via('l_hip', [0.134, 0.66, 0.012]),
      p('l_knee', [0.13, 0.49, 0.008]),
    ],
    originDesc: 'Anterior iliac crest and the outer lip just behind the ASIS',
    insertionDesc: 'Iliotibial tract, which inserts on Gerdy\'s tubercle of the lateral tibial condyle',
    actions: [
      { joint: 'l_hip', motion: 'abduction', role: 'prime' },
      { joint: 'l_hip', motion: 'flexion', role: 'assist' },
      { joint: 'l_hip', motion: 'internal rotation', role: 'assist' },
      { joint: 'l_knee', motion: 'extension', role: 'stabilise' },
    ],
    innervation: 'Superior gluteal nerve (L4, L5, S1)',
    nerve: 'l_superior_gluteal',
    bloodSupply: 'Superior gluteal and lateral circumflex femoral arteries',
    exercises: [
      {
        name: 'Side-lying hip abduction with the hip flexed',
        kind: 'isolation',
        equipment: 'Bodyweight',
        cue: 'Flexing the hip 30° and letting the leg drift forward deliberately biases TFL — useful to know so that you can avoid it when training gluteus medius.',
        motion: 'Hip abduction + flexion',
      },
      {
        name: 'Standing ITB stretch',
        kind: 'stretch',
        equipment: 'None',
        cue: 'Cross the leg behind and lean away. The band itself barely stretches; what you are influencing is TFL and gluteus maximus above it.',
        motion: 'Hip adduction + extension',
      },
      {
        name: 'Lateral step-down',
        kind: 'compound',
        equipment: 'Step',
        cue: 'Trains the abductors eccentrically in the pattern that fails in runners with ITB syndrome.',
        motion: 'Frontal-plane control',
      },
    ],
    antagonists: ['l_adductor_longus', 'l_gluteus_maximus'],
    synergists: ['l_gluteus_medius', 'l_gluteus_minimus'],
    clinical:
      'Iliotibial band syndrome is compression of the fat pad beneath the band near the lateral femoral epicondyle at about 30° of knee flexion, not friction — which is why foam rolling the band itself rarely helps and hip strengthening does.',
  },
  {
    id: 'l_piriformis',
    name: 'Piriformis',
    latin: 'Musculus piriformis',
    side: 'left',
    group: 'Deep hip rotators',
    region: 'hip',
    layer: 3,
    girth: 0.011,
    path: [
      p('pelvis', [0.03, 0.952, -0.05]),
      via('pelvis', [0.08, 0.942, -0.04]),
      p('l_hip', [0.113, 0.932, -0.012]),
    ],
    originDesc: 'Anterior surface of the sacrum (S2–S4), passing through the greater sciatic foramen',
    insertionDesc: 'Superior border of the greater trochanter',
    actions: [
      { joint: 'l_hip', motion: 'external rotation', role: 'prime' },
      { joint: 'l_hip', motion: 'abduction', role: 'assist' },
      { joint: 'sacroiliac', motion: 'posterior tilt', role: 'stabilise' },
    ],
    innervation: 'Nerve to piriformis (S1, S2)',
    bloodSupply: 'Superior and inferior gluteal arteries',
    exercises: [
      {
        name: 'Figure-4 stretch',
        kind: 'stretch',
        equipment: 'Floor or chair',
        cue: 'Ankle across the opposite knee, draw the knee toward the opposite shoulder. Hold 30–45 s.',
        motion: 'Hip flexion + adduction + internal rotation',
      },
      {
        name: 'Clamshell',
        kind: 'isolation',
        equipment: 'Band, bodyweight',
        cue: 'Side-lying, hips flexed 45°, open the top knee without rolling the pelvis back.',
        motion: 'Hip external rotation',
      },
      {
        name: 'Seated banded external rotation',
        kind: 'isolation',
        equipment: 'Band',
        cue: 'With the hip flexed past 60° piriformis becomes an internal rotator instead — a rare example of a muscle reversing its action with joint position.',
        motion: 'Hip external rotation',
      },
    ],
    antagonists: ['l_gluteus_minimus', 'l_tensor_fasciae_latae'],
    synergists: ['l_deep_rotators', 'l_gluteus_maximus'],
    clinical:
      'The sciatic nerve passes beneath it (and through it in about 15% of people) — the anatomical basis of piriformis syndrome, which mimics lumbar radiculopathy but has no back pain and normal straight-leg raise.',
  },
  {
    id: 'l_deep_rotators',
    name: 'Deep external rotators (obturators, gemelli, quadratus femoris)',
    latin: 'Musculi rotatores coxae',
    side: 'left',
    group: 'Deep hip rotators',
    region: 'hip',
    layer: 3,
    girth: 0.01,
    path: [
      p('pelvis', [0.065, 0.886, -0.03]),
      p('l_hip', [0.108, 0.918, -0.015]),
    ],
    originDesc: 'Obturator membrane and ischium — ischial spine, ischial tuberosity and the obturator foramen margins',
    insertionDesc: 'Trochanteric fossa and the intertrochanteric crest of the femur',
    actions: [
      { joint: 'l_hip', motion: 'external rotation', role: 'prime' },
      { joint: 'l_hip', motion: 'adduction', role: 'assist' },
    ],
    innervation: 'Nerve to obturator internus (L5, S1) and nerve to quadratus femoris (L4–S1)',
    bloodSupply: 'Inferior gluteal and medial circumflex femoral arteries',
    exercises: [
      {
        name: 'Clamshell / banded external rotation',
        kind: 'isolation',
        equipment: 'Band',
        cue: 'Slow, small range. These are the hip\'s equivalent of the rotator cuff — stabilisers first, movers second.',
        motion: 'Hip external rotation',
      },
      {
        name: 'Single-leg balance with rotational reach',
        kind: 'activation',
        equipment: 'Bodyweight',
        cue: 'They control femoral rotation under the pelvis — train them in weight bearing.',
        motion: 'Rotational control',
      },
    ],
    synergists: ['l_piriformis', 'l_gluteus_maximus'],
    clinical:
      'Collectively they compress the femoral head into the acetabulum, exactly as the rotator cuff does at the shoulder.',
  },
  // ==================================================================== HIP FLEXORS
  {
    id: 'l_psoas_major',
    name: 'Psoas major',
    latin: 'Musculus psoas major',
    side: 'left',
    group: 'Iliopsoas',
    region: 'hip',
    layer: 3,
    girth: 0.016,
    path: [
      p('lumbar', [0.026, 1.104, -0.018]),
      via('lumbar', [0.045, 1.03, 0.005]),
      via('pelvis', [0.062, 0.95, 0.028]),
      p('l_hip', [0.076, 0.886, -0.002]),
    ],
    originDesc: 'Transverse processes, bodies and intervertebral discs of T12–L5',
    insertionDesc: 'Lesser trochanter of the femur',
    actions: [
      { joint: 'l_hip', motion: 'flexion', role: 'prime' },
      { joint: 'l_hip', motion: 'external rotation', role: 'assist' },
      { joint: 'lumbar_spine', motion: 'flexion', role: 'assist' },
      { joint: 'sacroiliac', motion: 'anterior tilt', role: 'assist' },
    ],
    innervation: 'Anterior rami of L1–L3',
    nerve: 'l_lumbar_plexus',
    bloodSupply: 'Lumbar arteries, iliolumbar artery',
    exercises: [
      {
        name: 'Standing band hip flexion above 90°',
        kind: 'isolation',
        equipment: 'Band or cable',
        cue: 'Psoas dominates hip flexion *above* 90°; below that the rectus femoris does most of the work. Drive the knee high and hold.',
        motion: 'Hip flexion',
      },
      {
        name: 'Hanging knee raise to the chest',
        kind: 'isolation',
        equipment: 'Bar',
        cue: 'Take the knees past 90° to load the psoas rather than only the rectus femoris.',
        motion: 'Hip flexion',
      },
      {
        name: 'Half-kneeling hip flexor stretch',
        kind: 'stretch',
        equipment: 'Mat',
        cue: 'Tuck the pelvis posteriorly *first*, then shift forward. Without the tuck the movement comes from the lumbar spine and the psoas never lengthens.',
        motion: 'Hip extension',
      },
      {
        name: 'Copenhagen plank / dead bug',
        kind: 'activation',
        equipment: 'Bodyweight',
        cue: 'Trains the psoas in its stabilising role linking the lumbar spine to the femur.',
        motion: 'Lumbopelvic stabilisation',
      },
    ],
    antagonists: ['l_gluteus_maximus', 'l_biceps_femoris_long'],
    synergists: ['l_iliacus', 'l_rectus_femoris', 'l_sartorius'],
    clinical:
      'The only muscle connecting the spine to the leg. A psoas abscess or haematoma classically presents with a flexed hip the patient will not straighten, and the femoral nerve runs on its lateral border.',
  },
  {
    id: 'l_iliacus',
    name: 'Iliacus',
    latin: 'Musculus iliacus',
    side: 'left',
    group: 'Iliopsoas',
    region: 'hip',
    layer: 3,
    girth: 0.014,
    path: [
      p('pelvis', [0.076, 0.986, 0.022]),
      via('pelvis', [0.076, 0.944, 0.03]),
      p('l_hip', [0.077, 0.884, 0.0]),
    ],
    originDesc: 'Iliac fossa (the inner surface of the ilium) and the ala of the sacrum',
    insertionDesc: 'Lesser trochanter, blending with the psoas tendon',
    actions: [
      { joint: 'l_hip', motion: 'flexion', role: 'prime' },
      { joint: 'sacroiliac', motion: 'anterior tilt', role: 'prime' },
    ],
    innervation: 'Femoral nerve (L2, L3)',
    nerve: 'l_femoral',
    bloodSupply: 'Iliolumbar and deep circumflex iliac arteries',
    exercises: [
      {
        name: 'Seated hip flexor march with band',
        kind: 'isolation',
        equipment: 'Band',
        cue: 'Seated removes the lumbar contribution, so the hip flexion has to come from iliopsoas.',
        motion: 'Hip flexion',
      },
      {
        name: 'Supine straight-leg raise hold',
        kind: 'isolation',
        equipment: 'Bodyweight',
        cue: 'Keep the low back flat; if it arches, stop — the load has moved to the lumbar spine.',
        motion: 'Hip flexion (isometric)',
      },
    ],
    antagonists: ['l_gluteus_maximus'],
    synergists: ['l_psoas_major'],
    clinical:
      'Unlike psoas it does not cross the spine, so it tilts the pelvis anteriorly without directly flexing the lumbar spine.',
  },
  {
    id: 'l_sartorius',
    name: 'Sartorius',
    latin: 'Musculus sartorius',
    side: 'left',
    group: 'Anterior thigh',
    region: 'thigh',
    layer: 1,
    girth: 0.011,
    path: [
      p('pelvis', [0.104, 0.998, 0.072]),
      via('l_hip', [0.112, 0.8, 0.032]),
      via('l_hip', [0.086, 0.6, 0.002]),
      p('l_knee', [0.075, 0.44, 0.014]),
    ],
    originDesc: 'Anterior superior iliac spine (ASIS)',
    insertionDesc: 'Superomedial surface of the tibia at the pes anserinus',
    actions: [
      { joint: 'l_hip', motion: 'flexion', role: 'assist' },
      { joint: 'l_hip', motion: 'abduction', role: 'assist' },
      { joint: 'l_hip', motion: 'external rotation', role: 'assist' },
      { joint: 'l_knee', motion: 'flexion', role: 'assist' },
      { joint: 'l_knee', motion: 'internal rotation', role: 'assist' },
    ],
    innervation: 'Femoral nerve (L2, L3)',
    nerve: 'l_femoral',
    bloodSupply: 'Femoral artery (muscular branches)',
    fiberType: 'The longest muscle in the human body (~50 cm)',
    exercises: [
      {
        name: 'Seated cross-legged (tailor) position',
        kind: 'activation',
        equipment: 'None',
        cue: 'Its Latin name comes from *sartor*, a tailor: it produces the exact combination — hip flexion, abduction and external rotation with knee flexion — of the cross-legged sitting posture.',
        motion: 'Combined hip flexion/abduction/external rotation',
      },
      {
        name: 'Cable hip flexion with external rotation',
        kind: 'isolation',
        equipment: 'Cable',
        cue: 'Drive the knee up and across outward to match all four of its actions.',
        motion: 'Hip flexion + abduction + external rotation',
      },
      {
        name: 'Standing quad + hip flexor stretch',
        kind: 'stretch',
        equipment: 'None',
        cue: 'Extend and internally rotate the hip with the knee bent.',
        motion: 'Hip extension + internal rotation',
      },
    ],
    synergists: ['l_iliacus', 'l_rectus_femoris', 'l_gracilis'],
    clinical:
      'Forms the lateral border of the femoral triangle and crosses the femoral artery at the apex — a key surgical landmark. Its ASIS origin is a common adolescent avulsion site in sprinters.',
  },
  // ====================================================================== ADDUCTORS
  {
    id: 'l_pectineus',
    name: 'Pectineus',
    latin: 'Musculus pectineus',
    side: 'left',
    group: 'Adductor group',
    region: 'thigh',
    layer: 2,
    girth: 0.011,
    path: [
      p('pelvis', [0.04, 0.896, 0.06]),
      p('l_hip', [0.072, 0.875, -0.01]),
    ],
    originDesc: 'Pectineal line (pecten pubis) of the superior pubic ramus',
    insertionDesc: 'Pectineal line of the femur, below the lesser trochanter',
    actions: [
      { joint: 'l_hip', motion: 'adduction', role: 'prime' },
      { joint: 'l_hip', motion: 'flexion', role: 'assist' },
      { joint: 'l_hip', motion: 'internal rotation', role: 'assist' },
    ],
    innervation: 'Femoral nerve (L2, L3), sometimes also the obturator nerve',
    nerve: 'l_femoral',
    bloodSupply: 'Medial circumflex femoral artery',
    exercises: [
      {
        name: 'Standing cable hip adduction',
        kind: 'isolation',
        equipment: 'Cable with ankle strap',
        cue: 'Sweep the leg across the midline with a slight forward angle to catch pectineus\' flexion component.',
        motion: 'Hip adduction + flexion',
      },
      {
        name: 'Adductor machine',
        kind: 'isolation',
        equipment: 'Machine',
        cue: 'Trains the whole group; sitting more upright biases the upper adductors including pectineus.',
        motion: 'Hip adduction',
      },
    ],
    antagonists: ['l_gluteus_medius', 'l_tensor_fasciae_latae'],
    synergists: ['l_adductor_longus', 'l_adductor_brevis'],
    clinical:
      'Forms the floor of the femoral triangle. A dual nerve supply (femoral and obturator) is common here, reflecting its transitional position between the flexor and adductor groups.',
  },
  {
    id: 'l_adductor_longus',
    name: 'Adductor longus',
    latin: 'Musculus adductor longus',
    side: 'left',
    group: 'Adductor group',
    region: 'thigh',
    layer: 1,
    girth: 0.015,
    path: [
      p('pelvis', [0.028, 0.888, 0.068]),
      via('l_hip', [0.06, 0.8, 0.018]),
      p('l_hip', [0.078, 0.71, -0.012]),
    ],
    originDesc: 'Anterior body of the pubis just below the pubic crest',
    insertionDesc: 'Middle third of the linea aspera of the femur',
    actions: [
      { joint: 'l_hip', motion: 'adduction', role: 'prime' },
      { joint: 'l_hip', motion: 'flexion', role: 'assist' },
      { joint: 'l_hip', motion: 'internal rotation', role: 'assist' },
    ],
    innervation: 'Obturator nerve, anterior division (L2–L4)',
    nerve: 'l_obturator',
    bloodSupply: 'Deep femoral and obturator arteries',
    palpation: 'The most prominent tendon in the groin when you squeeze the knees together.',
    exercises: [
      {
        name: 'Copenhagen adduction',
        kind: 'isolation',
        equipment: 'Bench',
        cue: 'Side plank with the top leg on a bench and the bottom leg lifted to meet it. The most effective adductor exercise studied, and it reduces groin injury rates in field sports.',
        motion: 'Hip adduction (eccentric and isometric)',
      },
      {
        name: 'Cable hip adduction',
        kind: 'isolation',
        equipment: 'Cable',
        cue: 'Cross the midline fully; the adductors are strongest in the last part of the range.',
        motion: 'Hip adduction',
      },
      {
        name: 'Ball squeeze isometric',
        kind: 'activation',
        equipment: 'Ball',
        cue: 'Squeeze at 45° hip flexion; the standard test and early rehab exercise for adductor-related groin pain.',
        motion: 'Hip adduction (isometric)',
      },
      {
        name: 'Cossack squat / adductor stretch',
        kind: 'stretch',
        equipment: 'Bodyweight',
        cue: 'Shift the weight to one bent leg with the other straight; lengthens the whole group.',
        motion: 'Hip abduction',
      },
    ],
    antagonists: ['l_gluteus_medius', 'l_gluteus_minimus', 'l_tensor_fasciae_latae'],
    synergists: ['l_adductor_brevis', 'l_adductor_magnus', 'l_gracilis'],
    clinical:
      'The most commonly strained adductor, usually at its proximal tendon. Adductor squeeze strength is the standard screening measure for groin injury risk in football and hockey.',
  },
  {
    id: 'l_adductor_brevis',
    name: 'Adductor brevis',
    latin: 'Musculus adductor brevis',
    side: 'left',
    group: 'Adductor group',
    region: 'thigh',
    layer: 2,
    girth: 0.013,
    path: [
      p('pelvis', [0.03, 0.868, 0.05]),
      p('l_hip', [0.074, 0.8, -0.012]),
    ],
    originDesc: 'Body and inferior ramus of the pubis',
    insertionDesc: 'Pectineal line and proximal linea aspera of the femur',
    actions: [
      { joint: 'l_hip', motion: 'adduction', role: 'prime' },
      { joint: 'l_hip', motion: 'flexion', role: 'assist' },
    ],
    innervation: 'Obturator nerve (L2–L4)',
    nerve: 'l_obturator',
    bloodSupply: 'Obturator and deep femoral arteries',
    exercises: [
      {
        name: 'Side-lying bottom-leg adduction',
        kind: 'isolation',
        equipment: 'Bodyweight',
        cue: 'Top leg supported, lift the bottom leg to meet it. Simple and very targeted.',
        motion: 'Hip adduction',
      },
      {
        name: 'Copenhagen adduction (short lever)',
        kind: 'isolation',
        equipment: 'Bench',
        cue: 'Knee on the bench rather than the ankle — a regression that lets you build up safely.',
        motion: 'Hip adduction',
      },
    ],
    synergists: ['l_adductor_longus', 'l_pectineus'],
    clinical:
      'The two divisions of the obturator nerve straddle it — an important landmark in the medial thigh.',
  },
  {
    id: 'l_adductor_magnus',
    name: 'Adductor magnus',
    latin: 'Musculus adductor magnus',
    side: 'left',
    group: 'Adductor group',
    region: 'thigh',
    layer: 2,
    girth: 0.021,
    path: [
      p('pelvis', [0.056, 0.85, -0.03]),
      via('l_hip', [0.075, 0.72, -0.02]),
      p('l_hip', [0.078, 0.52, -0.006]),
    ],
    originDesc: 'Inferior pubic ramus, ischial ramus (adductor part) and ischial tuberosity (hamstring part)',
    insertionDesc: 'Whole length of the linea aspera and the adductor tubercle of the medial femoral condyle',
    actions: [
      { joint: 'l_hip', motion: 'adduction', role: 'prime' },
      { joint: 'l_hip', motion: 'extension', role: 'prime' },
      { joint: 'l_hip', motion: 'internal rotation', role: 'assist' },
    ],
    innervation: 'Obturator nerve (adductor part, L2–L4) and the tibial division of the sciatic nerve (hamstring part, L4)',
    nerve: 'l_obturator',
    bloodSupply: 'Deep femoral (perforating) and obturator arteries',
    exercises: [
      {
        name: 'Deep squat (below parallel)',
        kind: 'compound',
        equipment: 'Barbell or bodyweight',
        cue: 'Adductor magnus is a powerful hip extensor at depth — in a deep squat it contributes as much extensor moment as the glutes.',
        motion: 'Hip extension + adduction',
      },
      {
        name: 'Sumo deadlift',
        kind: 'compound',
        equipment: 'Barbell',
        cue: 'The wide stance places the adductors in a lengthened, mechanically advantaged position for extension.',
        motion: 'Hip extension',
      },
      {
        name: 'Copenhagen adduction',
        kind: 'isolation',
        equipment: 'Bench',
        cue: 'Targets the adductor portion specifically.',
        motion: 'Hip adduction',
      },
    ],
    antagonists: ['l_gluteus_medius', 'l_psoas_major'],
    synergists: ['l_gluteus_maximus', 'l_biceps_femoris_long'],
    clinical:
      'The largest adductor and functionally a hybrid — part adductor, part hamstring, with two different nerve supplies to prove it. Its tendon forms the adductor hiatus, through which the femoral vessels reach the popliteal fossa.',
  },
  {
    id: 'l_gracilis',
    name: 'Gracilis',
    latin: 'Musculus gracilis',
    side: 'left',
    group: 'Adductor group',
    region: 'thigh',
    layer: 1,
    girth: 0.01,
    path: [
      p('pelvis', [0.024, 0.87, 0.05]),
      via('l_hip', [0.062, 0.7, 0.0]),
      p('l_knee', [0.074, 0.435, 0.014]),
    ],
    originDesc: 'Body and inferior ramus of the pubis',
    insertionDesc: 'Superomedial tibia at the pes anserinus',
    actions: [
      { joint: 'l_hip', motion: 'adduction', role: 'prime' },
      { joint: 'l_knee', motion: 'flexion', role: 'assist' },
      { joint: 'l_knee', motion: 'internal rotation', role: 'assist' },
    ],
    innervation: 'Obturator nerve (L2, L3)',
    nerve: 'l_obturator',
    bloodSupply: 'Obturator and medial circumflex femoral arteries',
    exercises: [
      {
        name: 'Seated adduction with the knee bent',
        kind: 'isolation',
        equipment: 'Ball or band',
        cue: 'Because gracilis crosses the knee too, bending the knee changes its contribution — a useful way to bias it in or out.',
        motion: 'Hip adduction + knee flexion',
      },
      {
        name: 'Straddle / butterfly stretch',
        kind: 'stretch',
        equipment: 'Floor',
        cue: 'Straight legs stretch gracilis most because it crosses both joints.',
        motion: 'Hip abduction with knee extension',
      },
    ],
    synergists: ['l_adductor_longus', 'l_sartorius', 'l_semitendinosus'],
    clinical:
      'The only adductor to cross the knee. Frequently harvested as a tendon graft for ACL reconstruction, with minimal functional cost.',
  },
  // ===================================================================== QUADRICEPS
  {
    id: 'l_rectus_femoris',
    name: 'Rectus femoris',
    latin: 'Musculus rectus femoris',
    side: 'left',
    group: 'Quadriceps femoris',
    region: 'thigh',
    layer: 1,
    girth: 0.019,
    path: [
      p('pelvis', [0.098, 0.976, 0.055]),
      via('l_hip', [0.105, 0.75, 0.042]),
      via('l_knee', [0.101, 0.515, 0.05]),
      p('l_knee', [0.095, 0.44, 0.032]),
    ],
    originDesc: 'Anterior inferior iliac spine (straight head) and the superior acetabular rim (reflected head)',
    insertionDesc: 'Base of the patella, then the tibial tuberosity via the patellar tendon',
    actions: [
      { joint: 'l_knee', motion: 'extension', role: 'prime' },
      { joint: 'l_hip', motion: 'flexion', role: 'prime' },
    ],
    innervation: 'Femoral nerve (L2, L3, L4)',
    nerve: 'l_femoral',
    bloodSupply: 'Lateral circumflex femoral artery',
    palpation: 'The central ridge down the front of the thigh; contracts when you straighten the knee.',
    exercises: [
      {
        name: 'Seated leg extension',
        kind: 'isolation',
        equipment: 'Machine',
        cue: 'Sitting upright (hip flexed) shortens rectus femoris and reduces its contribution; leaning *back* lengthens it at the hip and biases it strongly.',
        motion: 'Knee extension',
      },
      {
        name: 'Reverse Nordic curl',
        kind: 'isolation',
        equipment: 'Bodyweight, pad',
        cue: 'Kneeling, lean back with hips extended. Loads the rectus femoris eccentrically at long length — excellent for sprinters.',
        motion: 'Knee extension (eccentric)',
      },
      {
        name: 'Sissy squat',
        kind: 'isolation',
        equipment: 'Bodyweight or support',
        cue: 'Knees travel forward with the hips extended — maximum quadriceps stretch under load.',
        motion: 'Knee extension',
      },
      {
        name: 'Couch stretch',
        kind: 'stretch',
        equipment: 'Wall or couch',
        cue: 'Knee flexed against the wall with the hip extended stretches it across both joints, which nothing else does.',
        motion: 'Hip extension + knee flexion',
      },
    ],
    antagonists: ['l_biceps_femoris_long', 'l_semitendinosus', 'l_gluteus_maximus'],
    synergists: ['l_vastus_lateralis', 'l_vastus_medialis', 'l_iliacus'],
    clinical:
      'The only quadriceps head crossing the hip, so it is the only one that can be trained differentially by hip position — and the only one at risk in a "kicking" strain of the anterior thigh.',
  },
  {
    id: 'l_vastus_lateralis',
    name: 'Vastus lateralis',
    latin: 'Musculus vastus lateralis',
    side: 'left',
    group: 'Quadriceps femoris',
    region: 'thigh',
    layer: 1,
    girth: 0.023,
    path: [
      p('l_hip', [0.118, 0.9, -0.004]),
      via('l_hip', [0.128, 0.7, 0.02]),
      via('l_knee', [0.112, 0.52, 0.045]),
      p('l_knee', [0.098, 0.442, 0.033]),
    ],
    originDesc: 'Greater trochanter, intertrochanteric line and the lateral lip of the linea aspera',
    insertionDesc: 'Lateral border of the patella and the tibial tuberosity via the patellar tendon',
    actions: [{ joint: 'l_knee', motion: 'extension', role: 'prime' }],
    innervation: 'Femoral nerve (L2, L3, L4)',
    nerve: 'l_femoral',
    bloodSupply: 'Lateral circumflex femoral artery',
    exercises: [
      {
        name: 'Back or front squat',
        kind: 'compound',
        equipment: 'Barbell',
        cue: 'The largest quadriceps head and the main contributor to squat strength. A narrower stance and more upright torso increase knee flexion and therefore its involvement.',
        motion: 'Knee extension',
      },
      {
        name: 'Leg press with feet low on the platform',
        kind: 'compound',
        equipment: 'Leg press',
        cue: 'Feet low and narrow increases knee travel and quadriceps demand.',
        motion: 'Knee extension',
      },
      {
        name: 'Leg extension with the toes turned in',
        kind: 'isolation',
        equipment: 'Machine',
        cue: 'A modest but real shift of emphasis toward the lateral head.',
        motion: 'Knee extension',
      },
    ],
    antagonists: ['l_biceps_femoris_long', 'l_semimembranosus'],
    synergists: ['l_vastus_intermedius', 'l_rectus_femoris'],
    clinical:
      'Its lateral pull is balanced by vastus medialis; an imbalance contributes to lateral patellar tracking and anterior knee pain. It is also the standard site for intramuscular injection in infants.',
  },
  {
    id: 'l_vastus_medialis',
    name: 'Vastus medialis',
    latin: 'Musculus vastus medialis',
    side: 'left',
    group: 'Quadriceps femoris',
    region: 'thigh',
    layer: 1,
    girth: 0.02,
    path: [
      p('l_hip', [0.075, 0.86, -0.004]),
      via('l_hip', [0.075, 0.62, 0.025]),
      via('l_knee', [0.088, 0.52, 0.045]),
      p('l_knee', [0.094, 0.442, 0.033]),
    ],
    originDesc: 'Intertrochanteric line, medial lip of the linea aspera and the medial supracondylar line',
    insertionDesc: 'Medial border of the patella (the oblique fibres, VMO) and the tibial tuberosity',
    actions: [
      { joint: 'l_knee', motion: 'extension', role: 'prime' },
      { joint: 'l_patellofemoral', motion: 'extension', role: 'stabilise' },
    ],
    innervation: 'Femoral nerve (L2, L3, L4)',
    nerve: 'l_femoral',
    bloodSupply: 'Femoral and descending genicular arteries',
    palpation: 'The teardrop above and medial to the knee; most obvious in the last 20° of extension.',
    exercises: [
      {
        name: 'Terminal knee extension (TKE)',
        kind: 'isolation',
        equipment: 'Band anchored in front',
        cue: 'The oblique fibres work hardest in the final 20° of extension — this drill lives entirely in that range.',
        motion: 'Terminal knee extension',
      },
      {
        name: 'Spanish squat',
        kind: 'isolation',
        equipment: 'Heavy band behind the knees',
        cue: 'Isometric quadriceps loading with minimal patellofemoral shear; a mainstay of patellar tendinopathy rehab.',
        motion: 'Knee extension (isometric)',
      },
      {
        name: 'Step-down',
        kind: 'compound',
        equipment: 'Step',
        cue: 'Eccentric single-leg control; watch that the knee does not fall inward.',
        motion: 'Knee extension (eccentric)',
      },
    ],
    antagonists: ['l_biceps_femoris_long'],
    synergists: ['l_vastus_intermedius', 'l_rectus_femoris'],
    clinical:
      'The VMO is often the first quadriceps portion to waste after knee injury or surgery. Whether it can be trained in true isolation is debated, but restoring terminal extension strength is not.',
  },
  {
    id: 'l_vastus_intermedius',
    name: 'Vastus intermedius',
    latin: 'Musculus vastus intermedius',
    side: 'left',
    group: 'Quadriceps femoris',
    region: 'thigh',
    layer: 3,
    girth: 0.017,
    path: [
      p('l_hip', [0.1, 0.83, 0.022]),
      via('l_hip', [0.101, 0.6, 0.035]),
      p('l_knee', [0.098, 0.445, 0.032]),
    ],
    originDesc: 'Anterior and lateral surfaces of the femoral shaft',
    insertionDesc: 'Deep surface of the quadriceps tendon to the patella and tibial tuberosity',
    actions: [{ joint: 'l_knee', motion: 'extension', role: 'prime' }],
    innervation: 'Femoral nerve (L2, L3, L4)',
    nerve: 'l_femoral',
    bloodSupply: 'Lateral circumflex femoral artery',
    exercises: [
      {
        name: 'Leg extension',
        kind: 'isolation',
        equipment: 'Machine',
        cue: 'Lies deep to rectus femoris and cannot be isolated from the other vasti — any knee-extension work loads it.',
        motion: 'Knee extension',
      },
      {
        name: 'Front squat',
        kind: 'compound',
        equipment: 'Barbell',
        cue: 'The upright torso maximises knee flexion and therefore total quadriceps demand.',
        motion: 'Knee extension',
      },
    ],
    synergists: ['l_vastus_lateralis', 'l_vastus_medialis'],
    clinical:
      'Its deep fibres form articularis genu, which pulls the suprapatellar bursa out of the way during extension.',
  },
  // ===================================================================== HAMSTRINGS
  {
    id: 'l_biceps_femoris_long',
    name: 'Biceps femoris — long head',
    latin: 'Musculus biceps femoris, caput longum',
    side: 'left',
    group: 'Hamstrings',
    region: 'thigh',
    layer: 1,
    girth: 0.018,
    path: [
      p('pelvis', [0.076, 0.848, -0.058]),
      via('l_hip', [0.1, 0.7, -0.035]),
      p('l_knee', [0.124, 0.458, -0.004]),
    ],
    originDesc: 'Ischial tuberosity, by a tendon shared with semitendinosus',
    insertionDesc: 'Head of the fibula and the lateral tibial condyle',
    actions: [
      { joint: 'l_knee', motion: 'flexion', role: 'prime' },
      { joint: 'l_hip', motion: 'extension', role: 'prime' },
      { joint: 'l_knee', motion: 'external rotation', role: 'assist' },
    ],
    innervation: 'Tibial division of the sciatic nerve (L5, S1, S2)',
    nerve: 'l_sciatic',
    bloodSupply: 'Perforating branches of the deep femoral artery',
    palpation: 'The lateral hamstring tendon behind the knee, running to the fibular head.',
    exercises: [
      {
        name: 'Nordic hamstring curl',
        kind: 'isolation',
        equipment: 'Partner or anchor',
        cue: 'The single best-evidenced hamstring injury-prevention exercise — roughly halves hamstring strain rates. Lower as slowly as you can control.',
        motion: 'Knee flexion (eccentric)',
      },
      {
        name: 'Romanian deadlift',
        kind: 'compound',
        equipment: 'Barbell',
        cue: 'Loads the hip-extension role at long muscle length; keep the shins vertical and the spine neutral.',
        motion: 'Hip extension',
      },
      {
        name: 'Seated leg curl',
        kind: 'isolation',
        equipment: 'Machine',
        cue: 'The seated position keeps the hip flexed, so the hamstrings are lengthened — measurably better for hypertrophy than the lying curl.',
        motion: 'Knee flexion',
      },
      {
        name: 'Single-leg RDL',
        kind: 'compound',
        equipment: 'Dumbbell or kettlebell',
        cue: 'Adds a frontal-plane control demand; the long head is also a pelvic stabiliser.',
        motion: 'Hip extension',
      },
    ],
    antagonists: ['l_rectus_femoris', 'l_vastus_lateralis', 'l_psoas_major'],
    synergists: ['l_semitendinosus', 'l_semimembranosus', 'l_gluteus_maximus'],
    clinical:
      'The most commonly strained muscle in sport, almost always at the proximal musculotendinous junction of the long head during terminal swing in sprinting, when it is lengthening under high force.',
  },
  {
    id: 'l_biceps_femoris_short',
    name: 'Biceps femoris — short head',
    latin: 'Musculus biceps femoris, caput breve',
    side: 'left',
    group: 'Hamstrings',
    region: 'thigh',
    layer: 2,
    girth: 0.012,
    path: [
      p('l_hip', [0.115, 0.68, -0.02]),
      p('l_knee', [0.126, 0.455, -0.006]),
    ],
    originDesc: 'Lateral lip of the linea aspera and the lateral supracondylar line of the femur',
    insertionDesc: 'Head of the fibula, joining the long head tendon',
    actions: [
      { joint: 'l_knee', motion: 'flexion', role: 'prime' },
      { joint: 'l_knee', motion: 'external rotation', role: 'assist' },
    ],
    innervation: 'Common peroneal division of the sciatic nerve (L5, S1, S2)',
    nerve: 'l_common_peroneal',
    bloodSupply: 'Perforating branches of the deep femoral artery',
    exercises: [
      {
        name: 'Lying (prone) leg curl',
        kind: 'isolation',
        equipment: 'Machine',
        cue: 'With the hip extended the two-joint hamstrings are shortened, so the single-joint short head takes a larger share.',
        motion: 'Knee flexion',
      },
      {
        name: 'Leg curl with the foot externally rotated',
        kind: 'isolation',
        equipment: 'Machine',
        cue: 'Turning the toes out biases the lateral hamstring (biceps femoris) over the medial ones.',
        motion: 'Knee flexion + tibial external rotation',
      },
    ],
    synergists: ['l_biceps_femoris_long'],
    clinical:
      'The only hamstring supplied by the peroneal division of the sciatic nerve — the two heads of one muscle have different nerve supplies, a genuine anatomical oddity.',
  },
  {
    id: 'l_semitendinosus',
    name: 'Semitendinosus',
    latin: 'Musculus semitendinosus',
    side: 'left',
    group: 'Hamstrings',
    region: 'thigh',
    layer: 1,
    girth: 0.014,
    path: [
      p('pelvis', [0.07, 0.845, -0.062]),
      via('l_hip', [0.082, 0.68, -0.038]),
      p('l_knee', [0.076, 0.43, 0.012]),
    ],
    originDesc: 'Ischial tuberosity (common tendon with the long head of biceps femoris)',
    insertionDesc: 'Superomedial tibia at the pes anserinus',
    actions: [
      { joint: 'l_knee', motion: 'flexion', role: 'prime' },
      { joint: 'l_hip', motion: 'extension', role: 'prime' },
      { joint: 'l_knee', motion: 'internal rotation', role: 'assist' },
    ],
    innervation: 'Tibial division of the sciatic nerve (L5, S1, S2)',
    nerve: 'l_sciatic',
    bloodSupply: 'Perforating branches of the deep femoral artery',
    exercises: [
      {
        name: 'Leg curl with the toes turned in',
        kind: 'isolation',
        equipment: 'Machine',
        cue: 'Internal tibial rotation biases the medial hamstrings — semitendinosus and semimembranosus.',
        motion: 'Knee flexion + tibial internal rotation',
      },
      {
        name: 'Glute-ham raise',
        kind: 'compound',
        equipment: 'GHD',
        cue: 'Trains hip extension and knee flexion simultaneously, which is how the hamstrings actually work in running.',
        motion: 'Knee flexion + hip extension',
      },
      {
        name: 'Standing hamstring stretch with the hip flexed',
        kind: 'stretch',
        equipment: 'Step',
        cue: 'Hinge from the hip with a flat back; rounding the spine cheats the stretch.',
        motion: 'Hip flexion with knee extension',
      },
    ],
    antagonists: ['l_rectus_femoris', 'l_vastus_medialis'],
    synergists: ['l_semimembranosus', 'l_biceps_femoris_long', 'l_gracilis'],
    clinical:
      'Its long cord-like tendon is the standard autograft (with gracilis) for ACL reconstruction; the tendon regenerates partially but knee flexion strength at deep angles stays slightly reduced.',
  },
  {
    id: 'l_semimembranosus',
    name: 'Semimembranosus',
    latin: 'Musculus semimembranosus',
    side: 'left',
    group: 'Hamstrings',
    region: 'thigh',
    layer: 2,
    girth: 0.016,
    path: [
      p('pelvis', [0.082, 0.852, -0.055]),
      via('l_hip', [0.078, 0.66, -0.035]),
      p('l_knee', [0.073, 0.462, -0.018]),
    ],
    originDesc: 'Ischial tuberosity, by a flat membranous tendon deep to the other two',
    insertionDesc: 'Posterior aspect of the medial tibial condyle',
    actions: [
      { joint: 'l_knee', motion: 'flexion', role: 'prime' },
      { joint: 'l_hip', motion: 'extension', role: 'prime' },
      { joint: 'l_knee', motion: 'internal rotation', role: 'assist' },
    ],
    innervation: 'Tibial division of the sciatic nerve (L5, S1, S2)',
    nerve: 'l_sciatic',
    bloodSupply: 'Perforating branches of the deep femoral artery',
    exercises: [
      {
        name: 'Romanian deadlift',
        kind: 'compound',
        equipment: 'Barbell',
        cue: 'The strongest hamstring by cross-section; hip-hinge patterns load it best.',
        motion: 'Hip extension',
      },
      {
        name: 'Seated leg curl, toes in',
        kind: 'isolation',
        equipment: 'Machine',
        cue: 'Hip flexed and tibia internally rotated is its most specific position.',
        motion: 'Knee flexion',
      },
      {
        name: '45° hip extension',
        kind: 'compound',
        equipment: 'Roman chair',
        cue: 'Keep the spine neutral and hinge purely at the hip so the hamstrings, not the erectors, do the work.',
        motion: 'Hip extension',
      },
    ],
    synergists: ['l_semitendinosus', 'l_gluteus_maximus'],
    clinical:
      'A Baker\'s cyst usually arises from the semimembranosus–gastrocnemius bursa. Its expansion into the posterior capsule also helps stabilise the medial knee.',
  },
  {
    id: 'l_popliteus',
    name: 'Popliteus',
    latin: 'Musculus popliteus',
    side: 'left',
    group: 'Posterior leg',
    region: 'leg',
    layer: 3,
    girth: 0.009,
    path: [
      p('l_hip', [0.124, 0.492, -0.012]),
      p('l_knee', [0.086, 0.44, -0.02]),
    ],
    originDesc: 'Lateral femoral condyle and the lateral meniscus',
    insertionDesc: 'Posterior surface of the proximal tibia above the soleal line',
    actions: [
      { joint: 'l_knee', motion: 'flexion', role: 'assist' },
      { joint: 'l_knee', motion: 'internal rotation', role: 'prime' },
    ],
    innervation: 'Tibial nerve (L4, L5, S1)',
    nerve: 'l_tibial',
    bloodSupply: 'Popliteal artery (genicular branches)',
    exercises: [
      {
        name: 'Seated resisted tibial internal rotation',
        kind: 'isolation',
        equipment: 'Band around the foot',
        cue: 'Knee bent to 90°, turn the shin inward against the band. The only way to load popliteus directly.',
        motion: 'Tibial internal rotation',
      },
      {
        name: 'Controlled knee unlocking from full extension',
        kind: 'activation',
        equipment: 'Bodyweight',
        cue: 'Popliteus is the "key" that unlocks the screw-home mechanism to start flexion from full extension.',
        motion: 'Knee unlocking',
      },
    ],
    clinical:
      'Also pulls the lateral meniscus posteriorly during flexion, preventing it from being trapped. Part of the posterolateral corner, which is injured with hyperextension and varus force.',
  },
  // ============================================================== POSTERIOR LEG (CALF)
  {
    id: 'l_gastrocnemius_medial',
    name: 'Gastrocnemius — medial head',
    latin: 'Musculus gastrocnemius, caput mediale',
    side: 'left',
    group: 'Triceps surae',
    region: 'leg',
    layer: 1,
    girth: 0.018,
    path: [
      p('l_hip', [0.079, 0.498, -0.018]),
      via('l_knee', [0.086, 0.35, -0.036]),
      p('l_ankle', [0.1, 0.028, -0.052]),
    ],
    originDesc: 'Posterior surface of the medial femoral condyle',
    insertionDesc: 'Posterior calcaneus via the calcaneal (Achilles) tendon',
    actions: [
      { joint: 'l_ankle', motion: 'plantarflexion', role: 'prime' },
      { joint: 'l_knee', motion: 'flexion', role: 'assist' },
      { joint: 'l_subtalar', motion: 'inversion', role: 'assist' },
    ],
    innervation: 'Tibial nerve (S1, S2)',
    nerve: 'l_tibial',
    bloodSupply: 'Sural arteries',
    fiberType: 'Predominantly fast-twitch — built for propulsion',
    palpation: 'The upper, medial bulge of the calf; most obvious on tiptoe with the knee straight.',
    exercises: [
      {
        name: 'Standing calf raise',
        kind: 'isolation',
        equipment: 'Machine, step or bodyweight',
        cue: 'The knee must be straight. Gastrocnemius crosses the knee, so with the knee bent it goes slack and the soleus does the work instead.',
        motion: 'Ankle plantarflexion',
      },
      {
        name: 'Single-leg calf raise off a step',
        kind: 'isolation',
        equipment: 'Step',
        cue: 'Full range — drop the heel below the step and rise to the top. Aim for 25+ single-leg reps as a functional benchmark.',
        motion: 'Ankle plantarflexion',
      },
      {
        name: 'Straight-leg calf stretch against a wall',
        kind: 'stretch',
        equipment: 'Wall',
        cue: 'Back leg straight, heel down. Bending the knee shifts the stretch to soleus.',
        motion: 'Ankle dorsiflexion',
      },
      {
        name: 'Skipping / pogo hops',
        kind: 'activation',
        equipment: 'Rope or none',
        cue: 'Trains the elastic, stretch-shortening role the gastrocnemius actually plays in running.',
        motion: 'Rapid plantarflexion',
      },
    ],
    antagonists: ['l_tibialis_anterior'],
    synergists: ['l_gastrocnemius_lateral', 'l_soleus'],
    clinical:
      '"Tennis leg" is a tear at the medial gastrocnemius musculotendinous junction, felt as a sudden blow to the calf during push-off.',
  },
  {
    id: 'l_gastrocnemius_lateral',
    name: 'Gastrocnemius — lateral head',
    latin: 'Musculus gastrocnemius, caput laterale',
    side: 'left',
    group: 'Triceps surae',
    region: 'leg',
    layer: 1,
    girth: 0.016,
    path: [
      p('l_hip', [0.124, 0.498, -0.018]),
      via('l_knee', [0.114, 0.35, -0.036]),
      p('l_ankle', [0.101, 0.028, -0.054]),
    ],
    originDesc: 'Posterior surface of the lateral femoral condyle',
    insertionDesc: 'Posterior calcaneus via the Achilles tendon',
    actions: [
      { joint: 'l_ankle', motion: 'plantarflexion', role: 'prime' },
      { joint: 'l_knee', motion: 'flexion', role: 'assist' },
    ],
    innervation: 'Tibial nerve (S1, S2)',
    nerve: 'l_tibial',
    bloodSupply: 'Sural arteries',
    exercises: [
      {
        name: 'Standing calf raise with the toes turned in',
        kind: 'isolation',
        equipment: 'Step or machine',
        cue: 'Slight internal foot rotation is commonly used to bias the lateral head; the effect is modest but real.',
        motion: 'Ankle plantarflexion',
      },
      {
        name: 'Donkey calf raise',
        kind: 'isolation',
        equipment: 'Machine or partner',
        cue: 'Hip flexion stretches the gastrocnemius across the knee for a longer working range.',
        motion: 'Ankle plantarflexion',
      },
    ],
    synergists: ['l_gastrocnemius_medial', 'l_soleus'],
    clinical:
      'A fabella (sesamoid) sits in its tendon in about 20% of people and can be mistaken for a loose body on X-ray.',
  },
  {
    id: 'l_soleus',
    name: 'Soleus',
    latin: 'Musculus soleus',
    side: 'left',
    group: 'Triceps surae',
    region: 'leg',
    layer: 2,
    girth: 0.02,
    path: [
      p('l_knee', [0.104, 0.42, -0.02]),
      via('l_knee', [0.102, 0.25, -0.033]),
      p('l_ankle', [0.1, 0.03, -0.05]),
    ],
    originDesc: 'Soleal line of the tibia, posterior head and proximal shaft of the fibula',
    insertionDesc: 'Posterior calcaneus via the Achilles tendon',
    actions: [
      { joint: 'l_ankle', motion: 'plantarflexion', role: 'prime' },
      { joint: 'l_subtalar', motion: 'inversion', role: 'assist' },
    ],
    innervation: 'Tibial nerve (S1, S2)',
    nerve: 'l_tibial',
    bloodSupply: 'Posterior tibial and peroneal arteries',
    fiberType: 'Predominantly slow-twitch — an endurance postural muscle',
    exercises: [
      {
        name: 'Seated calf raise',
        kind: 'isolation',
        equipment: 'Machine or a plate on the knee',
        cue: 'The definitive soleus isolator. Bending the knee to 90° makes the gastrocnemius insufficient, leaving the soleus to do everything.',
        motion: 'Ankle plantarflexion with the knee bent',
      },
      {
        name: 'Bent-knee wall calf stretch',
        kind: 'stretch',
        equipment: 'Wall',
        cue: 'Back knee bent, heel down. Restores the ankle dorsiflexion needed for a deep squat.',
        motion: 'Ankle dorsiflexion',
      },
      {
        name: 'Soleus wall sit / slow seated raises',
        kind: 'activation',
        equipment: 'Bodyweight',
        cue: 'Long duration, low load — matches its slow-twitch, postural profile.',
        motion: 'Plantarflexion (isometric)',
      },
    ],
    antagonists: ['l_tibialis_anterior'],
    synergists: ['l_gastrocnemius_medial', 'l_tibialis_posterior'],
    clinical:
      'Known as the "second heart": its contractions pump venous blood back up the leg. Immobility removes that pump, which is part of why long-haul flights raise DVT risk.',
  },
  {
    id: 'l_plantaris',
    name: 'Plantaris',
    latin: 'Musculus plantaris',
    side: 'left',
    group: 'Triceps surae',
    region: 'leg',
    layer: 3,
    girth: 0.006,
    path: [
      p('l_hip', [0.12, 0.505, -0.02]),
      via('l_knee', [0.105, 0.36, -0.03]),
      p('l_ankle', [0.096, 0.032, -0.05]),
    ],
    originDesc: 'Lateral supracondylar line of the femur',
    insertionDesc: 'Posterior calcaneus, medial to the Achilles tendon',
    actions: [
      { joint: 'l_ankle', motion: 'plantarflexion', role: 'assist' },
      { joint: 'l_knee', motion: 'flexion', role: 'assist' },
    ],
    innervation: 'Tibial nerve (S1, S2)',
    nerve: 'l_tibial',
    bloodSupply: 'Sural arteries',
    exercises: [
      {
        name: 'Calf raise',
        kind: 'compound',
        equipment: 'Step',
        cue: 'Works with the triceps surae; it cannot be isolated and contributes little force.',
        motion: 'Ankle plantarflexion',
      },
    ],
    synergists: ['l_gastrocnemius_lateral'],
    clinical:
      'Absent in 7–20% of people. A tiny belly with a very long tendon, extremely rich in proprioceptors — it may be more a sensory organ than a mover, and is a favourite tendon graft.',
  },
  // =============================================================== ANTERIOR LEG
  {
    id: 'l_tibialis_anterior',
    name: 'Tibialis anterior',
    latin: 'Musculus tibialis anterior',
    side: 'left',
    group: 'Anterior compartment',
    region: 'leg',
    layer: 1,
    girth: 0.013,
    path: [
      p('l_knee', [0.112, 0.44, 0.022]),
      via('l_knee', [0.106, 0.25, 0.028]),
      via('l_ankle', [0.096, 0.09, 0.02]),
      p('l_ankle', [0.076, 0.045, 0.052]),
    ],
    originDesc: 'Lateral condyle and proximal half of the lateral tibial surface, and the interosseous membrane',
    insertionDesc: 'Medial cuneiform and the base of the 1st metatarsal',
    actions: [
      { joint: 'l_ankle', motion: 'dorsiflexion', role: 'prime' },
      { joint: 'l_subtalar', motion: 'inversion', role: 'prime' },
    ],
    innervation: 'Deep peroneal (fibular) nerve (L4, L5)',
    nerve: 'l_deep_peroneal',
    bloodSupply: 'Anterior tibial artery',
    palpation: 'The strap just lateral to the shin bone; its tendon stands out at the front of the ankle on dorsiflexion.',
    exercises: [
      {
        name: 'Tibialis raise (toe raise against a wall)',
        kind: 'isolation',
        equipment: 'Wall, or a tib bar',
        cue: 'Heels a foot from the wall, back against it, lift the toes as high as possible. Simple, effective, and almost universally neglected.',
        motion: 'Ankle dorsiflexion',
      },
      {
        name: 'Banded dorsiflexion',
        kind: 'isolation',
        equipment: 'Band',
        cue: 'Anchor the band on the forefoot and pull the foot up and slightly inward to match its true line of pull.',
        motion: 'Dorsiflexion + inversion',
      },
      {
        name: 'Heel walking',
        kind: 'activation',
        equipment: 'None',
        cue: 'Walk 20–30 m on the heels; also the quick clinical screen for an L4/L5 lesion.',
        motion: 'Sustained dorsiflexion',
      },
    ],
    antagonists: ['l_gastrocnemius_medial', 'l_soleus', 'l_peroneus_longus'],
    synergists: ['l_extensor_digitorum_longus', 'l_tibialis_posterior'],
    clinical:
      'Weakness causes foot drop and a steppage gait. It is also the muscle most implicated in anterior shin splints and in anterior compartment syndrome.',
  },
  {
    id: 'l_extensor_digitorum_longus',
    name: 'Extensor digitorum longus',
    latin: 'Musculus extensor digitorum longus',
    side: 'left',
    group: 'Anterior compartment',
    region: 'leg',
    layer: 2,
    girth: 0.01,
    path: [
      p('l_knee', [0.12, 0.44, 0.012]),
      via('l_knee', [0.114, 0.22, 0.02]),
      via('l_ankle', [0.106, 0.085, 0.02]),
      p('l_forefoot', [0.105, 0.03, 0.155]),
    ],
    originDesc: 'Lateral tibial condyle, anterior fibula and the interosseous membrane',
    insertionDesc: 'Middle and distal phalanges of the lateral four toes',
    actions: [
      { joint: 'l_mtp', motion: 'extension', role: 'prime' },
      { joint: 'l_ankle', motion: 'dorsiflexion', role: 'assist' },
      { joint: 'l_subtalar', motion: 'eversion', role: 'assist' },
    ],
    innervation: 'Deep peroneal (fibular) nerve (L5, S1)',
    nerve: 'l_deep_peroneal',
    bloodSupply: 'Anterior tibial artery',
    exercises: [
      {
        name: 'Toe extension against a band',
        kind: 'isolation',
        equipment: 'Band or towel',
        cue: 'Lift the toes while keeping the ankle still — harder than it sounds and useful for hammertoe prevention.',
        motion: 'Toe extension',
      },
      {
        name: 'Toe-spread-and-lift drill',
        kind: 'activation',
        equipment: 'None',
        cue: 'Lift all toes, then lower them one at a time from the little toe inward.',
        motion: 'Toe extension',
      },
    ],
    antagonists: ['l_flexor_digitorum_longus_leg'],
    synergists: ['l_tibialis_anterior'],
  },
  {
    id: 'l_extensor_hallucis_longus',
    name: 'Extensor hallucis longus',
    latin: 'Musculus extensor hallucis longus',
    side: 'left',
    group: 'Anterior compartment',
    region: 'leg',
    layer: 3,
    girth: 0.008,
    path: [
      p('l_knee', [0.114, 0.3, 0.01]),
      via('l_ankle', [0.1, 0.085, 0.022]),
      p('l_forefoot', [0.078, 0.028, 0.16]),
    ],
    originDesc: 'Middle anterior surface of the fibula and the interosseous membrane',
    insertionDesc: 'Base of the distal phalanx of the great toe',
    actions: [
      { joint: 'l_mtp', motion: 'extension', role: 'prime' },
      { joint: 'l_ankle', motion: 'dorsiflexion', role: 'assist' },
      { joint: 'l_subtalar', motion: 'inversion', role: 'assist' },
    ],
    innervation: 'Deep peroneal (fibular) nerve (L5, S1)',
    nerve: 'l_deep_peroneal',
    bloodSupply: 'Anterior tibial artery',
    exercises: [
      {
        name: 'Big-toe extension isolation',
        kind: 'isolation',
        equipment: 'None',
        cue: 'Press the lesser toes down and lift only the big toe. Difficult at first — it is a genuine motor-control skill.',
        motion: 'Hallux extension',
      },
    ],
    antagonists: ['l_flexor_hallucis_longus'],
    clinical:
      'Weak great-toe extension is the most sensitive single motor sign of an L5 radiculopathy.',
  },
  // =============================================================== LATERAL LEG
  {
    id: 'l_peroneus_longus',
    name: 'Peroneus (fibularis) longus',
    latin: 'Musculus fibularis longus',
    side: 'left',
    group: 'Lateral compartment',
    region: 'leg',
    layer: 1,
    girth: 0.011,
    path: [
      p('l_knee', [0.126, 0.45, -0.004]),
      via('l_knee', [0.127, 0.25, -0.006]),
      via('l_ankle', [0.124, 0.062, -0.018]),
      via('l_ankle', [0.118, 0.024, 0.045]),
      p('l_ankle', [0.078, 0.026, 0.055]),
    ],
    originDesc: 'Head and proximal two-thirds of the lateral fibula',
    insertionDesc: 'Base of the 1st metatarsal and medial cuneiform — crossing the sole of the foot',
    actions: [
      { joint: 'l_subtalar', motion: 'eversion', role: 'prime' },
      { joint: 'l_ankle', motion: 'plantarflexion', role: 'assist' },
    ],
    innervation: 'Superficial peroneal (fibular) nerve (L5, S1, S2)',
    nerve: 'l_superficial_peroneal',
    bloodSupply: 'Peroneal artery',
    exercises: [
      {
        name: 'Banded eversion',
        kind: 'isolation',
        equipment: 'Band',
        cue: 'Anchor the band medially and turn the sole outward, keeping the knee still so the hip does not rotate instead.',
        motion: 'Foot eversion',
      },
      {
        name: 'Single-leg balance on an unstable surface',
        kind: 'activation',
        equipment: 'Balance pad',
        cue: 'The peroneals are the primary dynamic defence against an inversion sprain; reaction time matters more than strength.',
        motion: 'Lateral ankle stabilisation',
      },
      {
        name: 'Big-toe press-down (1st ray loading)',
        kind: 'activation',
        equipment: 'None',
        cue: 'Its insertion under the 1st metatarsal is what presses the big toe into the ground at push-off and maintains the transverse arch.',
        motion: 'First-ray plantarflexion',
      },
    ],
    antagonists: ['l_tibialis_posterior', 'l_tibialis_anterior'],
    synergists: ['l_peroneus_brevis'],
    clinical:
      'Its tendon and that of tibialis posterior form a stirrup under the foot supporting both arches. The common peroneal nerve winds around the fibular neck just above it and is easily compressed there.',
  },
  {
    id: 'l_peroneus_brevis',
    name: 'Peroneus (fibularis) brevis',
    latin: 'Musculus fibularis brevis',
    side: 'left',
    group: 'Lateral compartment',
    region: 'leg',
    layer: 2,
    girth: 0.009,
    path: [
      p('l_knee', [0.124, 0.22, -0.008]),
      via('l_ankle', [0.124, 0.062, -0.016]),
      p('l_ankle', [0.128, 0.042, 0.05]),
    ],
    originDesc: 'Distal two-thirds of the lateral surface of the fibula',
    insertionDesc: 'Tuberosity at the base of the 5th metatarsal',
    actions: [
      { joint: 'l_subtalar', motion: 'eversion', role: 'prime' },
      { joint: 'l_ankle', motion: 'plantarflexion', role: 'assist' },
    ],
    innervation: 'Superficial peroneal (fibular) nerve (L5, S1)',
    nerve: 'l_superficial_peroneal',
    bloodSupply: 'Peroneal artery',
    exercises: [
      {
        name: 'Banded eversion, foot plantarflexed',
        kind: 'isolation',
        equipment: 'Band',
        cue: 'The strongest evertor of the two; loading in slight plantarflexion mirrors the sprain position.',
        motion: 'Foot eversion',
      },
      {
        name: 'Lateral hops',
        kind: 'activation',
        equipment: 'None',
        cue: 'Late-stage ankle-sprain rehab; trains the reactive eversion response.',
        motion: 'Reactive eversion',
      },
    ],
    synergists: ['l_peroneus_longus'],
    clinical:
      'Its pull avulses the 5th metatarsal base in a forced inversion injury — the fracture that mimics a "simple sprain".',
  },
  // =============================================================== DEEP POSTERIOR LEG
  {
    id: 'l_tibialis_posterior',
    name: 'Tibialis posterior',
    latin: 'Musculus tibialis posterior',
    side: 'left',
    group: 'Deep posterior compartment',
    region: 'leg',
    layer: 3,
    girth: 0.011,
    path: [
      p('l_knee', [0.105, 0.35, -0.022]),
      via('l_ankle', [0.08, 0.06, -0.012]),
      p('l_ankle', [0.077, 0.045, 0.045]),
    ],
    originDesc: 'Interosseous membrane and the adjacent posterior tibia and fibula',
    insertionDesc: 'Navicular tuberosity, with slips to the cuneiforms, cuboid and metatarsal bases 2–4',
    actions: [
      { joint: 'l_subtalar', motion: 'inversion', role: 'prime' },
      { joint: 'l_ankle', motion: 'plantarflexion', role: 'assist' },
    ],
    innervation: 'Tibial nerve (L4, L5)',
    nerve: 'l_tibial',
    bloodSupply: 'Posterior tibial and peroneal arteries',
    exercises: [
      {
        name: 'Banded inversion',
        kind: 'isolation',
        equipment: 'Band',
        cue: 'Anchor laterally, turn the sole inward and slightly down. Keep the knee still.',
        motion: 'Foot inversion',
      },
      {
        name: 'Heel raise with the heel turned inward',
        kind: 'isolation',
        equipment: 'Step',
        cue: 'Rise onto the toes while keeping the heel inverted — the standard loading for posterior tibial tendon dysfunction.',
        motion: 'Plantarflexion + inversion',
      },
      {
        name: 'Short-foot (arch doming) exercise',
        kind: 'activation',
        equipment: 'None',
        cue: 'Draw the ball of the foot toward the heel without curling the toes, raising the medial arch.',
        motion: 'Arch support',
      },
    ],
    antagonists: ['l_peroneus_longus', 'l_peroneus_brevis'],
    synergists: ['l_soleus', 'l_flexor_digitorum_longus_leg'],
    clinical:
      'The chief dynamic supporter of the medial longitudinal arch. Posterior tibial tendon dysfunction is the commonest cause of acquired flatfoot in adults, shown by a "too many toes" sign and an inability to do a single-leg heel raise.',
  },
  {
    id: 'l_flexor_digitorum_longus_leg',
    name: 'Flexor digitorum longus',
    latin: 'Musculus flexor digitorum longus',
    side: 'left',
    group: 'Deep posterior compartment',
    region: 'leg',
    layer: 3,
    girth: 0.009,
    path: [
      p('l_knee', [0.095, 0.32, -0.028]),
      via('l_ankle', [0.079, 0.058, -0.016]),
      via('l_ankle', [0.09, 0.018, 0.04]),
      p('l_forefoot', [0.105, 0.015, 0.16]),
    ],
    originDesc: 'Posterior surface of the tibia below the soleal line',
    insertionDesc: 'Plantar bases of the distal phalanges of the lateral four toes',
    actions: [
      { joint: 'l_mtp', motion: 'flexion', role: 'prime' },
      { joint: 'l_ankle', motion: 'plantarflexion', role: 'assist' },
      { joint: 'l_subtalar', motion: 'inversion', role: 'assist' },
    ],
    innervation: 'Tibial nerve (S2, S3)',
    nerve: 'l_tibial',
    bloodSupply: 'Posterior tibial artery',
    exercises: [
      {
        name: 'Towel scrunch',
        kind: 'isolation',
        equipment: 'Towel',
        cue: 'Drag a towel toward you using only the toes. Old-fashioned but effective.',
        motion: 'Toe flexion',
      },
      {
        name: 'Toe curls against a band',
        kind: 'isolation',
        equipment: 'Band',
        cue: 'Resisted flexion of the lesser toes; pair with tibialis posterior work for arch support.',
        motion: 'Toe flexion',
      },
    ],
    antagonists: ['l_extensor_digitorum_longus'],
    synergists: ['l_tibialis_posterior', 'l_flexor_hallucis_longus'],
  },
  {
    id: 'l_flexor_hallucis_longus',
    name: 'Flexor hallucis longus',
    latin: 'Musculus flexor hallucis longus',
    side: 'left',
    group: 'Deep posterior compartment',
    region: 'leg',
    layer: 3,
    girth: 0.01,
    path: [
      p('l_knee', [0.115, 0.28, -0.03]),
      via('l_ankle', [0.092, 0.045, -0.03]),
      via('l_ankle', [0.09, 0.015, 0.05]),
      p('l_forefoot', [0.078, 0.014, 0.16]),
    ],
    originDesc: 'Distal two-thirds of the posterior fibula and the interosseous membrane',
    insertionDesc: 'Plantar base of the distal phalanx of the great toe',
    actions: [
      { joint: 'l_mtp', motion: 'flexion', role: 'prime' },
      { joint: 'l_ankle', motion: 'plantarflexion', role: 'assist' },
      { joint: 'l_subtalar', motion: 'inversion', role: 'assist' },
    ],
    innervation: 'Tibial nerve (S2, S3)',
    nerve: 'l_tibial',
    bloodSupply: 'Peroneal artery',
    exercises: [
      {
        name: 'Big-toe press into the floor',
        kind: 'isolation',
        equipment: 'None',
        cue: 'Standing, press the big toe down without curling the lesser toes or lifting the arch. Essential for push-off power.',
        motion: 'Hallux flexion',
      },
      {
        name: 'Single-leg calf raise with a big-toe focus',
        kind: 'compound',
        equipment: 'Step',
        cue: 'Rise all the way onto the big toe; FHL provides the final propulsive push in gait.',
        motion: 'Plantarflexion + hallux flexion',
      },
    ],
    antagonists: ['l_extensor_hallucis_longus'],
    clinical:
      'Runs in a groove behind the talus, where it is compressed in posterior ankle impingement — a classic dancer\'s complaint ("dancer\'s tendinitis") from repeated full pointe.',
  },
  {
    id: 'l_foot_intrinsics',
    name: 'Intrinsic foot muscles (abductor hallucis, flexor digitorum brevis, quadratus plantae, interossei)',
    latin: 'Musculi plantae pedis',
    side: 'left',
    group: 'Foot intrinsics',
    region: 'foot',
    layer: 2,
    girth: 0.01,
    path: [
      p('l_ankle', [0.098, 0.02, -0.045]),
      via('l_ankle', [0.095, 0.014, 0.05]),
      p('l_forefoot', [0.1, 0.012, 0.15]),
    ],
    originDesc: 'Calcaneal tuberosity, plantar aponeurosis and the metatarsal shafts',
    insertionDesc: 'Proximal and middle phalanges of the toes',
    actions: [
      { joint: 'l_mtp', motion: 'flexion', role: 'prime' },
      { joint: 'l_mtp', motion: 'abduction', role: 'assist' },
      { joint: 'l_midfoot', motion: 'inversion', role: 'stabilise' },
    ],
    innervation: 'Medial and lateral plantar branches of the tibial nerve (S1–S3)',
    nerve: 'l_tibial',
    bloodSupply: 'Medial and lateral plantar arteries',
    exercises: [
      {
        name: 'Short-foot exercise',
        kind: 'activation',
        equipment: 'None',
        cue: 'Draw the ball of the foot toward the heel to raise the arch, without curling the toes or lifting them. The core exercise for the "foot core".',
        motion: 'Arch doming',
      },
      {
        name: 'Toe yoga (spread and lift)',
        kind: 'activation',
        equipment: 'None',
        cue: 'Lift the big toe while keeping the others down, then reverse. Restores independent toe control.',
        motion: 'Toe abduction and control',
      },
      {
        name: 'Barefoot balance work',
        kind: 'activation',
        equipment: 'None',
        cue: 'Single-leg stance barefoot on a firm surface loads the intrinsics in their true stabilising role.',
        motion: 'Foot stabilisation',
      },
    ],
    synergists: ['l_tibialis_posterior', 'l_flexor_digitorum_longus_leg'],
    clinical:
      'Weakness of the intrinsics is associated with plantar fasciitis, arch collapse and hammertoes. They work alongside the plantar fascia as the foot\'s local stabiliser system.',
  },
];
