/**
 * Muscles of the shoulder girdle, arm, forearm and hand, plus the anterior chest wall.
 * Left side only — `bilateral()` mirrors them.
 */

import { p, via } from './muscleHelpers';
import type { MuscleDef } from './types';

export const UPPER_MUSCLES: MuscleDef[] = [
  // =============================================================== SHOULDER: deltoid
  {
    id: 'l_deltoid_anterior',
    name: 'Deltoid — anterior head',
    latin: 'Musculus deltoideus, pars clavicularis',
    side: 'left',
    group: 'Deltoid',
    region: 'shoulder',
    layer: 1,
    girth: 0.023,
    path: [
      p('l_clavicle', [0.128, 1.398, 0.014]),
      via('l_shoulder', [0.198, 1.335, 0.03]),
      p('l_shoulder', [0.199, 1.24, 0.008]),
    ],
    originDesc: 'Anterior border of the lateral third of the clavicle',
    insertionDesc: 'Deltoid tuberosity on the lateral surface of the humeral shaft',
    actions: [
      { joint: 'l_glenohumeral', motion: 'flexion', role: 'prime' },
      { joint: 'l_glenohumeral', motion: 'internal rotation', role: 'assist' },
      { joint: 'l_glenohumeral', motion: 'abduction', role: 'assist' },
    ],
    innervation: 'Axillary nerve (C5, C6)',
    nerve: 'l_axillary',
    bloodSupply: 'Posterior circumflex humeral artery',
    fiberType: 'Multipennate — built for force, not excursion',
    palpation: 'Front of the shoulder, just lateral to the clavicle; hardens when you raise the arm forwards.',
    exercises: [
      {
        name: 'Front raise',
        kind: 'isolation',
        equipment: 'Dumbbells or cable',
        cue: 'Raise to shoulder height with a neutral or slightly pronated grip and no torso swing. Stopping at 90° keeps the load on the deltoid rather than handing it to the scapular upward rotators.',
        motion: 'Shoulder flexion',
      },
      {
        name: 'Seated dumbbell press',
        kind: 'compound',
        equipment: 'Dumbbells and bench',
        cue: 'A slight incline and elbows drifting ~30° forward of the frontal plane bias the anterior head over the middle head.',
        motion: 'Shoulder flexion + abduction',
      },
      {
        name: 'Cable front raise, arm across the body',
        kind: 'isolation',
        equipment: 'Low cable',
        cue: 'Start with the hand at the opposite hip so the anterior head begins from a lengthened position — more tension where it is weakest.',
        motion: 'Shoulder flexion with adduction',
      },
      {
        name: 'Doorway pec/anterior-deltoid stretch',
        kind: 'stretch',
        equipment: 'Doorframe',
        cue: 'Forearm on the frame at shoulder height, step through and rotate away. Hold 30 s.',
        motion: 'Shoulder extension',
      },
    ],
    antagonists: ['l_deltoid_posterior', 'l_lat_dorsi'],
    synergists: ['l_pec_major_clavicular', 'l_biceps_short'],
    clinical:
      'Preferentially loaded by pressing and bench work, so it is usually strong relative to the posterior head — an imbalance that pulls the humeral head forward.',
  },
  {
    id: 'l_deltoid_middle',
    name: 'Deltoid — middle (acromial) head',
    latin: 'Musculus deltoideus, pars acromialis',
    side: 'left',
    group: 'Deltoid',
    region: 'shoulder',
    layer: 1,
    girth: 0.025,
    path: [
      p('l_scapula', [0.166, 1.404, -0.02]),
      via('l_shoulder', [0.216, 1.32, -0.004]),
      p('l_shoulder', [0.204, 1.236, 0.0]),
    ],
    originDesc: 'Lateral border of the acromion',
    insertionDesc: 'Deltoid tuberosity of the humerus',
    actions: [
      { joint: 'l_glenohumeral', motion: 'abduction', role: 'prime' },
    ],
    innervation: 'Axillary nerve (C5, C6)',
    nerve: 'l_axillary',
    bloodSupply: 'Posterior circumflex humeral artery',
    fiberType: 'Multipennate, the strongest of the three heads',
    palpation: 'The cap of the shoulder directly below the acromion.',
    exercises: [
      {
        name: 'Lateral raise',
        kind: 'isolation',
        equipment: 'Dumbbells or cable',
        cue: 'The single best isolator. Lead with the elbow, keep the thumb no higher than the little finger, and stop at shoulder height — beyond that the scapular upward rotators take over.',
        motion: 'Shoulder abduction',
      },
      {
        name: 'Cable lateral raise (behind the body)',
        kind: 'isolation',
        equipment: 'Low cable',
        cue: 'Standing side-on to the stack keeps tension at the bottom of the range, which a dumbbell cannot do because gravity gives no resistance there.',
        motion: 'Shoulder abduction',
      },
      {
        name: 'Upright row to sternum height',
        kind: 'compound',
        equipment: 'Barbell / EZ bar',
        cue: 'Wide grip, stop at the sternum. Going higher with internal rotation narrows the subacromial space.',
        motion: 'Shoulder abduction + elbow flexion',
      },
      {
        name: 'Overhead press',
        kind: 'compound',
        equipment: 'Barbell or dumbbells',
        cue: 'Recruits all three heads plus serratus and triceps; use it for strength, not for isolation.',
        motion: 'Shoulder abduction + flexion',
      },
    ],
    antagonists: ['l_lat_dorsi', 'l_pec_major_sternal', 'l_teres_major'],
    synergists: ['l_supraspinatus', 'l_trapezius_upper'],
    clinical:
      'Because it is multipennate its fibres pull at an angle to the line of the muscle, producing high force over a short range — hence heavy lateral raises rarely need a long range to work.',
  },
  {
    id: 'l_deltoid_posterior',
    name: 'Deltoid — posterior (spinal) head',
    latin: 'Musculus deltoideus, pars spinalis',
    side: 'left',
    group: 'Deltoid',
    region: 'shoulder',
    layer: 1,
    girth: 0.022,
    path: [
      p('l_scapula', [0.102, 1.374, -0.066]),
      via('l_shoulder', [0.204, 1.312, -0.032]),
      p('l_shoulder', [0.2, 1.242, -0.006]),
    ],
    originDesc: 'Inferior lip of the posterior border of the spine of the scapula',
    insertionDesc: 'Deltoid tuberosity of the humerus',
    actions: [
      { joint: 'l_glenohumeral', motion: 'extension', role: 'prime' },
      { joint: 'l_glenohumeral', motion: 'external rotation', role: 'assist' },
      { joint: 'l_glenohumeral', motion: 'abduction', role: 'assist' },
    ],
    innervation: 'Axillary nerve (C5, C6)',
    nerve: 'l_axillary',
    bloodSupply: 'Posterior circumflex humeral artery',
    palpation: 'Behind the shoulder below the scapular spine; contracts when you pull the elbow backwards.',
    exercises: [
      {
        name: 'Reverse (rear-delt) fly',
        kind: 'isolation',
        equipment: 'Dumbbells, pec-deck or cables',
        cue: 'Chest supported, thumbs down, and lead with the elbows *wide* rather than squeezing the shoulder blades — squeezing shifts the work to the rhomboids and mid-trapezius.',
        motion: 'Shoulder horizontal abduction',
      },
      {
        name: 'Face pull',
        kind: 'compound',
        equipment: 'Rope on a high cable',
        cue: 'Pull the rope to the forehead and finish with external rotation; hits the posterior head with the rotator cuff.',
        motion: 'Horizontal abduction + external rotation',
      },
      {
        name: 'Single-arm bent-over cable row, wide elbow',
        kind: 'isolation',
        equipment: 'Cable',
        cue: 'Elbow flared to 90° keeps the pull in the transverse plane, biasing the posterior deltoid over the latissimus.',
        motion: 'Shoulder horizontal abduction',
      },
    ],
    antagonists: ['l_deltoid_anterior', 'l_pec_major_clavicular'],
    synergists: ['l_infraspinatus', 'l_teres_minor', 'l_trapezius_middle'],
    clinical:
      'Commonly underdeveloped relative to the anterior head. Strengthening it, together with the external rotators, is a mainstay of shoulder impingement rehabilitation.',
  },
  // ============================================================ ROTATOR CUFF (SITS)
  {
    id: 'l_supraspinatus',
    name: 'Supraspinatus',
    latin: 'Musculus supraspinatus',
    side: 'left',
    group: 'Rotator cuff',
    region: 'shoulder',
    layer: 3,
    girth: 0.015,
    path: [
      p('l_scapula', [0.07, 1.386, -0.058]),
      via('l_scapula', [0.14, 1.4, -0.03]),
      p('l_shoulder', [0.185, 1.396, -0.006]),
    ],
    originDesc: 'Supraspinous fossa of the scapula',
    insertionDesc: 'Superior facet of the greater tubercle of the humerus',
    actions: [
      { joint: 'l_glenohumeral', motion: 'abduction', role: 'prime' },
      { joint: 'l_glenohumeral', motion: 'external rotation', role: 'assist' },
      { joint: 'l_glenohumeral', motion: 'flexion', role: 'stabilise' },
    ],
    innervation: 'Suprascapular nerve (C5, C6)',
    nerve: 'l_suprascapular',
    bloodSupply: 'Suprascapular artery',
    palpation: 'Deep to trapezius above the scapular spine — palpable only indirectly.',
    exercises: [
      {
        name: 'Prone "Y" raise',
        kind: 'activation',
        equipment: 'Bodyweight or 1–2 kg plates',
        cue: 'Face down on an incline bench, thumbs up, arms at ~120°. Low load, high control — this is the cleanest supraspinatus isolation.',
        motion: 'Shoulder abduction in the scapular plane',
      },
      {
        name: 'Scaption raise (0–60°)',
        kind: 'isolation',
        equipment: 'Light dumbbells',
        cue: 'Raise in the plane of the scapula (~30° forward of the frontal plane), thumbs up. Supraspinatus dominates the first 15–30° before the deltoid takes over.',
        motion: 'Shoulder abduction',
      },
      {
        name: 'Empty-can / Jobe test',
        kind: 'manual test',
        equipment: 'None',
        cue: 'Arm at 90° abduction, internally rotated, resist downward pressure. Pain or weakness suggests supraspinatus pathology.',
        motion: 'Resisted abduction',
      },
    ],
    antagonists: ['l_pec_major_sternal', 'l_lat_dorsi'],
    synergists: ['l_deltoid_middle'],
    clinical:
      'Its tendon passes under the coracoacromial arch, making it the most frequently torn tendon in the body. The critical zone about 1 cm from the insertion is relatively avascular.',
  },
  {
    id: 'l_infraspinatus',
    name: 'Infraspinatus',
    latin: 'Musculus infraspinatus',
    side: 'left',
    group: 'Rotator cuff',
    region: 'shoulder',
    layer: 2,
    girth: 0.018,
    path: [
      p('l_scapula', [0.082, 1.308, -0.066]),
      via('l_scapula', [0.146, 1.35, -0.05]),
      p('l_shoulder', [0.19, 1.384, -0.02]),
    ],
    originDesc: 'Infraspinous fossa of the scapula',
    insertionDesc: 'Middle facet of the greater tubercle of the humerus',
    actions: [
      { joint: 'l_glenohumeral', motion: 'external rotation', role: 'prime' },
      { joint: 'l_glenohumeral', motion: 'extension', role: 'assist' },
      { joint: 'l_glenohumeral', motion: 'adduction', role: 'stabilise' },
    ],
    innervation: 'Suprascapular nerve (C5, C6)',
    nerve: 'l_suprascapular',
    bloodSupply: 'Suprascapular and circumflex scapular arteries',
    palpation: 'Below the scapular spine, medial to the posterior deltoid.',
    exercises: [
      {
        name: 'Side-lying external rotation',
        kind: 'isolation',
        equipment: 'Light dumbbell, towel under the elbow',
        cue: 'The classic isolator. Elbow pinned to the ribs at 90°, rotate the forearm up only. A rolled towel under the arm adds ~20% activation.',
        motion: 'Shoulder external rotation',
      },
      {
        name: 'Cable external rotation at 90° abduction',
        kind: 'isolation',
        equipment: 'Cable at shoulder height',
        cue: 'Trains the cuff in the throwing position, where it actually has to work.',
        motion: 'Shoulder external rotation',
      },
      {
        name: 'Prone horizontal abduction with external rotation ("T")',
        kind: 'activation',
        equipment: 'Bodyweight or light plates',
        cue: 'Face down, arms out at 90°, thumbs up; combines cuff and scapular retractor work.',
        motion: 'Horizontal abduction + external rotation',
      },
      {
        name: 'Sleeper stretch',
        kind: 'stretch',
        equipment: 'Floor',
        cue: 'Side-lying, shoulder at 90°, gently internally rotate. Targets posterior cuff tightness in throwers.',
        motion: 'Shoulder internal rotation',
      },
    ],
    antagonists: ['l_subscapularis', 'l_pec_major_sternal', 'l_lat_dorsi'],
    synergists: ['l_teres_minor', 'l_deltoid_posterior'],
    clinical:
      'Provides roughly 60% of external rotation strength. Isolated wasting of the infraspinous fossa suggests suprascapular nerve entrapment at the spinoglenoid notch.',
  },
  {
    id: 'l_teres_minor',
    name: 'Teres minor',
    latin: 'Musculus teres minor',
    side: 'left',
    group: 'Rotator cuff',
    region: 'shoulder',
    layer: 3,
    girth: 0.011,
    path: [
      p('l_scapula', [0.116, 1.288, -0.06]),
      p('l_shoulder', [0.189, 1.368, -0.022]),
    ],
    originDesc: 'Upper part of the lateral border of the scapula',
    insertionDesc: 'Inferior facet of the greater tubercle of the humerus',
    actions: [
      { joint: 'l_glenohumeral', motion: 'external rotation', role: 'prime' },
      { joint: 'l_glenohumeral', motion: 'adduction', role: 'assist' },
    ],
    innervation: 'Axillary nerve (C5, C6)',
    nerve: 'l_axillary',
    bloodSupply: 'Circumflex scapular artery',
    exercises: [
      {
        name: 'Side-lying external rotation',
        kind: 'isolation',
        equipment: 'Light dumbbell',
        cue: 'Works with infraspinatus; there is no practical way to isolate teres minor from it in the gym.',
        motion: 'Shoulder external rotation',
      },
      {
        name: 'Bent-over external rotation at 90° abduction',
        kind: 'isolation',
        equipment: 'Light dumbbell',
        cue: 'Slightly greater teres minor contribution than at 0° abduction.',
        motion: 'Shoulder external rotation',
      },
    ],
    antagonists: ['l_subscapularis'],
    synergists: ['l_infraspinatus'],
    clinical:
      'The only cuff muscle supplied by the axillary nerve, so it is spared in suprascapular nerve lesions — a useful localising sign.',
  },
  {
    id: 'l_subscapularis',
    name: 'Subscapularis',
    latin: 'Musculus subscapularis',
    side: 'left',
    group: 'Rotator cuff',
    region: 'shoulder',
    layer: 3,
    girth: 0.018,
    path: [
      p('l_scapula', [0.08, 1.324, -0.044]),
      via('l_scapula', [0.142, 1.36, -0.018]),
      p('l_shoulder', [0.168, 1.386, 0.018]),
    ],
    originDesc: 'Subscapular fossa (anterior surface of the scapula)',
    insertionDesc: 'Lesser tubercle of the humerus',
    actions: [
      { joint: 'l_glenohumeral', motion: 'internal rotation', role: 'prime' },
      { joint: 'l_glenohumeral', motion: 'adduction', role: 'assist' },
      { joint: 'l_glenohumeral', motion: 'extension', role: 'stabilise' },
    ],
    innervation: 'Upper and lower subscapular nerves (C5–C6)',
    nerve: 'l_subscapular',
    bloodSupply: 'Subscapular artery',
    exercises: [
      {
        name: 'Side-lying internal rotation',
        kind: 'isolation',
        equipment: 'Light dumbbell',
        cue: 'Lie on the working side, elbow at 90°, rotate the forearm up toward the abdomen.',
        motion: 'Shoulder internal rotation',
      },
      {
        name: 'Cable internal rotation',
        kind: 'isolation',
        equipment: 'Cable at elbow height',
        cue: 'Elbow tucked; rotate the forearm across the body. Keep the humerus from adducting or the pec takes over.',
        motion: 'Shoulder internal rotation',
      },
      {
        name: 'Belly-press (Gerber lift-off) test',
        kind: 'manual test',
        equipment: 'None',
        cue: 'Press the palm into the abdomen keeping the elbow forward; inability indicates subscapularis tear.',
        motion: 'Resisted internal rotation',
      },
    ],
    antagonists: ['l_infraspinatus', 'l_teres_minor'],
    synergists: ['l_pec_major_sternal', 'l_lat_dorsi', 'l_teres_major'],
    clinical:
      'The anterior wall of the cuff and the main restraint against anterior humeral translation. Its tear is easily missed on examination because pectoralis major can substitute for internal rotation.',
  },
  // =========================================================== CHEST / ANTERIOR WALL
  {
    id: 'l_pec_major_clavicular',
    name: 'Pectoralis major — clavicular head',
    latin: 'Musculus pectoralis major, pars clavicularis',
    side: 'left',
    group: 'Pectoralis major',
    region: 'chest',
    layer: 1,
    girth: 0.029,
    path: [
      p('l_clavicle', [0.045, 1.398, 0.036]),
      via('chest', [0.125, 1.365, 0.058]),
      p('l_shoulder', [0.183, 1.334, 0.012]),
    ],
    originDesc: 'Medial half of the anterior surface of the clavicle',
    insertionDesc: 'Lateral lip of the intertubercular groove of the humerus (anterior lamina)',
    actions: [
      { joint: 'l_glenohumeral', motion: 'flexion', role: 'prime' },
      { joint: 'l_glenohumeral', motion: 'adduction', role: 'assist' },
      { joint: 'l_glenohumeral', motion: 'internal rotation', role: 'assist' },
    ],
    innervation: 'Lateral pectoral nerve (C5–C7)',
    nerve: 'l_pectoral',
    bloodSupply: 'Pectoral branch of the thoracoacromial artery',
    palpation: 'Upper chest just below the clavicle; contracts on a low-to-high punch.',
    exercises: [
      {
        name: 'Incline bench press (30–45°)',
        kind: 'compound',
        equipment: 'Barbell or dumbbells',
        cue: 'The bench angle aligns the resistance with the clavicular fibre direction. Beyond ~45° the anterior deltoid takes over.',
        motion: 'Shoulder flexion + adduction',
      },
      {
        name: 'Low-to-high cable fly',
        kind: 'isolation',
        equipment: 'Low pulleys',
        cue: 'Sweep the hands up and together to chin height — matches the clavicular line of pull exactly.',
        motion: 'Shoulder flexion + horizontal adduction',
      },
      {
        name: 'Incline dumbbell fly',
        kind: 'isolation',
        equipment: 'Dumbbells, incline bench',
        cue: 'Slight elbow bend, stretch at the bottom, squeeze without letting the shoulders roll forward.',
        motion: 'Shoulder horizontal adduction',
      },
    ],
    antagonists: ['l_deltoid_posterior', 'l_lat_dorsi', 'l_infraspinatus'],
    synergists: ['l_deltoid_anterior', 'l_biceps_short', 'l_coracobrachialis'],
    clinical:
      'The two heads can be trained differentially — a real effect, not gym folklore, because the clavicular head lies above the axis of shoulder flexion and the sternal head below it.',
  },
  {
    id: 'l_pec_major_sternal',
    name: 'Pectoralis major — sternocostal head',
    latin: 'Musculus pectoralis major, pars sternocostalis',
    side: 'left',
    group: 'Pectoralis major',
    region: 'chest',
    layer: 1,
    girth: 0.035,
    path: [
      p('chest', [0.014, 1.29, 0.086]),
      via('chest', [0.11, 1.33, 0.06]),
      p('l_shoulder', [0.181, 1.348, 0.006]),
    ],
    originDesc: 'Anterior surface of the sternum, costal cartilages 1–6, and the aponeurosis of external oblique',
    insertionDesc: 'Lateral lip of the intertubercular groove (posterior lamina, twisting behind the clavicular fibres)',
    actions: [
      { joint: 'l_glenohumeral', motion: 'adduction', role: 'prime' },
      { joint: 'l_glenohumeral', motion: 'internal rotation', role: 'prime' },
      { joint: 'l_glenohumeral', motion: 'extension', role: 'assist' },
    ],
    innervation: 'Medial and lateral pectoral nerves (C6–T1)',
    nerve: 'l_pectoral',
    bloodSupply: 'Pectoral branch of the thoracoacromial artery, intercostal perforators',
    palpation: 'The bulk of the chest; the free lower border forms the anterior wall of the axilla.',
    exercises: [
      {
        name: 'Flat or decline bench press',
        kind: 'compound',
        equipment: 'Barbell or dumbbells',
        cue: 'Decline or flat pressing with a slightly tucked elbow matches the sternal fibre line. Retract the scapulae and keep them retracted.',
        motion: 'Shoulder horizontal adduction',
      },
      {
        name: 'High-to-low cable fly',
        kind: 'isolation',
        equipment: 'High pulleys',
        cue: 'Cross the hands below the sternum. Adding a little internal rotation at the finish squeezes out the last of the range.',
        motion: 'Shoulder horizontal adduction',
      },
      {
        name: 'Dip (torso leaning forward)',
        kind: 'compound',
        equipment: 'Parallel bars',
        cue: 'Lean the chest forward and let the elbows flare slightly — upright dips are a triceps exercise instead.',
        motion: 'Shoulder adduction + extension',
      },
      {
        name: 'Pec-deck / machine fly',
        kind: 'isolation',
        equipment: 'Machine',
        cue: 'Fixes the elbow angle so nothing but horizontal adduction can happen — the most isolating option.',
        motion: 'Shoulder horizontal adduction',
      },
    ],
    antagonists: ['l_deltoid_posterior', 'l_infraspinatus', 'l_trapezius_middle'],
    synergists: ['l_deltoid_anterior', 'l_lat_dorsi', 'l_subscapularis'],
    clinical:
      'Its tendon twists 180° on its way to the humerus, which is why the lower fibres insert highest. Rupture at the tendon is a bench-press injury and shows as loss of the axillary fold.',
  },
  {
    id: 'l_pec_minor',
    name: 'Pectoralis minor',
    latin: 'Musculus pectoralis minor',
    side: 'left',
    group: 'Anterior thoracic wall',
    region: 'chest',
    layer: 2,
    girth: 0.012,
    path: [
      p('thorax', [0.056, 1.238, 0.076]),
      p('l_scapula', [0.11, 1.374, 0.045]),
    ],
    originDesc: 'Anterior surfaces of ribs 3–5 near their costal cartilages',
    insertionDesc: 'Coracoid process of the scapula',
    actions: [
      { joint: 'l_scapulothoracic', motion: 'protraction', role: 'prime' },
      { joint: 'l_scapulothoracic', motion: 'depression', role: 'assist' },
      { joint: 'l_scapulothoracic', motion: 'downward rotation', role: 'assist' },
    ],
    innervation: 'Medial pectoral nerve (C8, T1)',
    nerve: 'l_pectoral',
    bloodSupply: 'Pectoral branch of the thoracoacromial artery',
    exercises: [
      {
        name: 'Supine corner (pec minor) stretch',
        kind: 'stretch',
        equipment: 'Foam roller or towel roll',
        cue: 'Lie along a roller with arms out in a "W"; let gravity draw the shoulders back. A tight pec minor tips the scapula anteriorly and narrows the subacromial space.',
        motion: 'Scapular retraction + posterior tilt',
      },
      {
        name: 'Scapular push-up (plus)',
        kind: 'activation',
        equipment: 'Bodyweight',
        cue: 'From a push-up top position, protract and retract without bending the elbows. Trains pec minor with serratus anterior.',
        motion: 'Scapular protraction',
      },
    ],
    antagonists: ['l_trapezius_middle', 'l_rhomboid_major', 'l_trapezius_lower'],
    synergists: ['l_serratus_anterior'],
    clinical:
      'Both cords of the brachial plexus and the axillary vessels pass behind it — tightness contributes to neurogenic thoracic outlet syndrome.',
  },
  {
    id: 'l_serratus_anterior',
    name: 'Serratus anterior',
    latin: 'Musculus serratus anterior',
    side: 'left',
    group: 'Scapular stabilisers',
    region: 'chest',
    layer: 2,
    girth: 0.014,
    path: [
      p('thorax', [0.104, 1.2, 0.05]),
      via('thorax', [0.116, 1.27, 0.012]),
      via('thorax', [0.1, 1.3, -0.03]),
      p('l_scapula', [0.05, 1.302, -0.042]),
    ],
    originDesc: 'Outer surfaces of ribs 1–8 by fleshy digitations',
    insertionDesc: 'Costal (anterior) surface of the medial border of the scapula',
    actions: [
      { joint: 'l_scapulothoracic', motion: 'protraction', role: 'prime' },
      { joint: 'l_scapulothoracic', motion: 'upward rotation', role: 'prime' },
      { joint: 'l_glenohumeral', motion: 'abduction', role: 'stabilise' },
    ],
    innervation: 'Long thoracic nerve (C5, C6, C7 — "C5, 6, 7 keep the wing from heaven")',
    nerve: 'l_long_thoracic',
    bloodSupply: 'Lateral thoracic artery',
    palpation: 'The serrated digitations are visible over the lateral ribs in lean people when the arm reaches forward.',
    exercises: [
      {
        name: 'Scapular push-up ("push-up plus")',
        kind: 'activation',
        equipment: 'Bodyweight',
        cue: 'At the top of a push-up, push the floor away further to protract fully. The gold-standard serratus drill.',
        motion: 'Scapular protraction',
      },
      {
        name: 'Overhead press / wall slide with upward rotation',
        kind: 'isolation',
        equipment: 'Wall and towel, or a light bar',
        cue: 'Slide the forearms up the wall while reaching long at the top — the reach is what recruits serratus.',
        motion: 'Scapular upward rotation',
      },
      {
        name: 'Bear-crawl or plank protraction hold',
        kind: 'activation',
        equipment: 'Bodyweight',
        cue: 'Serratus works isometrically to keep the scapula flat on the ribcage; look for absence of winging.',
        motion: 'Scapular protraction (isometric)',
      },
      {
        name: 'Landmine press',
        kind: 'compound',
        equipment: 'Barbell in a landmine',
        cue: 'The arcing path demands protraction with elevation, loading serratus more than a vertical press.',
        motion: 'Protraction + upward rotation',
      },
    ],
    antagonists: ['l_rhomboid_major', 'l_rhomboid_minor', 'l_trapezius_middle'],
    synergists: ['l_trapezius_upper', 'l_trapezius_lower', 'l_pec_minor'],
    clinical:
      'Long thoracic nerve palsy produces the classic winged scapula, most obvious on a wall push-up. Without serratus you cannot elevate the arm fully because the scapula will not rotate upward.',
  },
  {
    id: 'l_subclavius',
    name: 'Subclavius',
    latin: 'Musculus subclavius',
    side: 'left',
    group: 'Anterior thoracic wall',
    region: 'chest',
    layer: 3,
    girth: 0.008,
    path: [
      p('thorax', [0.028, 1.362, 0.056]),
      p('l_clavicle', [0.112, 1.39, 0.014]),
    ],
    originDesc: 'First rib at its costal cartilage junction',
    insertionDesc: 'Inferior surface of the middle third of the clavicle',
    actions: [
      { joint: 'l_sternoclavicular', motion: 'depression', role: 'prime' },
      { joint: 'l_sternoclavicular', motion: 'protraction', role: 'stabilise' },
    ],
    innervation: 'Nerve to subclavius (C5, C6)',
    bloodSupply: 'Clavicular branch of the thoracoacromial artery',
    exercises: [
      {
        name: 'Weighted scapular depression (dip hold)',
        kind: 'activation',
        equipment: 'Parallel bars',
        cue: 'Support the bodyweight and push the shoulders down away from the ears.',
        motion: 'Clavicular depression',
      },
    ],
    clinical:
      'Acts mainly as a dynamic strut protecting the subclavian vessels; it cushions the clavicle against medial force.',
  },
  // =========================================================== BACK: scapular movers
  {
    id: 'l_lat_dorsi',
    name: 'Latissimus dorsi',
    latin: 'Musculus latissimus dorsi',
    side: 'left',
    group: 'Superficial back',
    region: 'back',
    layer: 1,
    girth: 0.035,
    path: [
      p('pelvis', [0.032, 1.0, -0.052]),
      via('lumbar', [0.052, 1.09, -0.062]),
      via('thorax', [0.078, 1.22, -0.058]),
      via('thorax', [0.108, 1.3, -0.038]),
      p('l_shoulder', [0.171, 1.338, 0.004]),
    ],
    originDesc:
      'Spinous processes of T7–L5 and the sacrum via the thoracolumbar fascia, posterior iliac crest, lower 3–4 ribs, inferior angle of the scapula',
    insertionDesc: 'Floor of the intertubercular groove of the humerus',
    actions: [
      { joint: 'l_glenohumeral', motion: 'extension', role: 'prime' },
      { joint: 'l_glenohumeral', motion: 'adduction', role: 'prime' },
      { joint: 'l_glenohumeral', motion: 'internal rotation', role: 'assist' },
      { joint: 'lumbar_spine', motion: 'extension', role: 'assist' },
    ],
    innervation: 'Thoracodorsal nerve (C6, C7, C8)',
    nerve: 'l_thoracodorsal',
    bloodSupply: 'Thoracodorsal artery',
    palpation: 'The posterior wall of the axilla; grip it between finger and thumb and resist arm adduction.',
    exercises: [
      {
        name: 'Straight-arm pulldown (pullover)',
        kind: 'isolation',
        equipment: 'High cable, straight bar or rope',
        cue: 'The best isolator: the elbow stays locked so the biceps cannot help. Hinge slightly and sweep the bar to the thighs.',
        motion: 'Shoulder extension',
      },
      {
        name: 'Wide-grip pull-up or pulldown',
        kind: 'compound',
        equipment: 'Bar or lat machine',
        cue: 'Pull the elbows down and *in* toward the ribs, thinking about the elbow rather than the hand.',
        motion: 'Shoulder adduction + extension',
      },
      {
        name: 'Single-arm dumbbell row',
        kind: 'compound',
        equipment: 'Dumbbell and bench',
        cue: 'Row toward the hip rather than the armpit; a slightly extended path favours the latissimus over the mid-trapezius.',
        motion: 'Shoulder extension',
      },
      {
        name: 'Overhead side-bend hang stretch',
        kind: 'stretch',
        equipment: 'Bar or doorframe',
        cue: 'Hang one-handed and shift the hips away from the working side to lengthen it from origin to insertion.',
        motion: 'Shoulder flexion + contralateral side-bend',
      },
    ],
    antagonists: ['l_deltoid_anterior', 'l_deltoid_middle', 'l_pec_major_clavicular', 'l_trapezius_upper'],
    synergists: ['l_teres_major', 'l_pec_major_sternal', 'l_triceps_long'],
    clinical:
      'The only muscle linking the upper limb to the pelvis, so it couples arm action to the sacroiliac joint through the thoracolumbar fascia — the anatomical reason a strong lat helps a heavy deadlift stay tight.',
  },
  {
    id: 'l_teres_major',
    name: 'Teres major',
    latin: 'Musculus teres major',
    side: 'left',
    group: 'Superficial back',
    region: 'shoulder',
    layer: 2,
    girth: 0.015,
    path: [
      p('l_scapula', [0.08, 1.246, -0.06]),
      p('l_shoulder', [0.172, 1.324, -0.006]),
    ],
    originDesc: 'Posterior surface of the inferior angle of the scapula',
    insertionDesc: 'Medial lip of the intertubercular groove of the humerus',
    actions: [
      { joint: 'l_glenohumeral', motion: 'adduction', role: 'prime' },
      { joint: 'l_glenohumeral', motion: 'extension', role: 'assist' },
      { joint: 'l_glenohumeral', motion: 'internal rotation', role: 'assist' },
    ],
    innervation: 'Lower subscapular nerve (C5, C6)',
    nerve: 'l_subscapular',
    bloodSupply: 'Circumflex scapular artery',
    exercises: [
      {
        name: 'Wide-grip pulldown',
        kind: 'compound',
        equipment: 'Lat machine',
        cue: 'Works with the latissimus — "lat\'s little helper". Pull to the upper chest.',
        motion: 'Shoulder adduction',
      },
      {
        name: 'Straight-arm pulldown',
        kind: 'isolation',
        equipment: 'High cable',
        cue: 'Shoulder extension with a locked elbow loads teres major alongside the latissimus.',
        motion: 'Shoulder extension',
      },
    ],
    antagonists: ['l_deltoid_middle', 'l_supraspinatus'],
    synergists: ['l_lat_dorsi', 'l_subscapularis'],
    clinical:
      'Together with the latissimus tendon it forms the posterior wall of the axilla and the lower border of the quadrangular space.',
  },
  {
    id: 'l_trapezius_upper',
    name: 'Trapezius — upper (descending) fibres',
    latin: 'Musculus trapezius, pars descendens',
    side: 'left',
    group: 'Trapezius',
    region: 'back',
    layer: 1,
    girth: 0.019,
    path: [
      p('head', [0.012, 1.598, -0.07]),
      via('neck', [0.034, 1.47, -0.056]),
      p('l_clavicle', [0.134, 1.4, -0.006]),
    ],
    originDesc: 'External occipital protuberance, medial nuchal line and the nuchal ligament',
    insertionDesc: 'Posterior border of the lateral third of the clavicle',
    actions: [
      { joint: 'l_scapulothoracic', motion: 'elevation', role: 'prime' },
      { joint: 'l_scapulothoracic', motion: 'upward rotation', role: 'assist' },
      { joint: 'cervical_spine', motion: 'extension', role: 'assist' },
      { joint: 'cervical_spine', motion: 'left lateral flexion', role: 'assist' },
    ],
    innervation: 'Accessory nerve (CN XI), with proprioceptive fibres from C3–C4',
    nerve: 'l_accessory',
    bloodSupply: 'Transverse cervical artery',
    palpation: 'The sloping ridge from neck to shoulder; shrug against resistance.',
    exercises: [
      {
        name: 'Barbell or dumbbell shrug',
        kind: 'isolation',
        equipment: 'Barbell, dumbbells or trap bar',
        cue: 'Straight up and slightly back, no rolling. Pause at the top — the range is short so time under tension matters.',
        motion: 'Scapular elevation',
      },
      {
        name: 'Farmer\'s carry',
        kind: 'activation',
        equipment: 'Heavy dumbbells / handles',
        cue: 'Loaded isometric elevation; also trains grip and trunk stability.',
        motion: 'Scapular elevation (isometric)',
      },
      {
        name: 'Upper trapezius stretch',
        kind: 'stretch',
        equipment: 'None',
        cue: 'Depress the shoulder, then side-bend and rotate the head away. Hold 30 s.',
        motion: 'Cervical side-bend with scapular depression',
      },
    ],
    antagonists: ['l_trapezius_lower', 'l_pec_minor', 'l_subclavius'],
    synergists: ['l_levator_scapulae', 'l_serratus_anterior'],
    clinical:
      'Habitually overactive in desk workers and often the site of referred "tension headache". A shrug that cannot be performed indicates accessory nerve injury — a known complication of posterior neck surgery.',
  },
  {
    id: 'l_trapezius_middle',
    name: 'Trapezius — middle (transverse) fibres',
    latin: 'Musculus trapezius, pars transversa',
    side: 'left',
    group: 'Trapezius',
    region: 'back',
    layer: 1,
    girth: 0.022,
    path: [
      p('thorax', [0.0, 1.33, -0.066]),
      p('l_scapula', [0.128, 1.384, -0.05]),
    ],
    originDesc: 'Spinous processes of C7–T3',
    insertionDesc: 'Medial acromion and superior lip of the scapular spine',
    actions: [
      { joint: 'l_scapulothoracic', motion: 'retraction', role: 'prime' },
      { joint: 'l_scapulothoracic', motion: 'upward rotation', role: 'stabilise' },
    ],
    innervation: 'Accessory nerve (CN XI), C3–C4 proprioception',
    nerve: 'l_accessory',
    bloodSupply: 'Transverse cervical artery, dorsal scapular artery',
    exercises: [
      {
        name: 'Chest-supported row / seated row with a squeeze',
        kind: 'compound',
        equipment: 'Bench and dumbbells, or cable row',
        cue: 'Pull the shoulder blades together and hold for a beat at the end range. Retraction, not elbow flexion, is the point.',
        motion: 'Scapular retraction',
      },
      {
        name: 'Prone "T" raise',
        kind: 'isolation',
        equipment: 'Bodyweight or light plates',
        cue: 'Arms straight out at 90°, thumbs up, lift by retracting. Highest mid-trapezius activation of any common drill.',
        motion: 'Scapular retraction',
      },
      {
        name: 'Band pull-apart',
        kind: 'activation',
        equipment: 'Resistance band',
        cue: 'Arms straight at chest height; pull the band apart until the arms are in line with the shoulders.',
        motion: 'Scapular retraction + horizontal abduction',
      },
    ],
    antagonists: ['l_serratus_anterior', 'l_pec_minor'],
    synergists: ['l_rhomboid_major', 'l_rhomboid_minor', 'l_trapezius_lower'],
    clinical:
      'Weak middle trapezius plus a tight pec minor is the standard "rounded shoulder" pairing; retraining retraction is a first-line intervention.',
  },
  {
    id: 'l_trapezius_lower',
    name: 'Trapezius — lower (ascending) fibres',
    latin: 'Musculus trapezius, pars ascendens',
    side: 'left',
    group: 'Trapezius',
    region: 'back',
    layer: 1,
    girth: 0.023,
    path: [
      p('thorax', [0.0, 1.19, -0.06]),
      via('thorax', [0.036, 1.27, -0.064]),
      p('l_scapula', [0.062, 1.354, -0.06]),
    ],
    originDesc: 'Spinous processes of T4–T12',
    insertionDesc: 'Medial end of the scapular spine (deltoid tubercle)',
    actions: [
      { joint: 'l_scapulothoracic', motion: 'depression', role: 'prime' },
      { joint: 'l_scapulothoracic', motion: 'upward rotation', role: 'prime' },
      { joint: 'l_scapulothoracic', motion: 'retraction', role: 'assist' },
    ],
    innervation: 'Accessory nerve (CN XI), C3–C4 proprioception',
    nerve: 'l_accessory',
    bloodSupply: 'Dorsal scapular artery',
    exercises: [
      {
        name: 'Prone "Y" raise',
        kind: 'isolation',
        equipment: 'Incline bench, light plates',
        cue: 'Arms overhead at ~135°, thumbs up. The single most specific lower-trapezius drill; keep the neck long.',
        motion: 'Scapular upward rotation + depression',
      },
      {
        name: 'Half-kneeling single-arm overhead press',
        kind: 'compound',
        equipment: 'Dumbbell or kettlebell',
        cue: 'Reach tall at the top; the lower trapezius and serratus produce the upward rotation that opens the subacromial space.',
        motion: 'Scapular upward rotation',
      },
      {
        name: 'Wall slide with band',
        kind: 'activation',
        equipment: 'Wall, light band',
        cue: 'Slide up the wall pressing out against the band. Cue "armpits down" to bias the lower over the upper fibres.',
        motion: 'Upward rotation + depression',
      },
    ],
    antagonists: ['l_trapezius_upper', 'l_levator_scapulae'],
    synergists: ['l_serratus_anterior', 'l_trapezius_middle'],
    clinical:
      'The key muscle in shoulder-impingement rehab: it produces upward rotation *and* depression, the combination that keeps the acromion clear of the cuff.',
  },
  {
    id: 'l_rhomboid_major',
    name: 'Rhomboid major',
    latin: 'Musculus rhomboideus major',
    side: 'left',
    group: 'Scapular stabilisers',
    region: 'back',
    layer: 2,
    girth: 0.013,
    path: [
      p('thorax', [0.0, 1.276, -0.064]),
      p('l_scapula', [0.05, 1.268, -0.062]),
    ],
    originDesc: 'Spinous processes of T2–T5',
    insertionDesc: 'Medial border of the scapula below the level of the spine',
    actions: [
      { joint: 'l_scapulothoracic', motion: 'retraction', role: 'prime' },
      { joint: 'l_scapulothoracic', motion: 'downward rotation', role: 'prime' },
      { joint: 'l_scapulothoracic', motion: 'elevation', role: 'assist' },
    ],
    innervation: 'Dorsal scapular nerve (C4, C5)',
    nerve: 'l_dorsal_scapular',
    bloodSupply: 'Dorsal scapular artery',
    exercises: [
      {
        name: 'Seated row with full retraction',
        kind: 'compound',
        equipment: 'Cable row',
        cue: 'Neutral or narrow grip, elbows close, pull the shoulder blades toward the spine.',
        motion: 'Scapular retraction',
      },
      {
        name: 'Prone horizontal abduction ("T"), thumbs down',
        kind: 'isolation',
        equipment: 'Light plates',
        cue: 'Thumbs down (internal rotation) shifts emphasis from mid-trapezius toward the rhomboids.',
        motion: 'Scapular retraction + downward rotation',
      },
      {
        name: 'Inverted row',
        kind: 'compound',
        equipment: 'Bar or rings',
        cue: 'Body rigid, retract before you bend the elbows.',
        motion: 'Scapular retraction',
      },
    ],
    antagonists: ['l_serratus_anterior', 'l_pec_minor'],
    synergists: ['l_rhomboid_minor', 'l_trapezius_middle', 'l_levator_scapulae'],
    clinical:
      'Its downward-rotation action opposes serratus anterior; a rhomboid-dominant, serratus-weak pattern limits overhead reach.',
  },
  {
    id: 'l_rhomboid_minor',
    name: 'Rhomboid minor',
    latin: 'Musculus rhomboideus minor',
    side: 'left',
    group: 'Scapular stabilisers',
    region: 'back',
    layer: 2,
    girth: 0.01,
    path: [
      p('thorax', [0.0, 1.356, -0.06]),
      p('l_scapula', [0.048, 1.35, -0.062]),
    ],
    originDesc: 'Nuchal ligament and spinous processes of C7–T1',
    insertionDesc: 'Medial border of the scapula at the root of the spine',
    actions: [
      { joint: 'l_scapulothoracic', motion: 'retraction', role: 'prime' },
      { joint: 'l_scapulothoracic', motion: 'elevation', role: 'assist' },
      { joint: 'l_scapulothoracic', motion: 'downward rotation', role: 'assist' },
    ],
    innervation: 'Dorsal scapular nerve (C4, C5)',
    nerve: 'l_dorsal_scapular',
    bloodSupply: 'Dorsal scapular artery',
    exercises: [
      {
        name: 'Scapular retraction hold',
        kind: 'activation',
        equipment: 'Band or bodyweight',
        cue: 'Hold end-range retraction for 5 s at a time; endurance rather than load is the deficit here.',
        motion: 'Scapular retraction',
      },
      {
        name: 'Face pull',
        kind: 'compound',
        equipment: 'Rope on high cable',
        cue: 'Trains the rhomboids with the posterior deltoid and external rotators.',
        motion: 'Retraction + external rotation',
      },
    ],
    antagonists: ['l_serratus_anterior'],
    synergists: ['l_rhomboid_major', 'l_levator_scapulae'],
  },
  {
    id: 'l_levator_scapulae',
    name: 'Levator scapulae',
    latin: 'Musculus levator scapulae',
    side: 'left',
    group: 'Scapular stabilisers',
    region: 'neck',
    layer: 2,
    girth: 0.011,
    path: [
      p('neck', [0.022, 1.512, -0.038]),
      via('neck', [0.036, 1.45, -0.05]),
      p('l_scapula', [0.05, 1.386, -0.06]),
    ],
    originDesc: 'Posterior tubercles of the transverse processes of C1–C4',
    insertionDesc: 'Medial border of the scapula between the superior angle and the root of the spine',
    actions: [
      { joint: 'l_scapulothoracic', motion: 'elevation', role: 'prime' },
      { joint: 'l_scapulothoracic', motion: 'downward rotation', role: 'assist' },
      { joint: 'cervical_spine', motion: 'left lateral flexion', role: 'assist' },
      { joint: 'cervical_spine', motion: 'left rotation', role: 'assist' },
    ],
    innervation: 'Cervical nerves C3–C4 and the dorsal scapular nerve (C5)',
    nerve: 'l_dorsal_scapular',
    bloodSupply: 'Dorsal scapular artery',
    palpation: 'Between the posterior border of sternocleidomastoid and the upper trapezius, running to the superior angle.',
    exercises: [
      {
        name: 'Shrug with the head turned away',
        kind: 'isolation',
        equipment: 'Dumbbells',
        cue: 'Rotating the neck away puts the levator on stretch and biases it over the upper trapezius.',
        motion: 'Scapular elevation',
      },
      {
        name: 'Levator scapulae stretch',
        kind: 'stretch',
        equipment: 'None',
        cue: 'Depress the shoulder, rotate the head away, then look down into the armpit — different from the upper-trapezius stretch, which looks up.',
        motion: 'Cervical flexion + contralateral rotation',
      },
    ],
    antagonists: ['l_trapezius_lower', 'l_serratus_anterior'],
    synergists: ['l_trapezius_upper', 'l_rhomboid_minor'],
    clinical:
      'The commonest source of the sharp "crick" at the top medial border of the scapula, especially after sleeping awkwardly or a long phone-to-shoulder habit.',
  },
  // ================================================================ ARM: elbow flexors
  {
    id: 'l_biceps_long',
    name: 'Biceps brachii — long head',
    latin: 'Musculus biceps brachii, caput longum',
    side: 'left',
    group: 'Biceps brachii',
    region: 'arm',
    layer: 1,
    girth: 0.019,
    path: [
      p('l_scapula', [0.163, 1.402, 0.004]),
      via('l_shoulder', [0.182, 1.36, 0.021]),
      via('l_shoulder', [0.195, 1.2, 0.026]),
      p('l_radioulnar', [0.222, 1.045, 0.013]),
    ],
    originDesc: 'Supraglenoid tubercle of the scapula, via a tendon that runs through the joint and the intertubercular groove',
    insertionDesc: 'Radial tuberosity, plus the bicipital aponeurosis into the deep forearm fascia',
    actions: [
      { joint: 'l_elbow', motion: 'flexion', role: 'prime' },
      { joint: 'l_radioulnar', motion: 'supination', role: 'prime' },
      { joint: 'l_glenohumeral', motion: 'flexion', role: 'assist' },
      { joint: 'l_glenohumeral', motion: 'abduction', role: 'stabilise' },
    ],
    innervation: 'Musculocutaneous nerve (C5, C6)',
    nerve: 'l_musculocutaneous',
    bloodSupply: 'Brachial artery',
    palpation: 'The bulge of the front of the arm; its tendon is palpable in the cubital fossa.',
    exercises: [
      {
        name: 'Incline dumbbell curl',
        kind: 'isolation',
        equipment: 'Incline bench, dumbbells',
        cue: 'Lying back puts the shoulder into extension, lengthening the long head across the shoulder — the best long-head bias.',
        motion: 'Elbow flexion with the shoulder extended',
      },
      {
        name: 'Behind-the-body cable curl (Bayesian curl)',
        kind: 'isolation',
        equipment: 'Low cable',
        cue: 'Step forward of the pulley so the arm starts behind the torso; maximum long-head stretch under load.',
        motion: 'Elbow flexion',
      },
      {
        name: 'Narrow-grip barbell curl',
        kind: 'isolation',
        equipment: 'Barbell',
        cue: 'A narrower grip places the arm in relative adduction, favouring the long (lateral, outer) head.',
        motion: 'Elbow flexion + supination',
      },
      {
        name: 'Supinated cable curl held at 90°',
        kind: 'isolation',
        equipment: 'Cable',
        cue: 'Full supination recruits biceps hard; brachialis and brachioradialis cannot supinate, so this separates them.',
        motion: 'Forearm supination',
      },
    ],
    antagonists: ['l_triceps_long', 'l_triceps_lateral', 'l_anconeus'],
    synergists: ['l_brachialis', 'l_brachioradialis', 'l_biceps_short'],
    clinical:
      'Its intracapsular tendon is a common source of anterior shoulder pain; rupture produces the "Popeye" sign as the belly retracts distally.',
  },
  {
    id: 'l_biceps_short',
    name: 'Biceps brachii — short head',
    latin: 'Musculus biceps brachii, caput breve',
    side: 'left',
    group: 'Biceps brachii',
    region: 'arm',
    layer: 1,
    girth: 0.018,
    path: [
      p('l_scapula', [0.116, 1.374, 0.046]),
      via('l_shoulder', [0.185, 1.25, 0.028]),
      p('l_radioulnar', [0.218, 1.048, 0.015]),
    ],
    originDesc: 'Apex of the coracoid process of the scapula (with coracobrachialis)',
    insertionDesc: 'Radial tuberosity via the common biceps tendon',
    actions: [
      { joint: 'l_elbow', motion: 'flexion', role: 'prime' },
      { joint: 'l_radioulnar', motion: 'supination', role: 'prime' },
      { joint: 'l_glenohumeral', motion: 'flexion', role: 'assist' },
      { joint: 'l_glenohumeral', motion: 'adduction', role: 'assist' },
    ],
    innervation: 'Musculocutaneous nerve (C5, C6)',
    nerve: 'l_musculocutaneous',
    bloodSupply: 'Brachial artery',
    exercises: [
      {
        name: 'Preacher curl',
        kind: 'isolation',
        equipment: 'Preacher bench, EZ bar',
        cue: 'The arm sits in front of the torso (shoulder flexed), shortening the long head and biasing the short head.',
        motion: 'Elbow flexion',
      },
      {
        name: 'Concentration curl',
        kind: 'isolation',
        equipment: 'Dumbbell',
        cue: 'Elbow braced on the inner thigh; supinate hard at the top.',
        motion: 'Elbow flexion + supination',
      },
      {
        name: 'Wide-grip barbell curl',
        kind: 'isolation',
        equipment: 'Barbell',
        cue: 'A wider grip abducts the arm and favours the short (medial, inner) head.',
        motion: 'Elbow flexion',
      },
    ],
    antagonists: ['l_triceps_long', 'l_triceps_medial'],
    synergists: ['l_biceps_long', 'l_brachialis', 'l_coracobrachialis'],
  },
  {
    id: 'l_brachialis',
    name: 'Brachialis',
    latin: 'Musculus brachialis',
    side: 'left',
    group: 'Elbow flexors',
    region: 'arm',
    layer: 2,
    girth: 0.016,
    path: [
      p('l_shoulder', [0.198, 1.192, 0.016]),
      p('l_elbow', [0.205, 1.055, 0.01]),
    ],
    originDesc: 'Distal half of the anterior surface of the humerus',
    insertionDesc: 'Coronoid process and tuberosity of the ulna',
    actions: [{ joint: 'l_elbow', motion: 'flexion', role: 'prime' }],
    innervation: 'Musculocutaneous nerve (C5, C6), with a radial nerve twig to the lateral part',
    nerve: 'l_musculocutaneous',
    bloodSupply: 'Brachial and radial recurrent arteries',
    palpation: 'Either side of the biceps tendon in the lower arm, best felt with the forearm pronated.',
    exercises: [
      {
        name: 'Hammer (neutral-grip) curl',
        kind: 'isolation',
        equipment: 'Dumbbells or rope on a cable',
        cue: 'Because brachialis inserts on the ulna it cannot supinate — a neutral or pronated grip takes the biceps out of its best line and loads brachialis.',
        motion: 'Elbow flexion',
      },
      {
        name: 'Reverse (pronated) barbell curl',
        kind: 'isolation',
        equipment: 'Barbell or EZ bar',
        cue: 'Full pronation puts the biceps at a mechanical disadvantage; brachialis and brachioradialis do the work.',
        motion: 'Elbow flexion with the forearm pronated',
      },
      {
        name: 'Cross-body dumbbell curl',
        kind: 'isolation',
        equipment: 'Dumbbell',
        cue: 'Curl toward the opposite shoulder in neutral grip; keeps the biceps from supinating in.',
        motion: 'Elbow flexion',
      },
    ],
    antagonists: ['l_triceps_long', 'l_triceps_medial', 'l_triceps_lateral'],
    synergists: ['l_biceps_long', 'l_brachioradialis'],
    clinical:
      'The workhorse of elbow flexion — larger cross-section than the biceps, and unaffected by forearm rotation, so it is the reason pronated curls still feel hard.',
  },
  {
    id: 'l_coracobrachialis',
    name: 'Coracobrachialis',
    latin: 'Musculus coracobrachialis',
    side: 'left',
    group: 'Anterior arm',
    region: 'arm',
    layer: 3,
    girth: 0.011,
    path: [
      p('l_scapula', [0.113, 1.372, 0.042]),
      p('l_shoulder', [0.178, 1.23, 0.011]),
    ],
    originDesc: 'Apex of the coracoid process',
    insertionDesc: 'Medial surface of the mid humeral shaft',
    actions: [
      { joint: 'l_glenohumeral', motion: 'flexion', role: 'assist' },
      { joint: 'l_glenohumeral', motion: 'adduction', role: 'assist' },
    ],
    innervation: 'Musculocutaneous nerve (C5–C7) — which pierces it',
    nerve: 'l_musculocutaneous',
    bloodSupply: 'Brachial artery',
    exercises: [
      {
        name: 'Cable shoulder adduction from overhead',
        kind: 'isolation',
        equipment: 'High cable, straight arm',
        cue: 'Straight arm pulls the humerus down and in — flexion plus adduction, the coracobrachialis line of pull.',
        motion: 'Shoulder adduction + flexion',
      },
      {
        name: 'Front raise (assisted role)',
        kind: 'compound',
        equipment: 'Dumbbell',
        cue: 'Contributes to the first part of shoulder flexion alongside the anterior deltoid.',
        motion: 'Shoulder flexion',
      },
    ],
    synergists: ['l_biceps_short', 'l_deltoid_anterior'],
    clinical:
      'A landmark: the musculocutaneous nerve passes through it, and the muscle guides the surgeon to the axillary neurovascular bundle.',
  },
  // ============================================================== ARM: elbow extensors
  {
    id: 'l_triceps_long',
    name: 'Triceps brachii — long head',
    latin: 'Musculus triceps brachii, caput longum',
    side: 'left',
    group: 'Triceps brachii',
    region: 'arm',
    layer: 1,
    girth: 0.021,
    path: [
      p('l_scapula', [0.16, 1.35, -0.03]),
      via('l_shoulder', [0.193, 1.22, -0.03]),
      p('l_elbow', [0.205, 1.1, -0.032]),
    ],
    originDesc: 'Infraglenoid tubercle of the scapula',
    insertionDesc: 'Olecranon of the ulna via the common triceps tendon',
    actions: [
      { joint: 'l_elbow', motion: 'extension', role: 'prime' },
      { joint: 'l_glenohumeral', motion: 'extension', role: 'assist' },
      { joint: 'l_glenohumeral', motion: 'adduction', role: 'assist' },
    ],
    innervation: 'Radial nerve (C6–C8)',
    nerve: 'l_radial',
    bloodSupply: 'Profunda brachii artery',
    palpation: 'The medial mass at the back of the arm, extending up into the axilla.',
    exercises: [
      {
        name: 'Overhead cable / dumbbell triceps extension',
        kind: 'isolation',
        equipment: 'Cable rope or dumbbell',
        cue: 'The long head crosses the shoulder, so it is only fully stretched with the arm overhead. This is far and away its best exercise.',
        motion: 'Elbow extension with the shoulder flexed',
      },
      {
        name: 'Incline / "skull-crusher" behind the head',
        kind: 'isolation',
        equipment: 'EZ bar, bench',
        cue: 'Lower toward the forehead or behind it to keep the shoulder flexed; elbows stay pointing at the ceiling.',
        motion: 'Elbow extension',
      },
      {
        name: 'Straight-arm cable pull-down',
        kind: 'isolation',
        equipment: 'High cable',
        cue: 'Trains the long head\'s shoulder-extension role with the elbow locked.',
        motion: 'Shoulder extension',
      },
      {
        name: 'Overhead triceps stretch',
        kind: 'stretch',
        equipment: 'None',
        cue: 'Elbow bent fully overhead, gently pull with the other hand — the only way to stretch the long head across both joints.',
        motion: 'Shoulder flexion + elbow flexion',
      },
    ],
    antagonists: ['l_biceps_long', 'l_brachialis'],
    synergists: ['l_triceps_lateral', 'l_triceps_medial', 'l_anconeus'],
    clinical:
      'Only the long head crosses the shoulder, which is why overhead work is essential for full triceps development and why it is the head most often left underdeveloped by pressing alone.',
  },
  {
    id: 'l_triceps_lateral',
    name: 'Triceps brachii — lateral head',
    latin: 'Musculus triceps brachii, caput laterale',
    side: 'left',
    group: 'Triceps brachii',
    region: 'arm',
    layer: 1,
    girth: 0.018,
    path: [
      p('l_shoulder', [0.201, 1.3, -0.02]),
      via('l_shoulder', [0.215, 1.19, -0.028]),
      p('l_elbow', [0.208, 1.1, -0.03]),
    ],
    originDesc: 'Posterior humerus above and lateral to the radial groove',
    insertionDesc: 'Olecranon via the common triceps tendon',
    actions: [{ joint: 'l_elbow', motion: 'extension', role: 'prime' }],
    innervation: 'Radial nerve (C6–C8)',
    nerve: 'l_radial',
    bloodSupply: 'Profunda brachii artery',
    palpation: 'The lateral "horseshoe" at the back of the arm.',
    exercises: [
      {
        name: 'Rope or bar pushdown',
        kind: 'isolation',
        equipment: 'High cable',
        cue: 'Arms at the sides so the long head is slack — the lateral head takes the load. Spread the rope at the bottom.',
        motion: 'Elbow extension',
      },
      {
        name: 'Close-grip bench press',
        kind: 'compound',
        equipment: 'Barbell',
        cue: 'Hands shoulder-width, elbows tucked. Heavy loading for the whole triceps with a lateral-head bias.',
        motion: 'Elbow extension + shoulder flexion',
      },
      {
        name: 'Dip (upright torso)',
        kind: 'compound',
        equipment: 'Parallel bars',
        cue: 'Stay vertical and keep the elbows in — leaning forward hands the work to the chest.',
        motion: 'Elbow extension',
      },
    ],
    antagonists: ['l_biceps_long', 'l_brachialis', 'l_brachioradialis'],
    synergists: ['l_triceps_long', 'l_triceps_medial'],
  },
  {
    id: 'l_triceps_medial',
    name: 'Triceps brachii — medial head',
    latin: 'Musculus triceps brachii, caput mediale',
    side: 'left',
    group: 'Triceps brachii',
    region: 'arm',
    layer: 3,
    girth: 0.015,
    path: [
      p('l_shoulder', [0.186, 1.22, -0.022]),
      p('l_elbow', [0.203, 1.098, -0.028]),
    ],
    originDesc: 'Posterior humerus below the radial groove, the whole distal half',
    insertionDesc: 'Olecranon via the common triceps tendon and directly into the capsule',
    actions: [{ joint: 'l_elbow', motion: 'extension', role: 'prime' }],
    innervation: 'Radial nerve (C6–C8), plus the ulnar nerve to part of it',
    nerve: 'l_radial',
    bloodSupply: 'Profunda brachii and superior ulnar collateral arteries',
    exercises: [
      {
        name: 'Reverse-grip (supinated) pushdown',
        kind: 'isolation',
        equipment: 'Cable, single handle',
        cue: 'The supinated grip is often reported to bias the medial head; keep the elbow pinned.',
        motion: 'Elbow extension',
      },
      {
        name: 'Bench dip / kickback with full lockout',
        kind: 'isolation',
        equipment: 'Bench or dumbbell',
        cue: 'The medial head does most of the work in the last 20° of extension, so full lockout matters.',
        motion: 'Elbow extension (terminal range)',
      },
    ],
    antagonists: ['l_biceps_short', 'l_brachialis'],
    synergists: ['l_triceps_long', 'l_triceps_lateral', 'l_anconeus'],
    clinical:
      'The workhorse for low-force elbow extension and the head most active in fine positioning tasks.',
  },
  {
    id: 'l_anconeus',
    name: 'Anconeus',
    latin: 'Musculus anconeus',
    side: 'left',
    group: 'Elbow extensors',
    region: 'forearm',
    layer: 3,
    girth: 0.008,
    path: [
      p('l_shoulder', [0.232, 1.09, -0.022]),
      p('l_elbow', [0.207, 1.055, -0.022]),
    ],
    originDesc: 'Posterior surface of the lateral epicondyle of the humerus',
    insertionDesc: 'Lateral olecranon and posterior proximal ulna',
    actions: [
      { joint: 'l_elbow', motion: 'extension', role: 'assist' },
      { joint: 'l_radioulnar', motion: 'pronation', role: 'stabilise' },
    ],
    innervation: 'Radial nerve (C7, C8)',
    nerve: 'l_radial',
    bloodSupply: 'Middle collateral artery',
    exercises: [
      {
        name: 'Cable pushdown to full lockout',
        kind: 'isolation',
        equipment: 'Cable',
        cue: 'Anconeus fires hardest in terminal extension; a hard squeeze at the bottom is all you can really do for it.',
        motion: 'Elbow extension',
      },
    ],
    synergists: ['l_triceps_medial'],
    clinical:
      'Stabilises the ulna during pronation and supination; often released or split as the surgical approach to the radial head.',
  },
  // ================================================================ FOREARM: rotators
  {
    id: 'l_brachioradialis',
    name: 'Brachioradialis',
    latin: 'Musculus brachioradialis',
    side: 'left',
    group: 'Forearm extensors (mobile wad)',
    region: 'forearm',
    layer: 1,
    girth: 0.014,
    path: [
      p('l_shoulder', [0.228, 1.13, -0.004]),
      via('l_elbow', [0.238, 1.02, 0.009]),
      p('l_radioulnar', [0.238, 0.845, 0.009]),
    ],
    originDesc: 'Proximal two-thirds of the lateral supracondylar ridge of the humerus',
    insertionDesc: 'Lateral surface of the distal radius above the styloid',
    actions: [
      { joint: 'l_elbow', motion: 'flexion', role: 'prime' },
      { joint: 'l_radioulnar', motion: 'pronation', role: 'assist' },
      { joint: 'l_radioulnar', motion: 'supination', role: 'assist' },
    ],
    innervation: 'Radial nerve (C5, C6) — an extensor-compartment muscle that flexes the elbow',
    nerve: 'l_radial',
    bloodSupply: 'Radial recurrent artery',
    palpation: 'The prominent ridge on the lateral forearm when you flex the elbow with the thumb up.',
    exercises: [
      {
        name: 'Hammer curl',
        kind: 'isolation',
        equipment: 'Dumbbells',
        cue: 'Mid-prone grip is brachioradialis\' strongest position — it is most efficient midway between pronation and supination.',
        motion: 'Elbow flexion in neutral',
      },
      {
        name: 'Reverse curl',
        kind: 'isolation',
        equipment: 'Barbell or EZ bar',
        cue: 'Pronated grip removes the biceps\' advantage; brachioradialis and the wrist extensors take over.',
        motion: 'Elbow flexion pronated',
      },
      {
        name: 'Zottman curl',
        kind: 'isolation',
        equipment: 'Dumbbells',
        cue: 'Supinated up, pronated down — the eccentric loads brachioradialis and the extensors hard.',
        motion: 'Elbow flexion with rotation',
      },
    ],
    antagonists: ['l_triceps_lateral', 'l_anconeus'],
    synergists: ['l_brachialis', 'l_biceps_long'],
    clinical:
      'Its unusual dual action (it rotates the forearm toward mid-prone from either extreme) makes it a useful clue to radial nerve function above the elbow.',
  },
  {
    id: 'l_pronator_teres',
    name: 'Pronator teres',
    latin: 'Musculus pronator teres',
    side: 'left',
    group: 'Forearm flexors',
    region: 'forearm',
    layer: 1,
    girth: 0.012,
    path: [
      p('l_shoulder', [0.19, 1.088, 0.006]),
      p('l_radioulnar', [0.228, 0.99, 0.012]),
    ],
    originDesc: 'Medial epicondyle of the humerus (common flexor origin) and the coronoid process of the ulna',
    insertionDesc: 'Lateral surface of the mid-shaft of the radius',
    actions: [
      { joint: 'l_radioulnar', motion: 'pronation', role: 'prime' },
      { joint: 'l_elbow', motion: 'flexion', role: 'assist' },
    ],
    innervation: 'Median nerve (C6, C7)',
    nerve: 'l_median',
    bloodSupply: 'Ulnar and radial arteries',
    exercises: [
      {
        name: 'Cable or dumbbell pronation',
        kind: 'isolation',
        equipment: 'Light dumbbell held at one end, or a cable',
        cue: 'Elbow braced at 90° on a bench; rotate the palm from up to down against the load. Bracing the elbow removes shoulder rotation.',
        motion: 'Forearm pronation',
      },
      {
        name: 'Pronated wrist-roller work',
        kind: 'isolation',
        equipment: 'Wrist roller',
        cue: 'Sustained pronation under load; also trains the wrist flexors.',
        motion: 'Forearm pronation',
      },
    ],
    antagonists: ['l_supinator', 'l_biceps_long'],
    synergists: ['l_pronator_quadratus', 'l_flexor_carpi_radialis'],
    clinical:
      'The median nerve passes between its two heads — a site of pronator teres syndrome, giving forearm pain with median symptoms but no night waking (unlike carpal tunnel).',
  },
  {
    id: 'l_supinator',
    name: 'Supinator',
    latin: 'Musculus supinator',
    side: 'left',
    group: 'Forearm extensors',
    region: 'forearm',
    layer: 3,
    girth: 0.01,
    path: [
      p('l_shoulder', [0.232, 1.085, -0.008]),
      via('l_radioulnar', [0.234, 1.05, 0.0]),
      p('l_radioulnar', [0.222, 1.028, 0.013]),
    ],
    originDesc: 'Lateral epicondyle, radial collateral and annular ligaments, and the supinator crest of the ulna',
    insertionDesc: 'Posterior, lateral and anterior surfaces of the proximal third of the radius',
    actions: [{ joint: 'l_radioulnar', motion: 'supination', role: 'prime' }],
    innervation: 'Deep branch of the radial nerve (C5–C7)',
    nerve: 'l_radial',
    bloodSupply: 'Radial recurrent and posterior interosseous arteries',
    exercises: [
      {
        name: 'Dumbbell supination (elbow braced, extended)',
        kind: 'isolation',
        equipment: 'Light dumbbell held off-centre',
        cue: 'With the elbow straight the biceps loses its supination leverage, so supinator has to do the work — the cleanest isolation.',
        motion: 'Forearm supination',
      },
      {
        name: 'Supinated cable curl',
        kind: 'compound',
        equipment: 'Cable',
        cue: 'Trains supinator with biceps; less isolating but heavier.',
        motion: 'Supination + elbow flexion',
      },
    ],
    antagonists: ['l_pronator_teres', 'l_pronator_quadratus'],
    synergists: ['l_biceps_long', 'l_biceps_short'],
    clinical:
      'The posterior interosseous nerve dives through the arcade of Frohse in its proximal edge — entrapment there causes finger-drop with preserved wrist extension and no sensory loss.',
  },
  {
    id: 'l_pronator_quadratus',
    name: 'Pronator quadratus',
    latin: 'Musculus pronator quadratus',
    side: 'left',
    group: 'Forearm flexors',
    region: 'forearm',
    layer: 3,
    girth: 0.008,
    path: [
      p('l_elbow', [0.207, 0.855, 0.009]),
      p('l_radioulnar', [0.235, 0.855, 0.011]),
    ],
    originDesc: 'Distal anterior surface of the ulna',
    insertionDesc: 'Distal anterior surface of the radius',
    actions: [
      { joint: 'l_radioulnar', motion: 'pronation', role: 'prime' },
    ],
    innervation: 'Anterior interosseous branch of the median nerve (C8, T1)',
    nerve: 'l_median',
    bloodSupply: 'Anterior interosseous artery',
    exercises: [
      {
        name: 'Slow resisted pronation, elbow flexed',
        kind: 'isolation',
        equipment: 'Cable or light hammer',
        cue: 'Pronator quadratus initiates pronation and works throughout; pronator teres joins in only against resistance.',
        motion: 'Forearm pronation',
      },
    ],
    antagonists: ['l_supinator'],
    synergists: ['l_pronator_teres'],
    clinical:
      'Also holds the distal radioulnar joint together. It is the deepest muscle of the anterior forearm and is used as a vascularised flap in wrist surgery.',
  },
  // ============================================================ FOREARM: wrist flexors
  {
    id: 'l_flexor_carpi_radialis',
    name: 'Flexor carpi radialis',
    latin: 'Musculus flexor carpi radialis',
    side: 'left',
    group: 'Forearm flexors',
    region: 'forearm',
    layer: 1,
    girth: 0.011,
    path: [
      p('l_shoulder', [0.19, 1.085, 0.009]),
      via('l_elbow', [0.215, 0.96, 0.019]),
      p('l_wrist', [0.228, 0.795, 0.016]),
    ],
    originDesc: 'Medial epicondyle of the humerus via the common flexor tendon',
    insertionDesc: 'Base of the 2nd metacarpal and part of the 3rd',
    actions: [
      { joint: 'l_wrist', motion: 'flexion', role: 'prime' },
      { joint: 'l_wrist', motion: 'radial deviation', role: 'assist' },
      { joint: 'l_elbow', motion: 'flexion', role: 'stabilise' },
    ],
    innervation: 'Median nerve (C6, C7)',
    nerve: 'l_median',
    bloodSupply: 'Ulnar artery',
    palpation: 'Its tendon is the more lateral of the two prominent tendons at the front of the wrist; the radial artery lies just lateral to it.',
    exercises: [
      {
        name: 'Seated barbell wrist curl',
        kind: 'isolation',
        equipment: 'Barbell, bench',
        cue: 'Forearms on the thighs, palms up, let the bar roll to the fingertips then curl it back. Full range beats heavy load here.',
        motion: 'Wrist flexion',
      },
      {
        name: 'Cable wrist curl with radial deviation',
        kind: 'isolation',
        equipment: 'Low cable',
        cue: 'Combine flexion with a thumb-side tilt to match the true line of pull.',
        motion: 'Wrist flexion + radial deviation',
      },
      {
        name: 'Wrist extensor stretch',
        kind: 'stretch',
        equipment: 'None',
        cue: 'Extend the elbow and the wrist, then gently pull the fingers back with the other hand.',
        motion: 'Wrist extension',
      },
    ],
    antagonists: ['l_extensor_carpi_radialis_longus', 'l_extensor_carpi_ulnaris'],
    synergists: ['l_flexor_carpi_ulnaris', 'l_palmaris_longus', 'l_flexor_digitorum_superficialis'],
    clinical:
      'The landmark for palpating the radial pulse and the guide to the median nerve at the wrist.',
  },
  {
    id: 'l_flexor_carpi_ulnaris',
    name: 'Flexor carpi ulnaris',
    latin: 'Musculus flexor carpi ulnaris',
    side: 'left',
    group: 'Forearm flexors',
    region: 'forearm',
    layer: 1,
    girth: 0.011,
    path: [
      p('l_shoulder', [0.192, 1.08, -0.005]),
      via('l_elbow', [0.203, 0.95, 0.01]),
      p('l_wrist', [0.203, 0.795, 0.013]),
    ],
    originDesc: 'Medial epicondyle (common flexor tendon) and posterior border of the ulna',
    insertionDesc: 'Pisiform and hook of the hamate, base of the 5th metacarpal',
    actions: [
      { joint: 'l_wrist', motion: 'flexion', role: 'prime' },
      { joint: 'l_wrist', motion: 'ulnar deviation', role: 'prime' },
    ],
    innervation: 'Ulnar nerve (C7, C8) — one of only two forearm muscles it supplies',
    nerve: 'l_ulnar',
    bloodSupply: 'Ulnar artery',
    exercises: [
      {
        name: 'Ulnar deviation with a hammer or club',
        kind: 'isolation',
        equipment: 'Hammer, club or indian club',
        cue: 'Hold the handle with the head to the little-finger side and tilt the hand toward the ulna. Direct and unmistakable.',
        motion: 'Wrist ulnar deviation',
      },
      {
        name: 'Wrist curl with ulnar bias',
        kind: 'isolation',
        equipment: 'Dumbbell',
        cue: 'Curl the wrist while drifting toward the little finger.',
        motion: 'Wrist flexion + ulnar deviation',
      },
    ],
    antagonists: ['l_extensor_carpi_radialis_longus', 'l_flexor_carpi_radialis'],
    synergists: ['l_extensor_carpi_ulnaris', 'l_flexor_digitorum_profundus'],
    clinical:
      'The ulnar nerve passes between its two heads at the elbow — a site of cubital tunnel syndrome.',
  },
  {
    id: 'l_palmaris_longus',
    name: 'Palmaris longus',
    latin: 'Musculus palmaris longus',
    side: 'left',
    group: 'Forearm flexors',
    region: 'forearm',
    layer: 1,
    girth: 0.007,
    path: [
      p('l_shoulder', [0.193, 1.082, 0.013]),
      via('l_elbow', [0.212, 0.95, 0.023]),
      p('l_wrist', [0.222, 0.775, 0.024]),
    ],
    originDesc: 'Medial epicondyle via the common flexor tendon',
    insertionDesc: 'Palmar aponeurosis and flexor retinaculum',
    actions: [
      { joint: 'l_wrist', motion: 'flexion', role: 'assist' },
    ],
    innervation: 'Median nerve (C7, C8)',
    nerve: 'l_median',
    bloodSupply: 'Ulnar artery',
    exercises: [
      {
        name: 'Wrist curl with cupped palm',
        kind: 'isolation',
        equipment: 'Light dumbbell',
        cue: 'Flex the wrist while cupping the hand — palmaris longus tensions the palmar aponeurosis.',
        motion: 'Wrist flexion',
      },
    ],
    synergists: ['l_flexor_carpi_radialis'],
    clinical:
      'Absent in roughly 14% of people, unilaterally or bilaterally. Expendable, which makes it the go-to tendon graft donor.',
  },
  {
    id: 'l_flexor_digitorum_superficialis',
    name: 'Flexor digitorum superficialis',
    latin: 'Musculus flexor digitorum superficialis',
    side: 'left',
    group: 'Forearm flexors',
    region: 'forearm',
    layer: 2,
    girth: 0.014,
    path: [
      p('l_shoulder', [0.196, 1.078, 0.007]),
      via('l_elbow', [0.215, 0.95, 0.021]),
      via('l_wrist', [0.222, 0.8, 0.015]),
      p('l_fingers', [0.232, 0.685, 0.026]),
    ],
    originDesc: 'Medial epicondyle, coronoid process of the ulna and the anterior border of the radius',
    insertionDesc: 'Sides of the middle phalanges of the four fingers',
    actions: [
      { joint: 'l_pip', motion: 'flexion', role: 'prime' },
      { joint: 'l_mcp', motion: 'flexion', role: 'assist' },
      { joint: 'l_wrist', motion: 'flexion', role: 'assist' },
    ],
    innervation: 'Median nerve (C7–T1)',
    nerve: 'l_median',
    bloodSupply: 'Ulnar and radial arteries',
    exercises: [
      {
        name: 'Towel or gripper crush',
        kind: 'isolation',
        equipment: 'Hand gripper, thick towel',
        cue: 'Crush grip drives the PIP joints; keep the wrist neutral so the wrist flexors do not take over.',
        motion: 'Finger (PIP) flexion',
      },
      {
        name: 'Dead hang from a bar',
        kind: 'activation',
        equipment: 'Pull-up bar',
        cue: 'Sustained isometric finger flexion; add a thicker bar to increase demand.',
        motion: 'Finger flexion (isometric)',
      },
      {
        name: 'FDS isolation test',
        kind: 'manual test',
        equipment: 'None',
        cue: 'Hold the other fingers extended and flex one PIP joint — if it flexes, FDS is intact to that digit.',
        motion: 'Isolated PIP flexion',
      },
    ],
    antagonists: ['l_extensor_digitorum'],
    synergists: ['l_flexor_digitorum_profundus'],
    clinical:
      'Its tendons and the median nerve share the carpal tunnel; swelling here is the anatomical basis of carpal tunnel syndrome.',
  },
  {
    id: 'l_flexor_digitorum_profundus',
    name: 'Flexor digitorum profundus',
    latin: 'Musculus flexor digitorum profundus',
    side: 'left',
    group: 'Forearm flexors',
    region: 'forearm',
    layer: 3,
    girth: 0.013,
    path: [
      p('l_elbow', [0.205, 1.03, 0.013]),
      via('l_elbow', [0.218, 0.86, 0.017]),
      via('l_wrist', [0.223, 0.795, 0.014]),
      p('l_fingers', [0.234, 0.665, 0.023]),
    ],
    originDesc: 'Anterior and medial surfaces of the proximal ulna and the interosseous membrane',
    insertionDesc: 'Palmar bases of the distal phalanges of the four fingers',
    actions: [
      { joint: 'l_pip', motion: 'flexion', role: 'prime' },
      { joint: 'l_mcp', motion: 'flexion', role: 'assist' },
      { joint: 'l_wrist', motion: 'flexion', role: 'assist' },
    ],
    innervation: 'Medial half by the ulnar nerve, lateral half by the anterior interosseous (median) nerve (C8, T1)',
    nerve: 'l_ulnar',
    bloodSupply: 'Ulnar and anterior interosseous arteries',
    exercises: [
      {
        name: 'Fingertip / open-hand hang',
        kind: 'isolation',
        equipment: 'Bar, edge or block',
        cue: 'An open (drag) grip loads the DIP joints and therefore FDP specifically. Build up gradually — tendon tissue adapts slowly.',
        motion: 'DIP flexion',
      },
      {
        name: 'Plate pinch',
        kind: 'isolation',
        equipment: 'Smooth plates',
        cue: 'Pinch two plates together; heavy demand on the deep flexors and thumb.',
        motion: 'Finger flexion (isometric)',
      },
    ],
    antagonists: ['l_extensor_digitorum'],
    synergists: ['l_flexor_digitorum_superficialis', 'l_flexor_carpi_ulnaris'],
    clinical:
      'The only muscle that can flex the DIP joints. Avulsion of its insertion is "jersey finger", from grabbing an opponent\'s shirt.',
  },
  {
    id: 'l_flexor_pollicis_longus',
    name: 'Flexor pollicis longus',
    latin: 'Musculus flexor pollicis longus',
    side: 'left',
    group: 'Forearm flexors',
    region: 'forearm',
    layer: 3,
    girth: 0.009,
    path: [
      p('l_radioulnar', [0.226, 0.97, 0.015]),
      via('l_wrist', [0.235, 0.83, 0.015]),
      p('l_thumb', [0.272, 0.715, 0.032]),
    ],
    originDesc: 'Anterior surface of the middle radius and the interosseous membrane',
    insertionDesc: 'Palmar base of the distal phalanx of the thumb',
    actions: [
      { joint: 'l_thumb_cmc', motion: 'flexion', role: 'prime' },
      { joint: 'l_wrist', motion: 'flexion', role: 'assist' },
    ],
    innervation: 'Anterior interosseous branch of the median nerve (C8, T1)',
    nerve: 'l_median',
    bloodSupply: 'Anterior interosseous artery',
    exercises: [
      {
        name: 'Thumb press against a band',
        kind: 'isolation',
        equipment: 'Light band or putty',
        cue: 'Press the thumb tip into the band, bending only the last joint.',
        motion: 'Thumb IP flexion',
      },
      {
        name: 'Heavy pinch grip',
        kind: 'isolation',
        equipment: 'Plates or a pinch block',
        cue: 'Trains it with the thenar muscles; the thumb is the limiting factor in most pinch tasks.',
        motion: 'Thumb flexion (isometric)',
      },
    ],
    antagonists: ['l_extensor_pollicis_longus'],
    clinical:
      'Loss of thumb IP flexion with weak index DIP flexion localises a lesion to the anterior interosseous nerve.',
  },
  // ========================================================== FOREARM: wrist extensors
  {
    id: 'l_extensor_carpi_radialis_longus',
    name: 'Extensor carpi radialis longus',
    latin: 'Musculus extensor carpi radialis longus',
    side: 'left',
    group: 'Forearm extensors',
    region: 'forearm',
    layer: 1,
    girth: 0.011,
    path: [
      p('l_shoulder', [0.231, 1.115, -0.008]),
      via('l_elbow', [0.24, 0.95, -0.005]),
      p('l_wrist', [0.235, 0.8, -0.012]),
    ],
    originDesc: 'Distal third of the lateral supracondylar ridge of the humerus',
    insertionDesc: 'Dorsal base of the 2nd metacarpal',
    actions: [
      { joint: 'l_wrist', motion: 'extension', role: 'prime' },
      { joint: 'l_wrist', motion: 'radial deviation', role: 'prime' },
      { joint: 'l_elbow', motion: 'flexion', role: 'stabilise' },
    ],
    innervation: 'Radial nerve (C6, C7)',
    nerve: 'l_radial',
    bloodSupply: 'Radial artery',
    exercises: [
      {
        name: 'Reverse wrist curl',
        kind: 'isolation',
        equipment: 'Barbell or dumbbell',
        cue: 'Palms down, forearms supported, lift the back of the hand. Light loads — this group is small and easily irritated.',
        motion: 'Wrist extension',
      },
      {
        name: 'Radial deviation with a hammer',
        kind: 'isolation',
        equipment: 'Hammer',
        cue: 'Head of the hammer on the thumb side; tilt toward the thumb.',
        motion: 'Wrist radial deviation',
      },
      {
        name: 'Reverse curl',
        kind: 'compound',
        equipment: 'Barbell',
        cue: 'The extensors work hard isometrically to hold the pronated wrist steady.',
        motion: 'Wrist extension (isometric)',
      },
    ],
    antagonists: ['l_flexor_carpi_radialis', 'l_flexor_carpi_ulnaris'],
    synergists: ['l_extensor_carpi_radialis_brevis', 'l_extensor_digitorum'],
  },
  {
    id: 'l_extensor_carpi_radialis_brevis',
    name: 'Extensor carpi radialis brevis',
    latin: 'Musculus extensor carpi radialis brevis',
    side: 'left',
    group: 'Forearm extensors',
    region: 'forearm',
    layer: 2,
    girth: 0.01,
    path: [
      p('l_shoulder', [0.234, 1.088, -0.012]),
      via('l_elbow', [0.238, 0.95, -0.008]),
      p('l_wrist', [0.228, 0.8, -0.014]),
    ],
    originDesc: 'Lateral epicondyle of the humerus (common extensor origin)',
    insertionDesc: 'Dorsal base of the 3rd metacarpal',
    actions: [
      { joint: 'l_wrist', motion: 'extension', role: 'prime' },
      { joint: 'l_wrist', motion: 'radial deviation', role: 'assist' },
    ],
    innervation: 'Deep branch of the radial nerve (C7, C8)',
    nerve: 'l_radial',
    bloodSupply: 'Radial artery',
    exercises: [
      {
        name: 'Eccentric wrist extension (Tyler twist)',
        kind: 'isolation',
        equipment: 'FlexBar or light dumbbell',
        cue: 'Slow eccentric loading is the evidence-based treatment for lateral epicondylalgia — this is the tendon involved.',
        motion: 'Wrist extension (eccentric)',
      },
      {
        name: 'Reverse wrist curl',
        kind: 'isolation',
        equipment: 'Barbell',
        cue: 'Keep the elbow extended to lengthen the whole extensor group.',
        motion: 'Wrist extension',
      },
      {
        name: 'Wrist extensor stretch',
        kind: 'stretch',
        equipment: 'None',
        cue: 'Elbow straight, wrist flexed and pronated, gently pull the hand down. Central to tennis-elbow management.',
        motion: 'Wrist flexion',
      },
    ],
    antagonists: ['l_flexor_carpi_radialis'],
    synergists: ['l_extensor_carpi_radialis_longus'],
    clinical:
      'The tendon involved in the overwhelming majority of "tennis elbow" cases — a degenerative tendinopathy, not inflammation.',
  },
  {
    id: 'l_extensor_carpi_ulnaris',
    name: 'Extensor carpi ulnaris',
    latin: 'Musculus extensor carpi ulnaris',
    side: 'left',
    group: 'Forearm extensors',
    region: 'forearm',
    layer: 1,
    girth: 0.01,
    path: [
      p('l_shoulder', [0.23, 1.085, -0.02]),
      via('l_elbow', [0.212, 0.95, -0.014]),
      p('l_wrist', [0.207, 0.8, -0.013]),
    ],
    originDesc: 'Lateral epicondyle (common extensor origin) and the posterior border of the ulna',
    insertionDesc: 'Dorsal base of the 5th metacarpal',
    actions: [
      { joint: 'l_wrist', motion: 'extension', role: 'prime' },
      { joint: 'l_wrist', motion: 'ulnar deviation', role: 'prime' },
    ],
    innervation: 'Deep branch of the radial nerve (C7, C8)',
    nerve: 'l_radial',
    bloodSupply: 'Posterior interosseous artery',
    exercises: [
      {
        name: 'Ulnar deviation, palm down',
        kind: 'isolation',
        equipment: 'Hammer or dumbbell held at one end',
        cue: 'Pronated, tilt toward the little finger — extension plus ulnar deviation is its true line.',
        motion: 'Wrist extension + ulnar deviation',
      },
      {
        name: 'Reverse wrist curl with ulnar drift',
        kind: 'isolation',
        equipment: 'Dumbbell',
        cue: 'Combine extension with a little-finger bias.',
        motion: 'Wrist extension',
      },
    ],
    antagonists: ['l_flexor_carpi_ulnaris', 'l_flexor_carpi_radialis'],
    synergists: ['l_extensor_digitorum'],
    clinical:
      'Its subsheath at the ulnar head is a common site of tendinopathy and subluxation in racquet and stick sports.',
  },
  {
    id: 'l_extensor_digitorum',
    name: 'Extensor digitorum',
    latin: 'Musculus extensor digitorum',
    side: 'left',
    group: 'Forearm extensors',
    region: 'forearm',
    layer: 1,
    girth: 0.012,
    path: [
      p('l_shoulder', [0.23, 1.082, -0.016]),
      via('l_elbow', [0.225, 0.95, -0.014]),
      via('l_wrist', [0.224, 0.8, -0.014]),
      p('l_fingers', [0.23, 0.675, -0.016]),
    ],
    originDesc: 'Lateral epicondyle via the common extensor tendon',
    insertionDesc: 'Extensor expansions (hoods) of the four fingers, into the middle and distal phalanges',
    actions: [
      { joint: 'l_mcp', motion: 'extension', role: 'prime' },
      { joint: 'l_pip', motion: 'extension', role: 'assist' },
      { joint: 'l_wrist', motion: 'extension', role: 'assist' },
    ],
    innervation: 'Posterior interosseous branch of the radial nerve (C7, C8)',
    nerve: 'l_radial',
    bloodSupply: 'Posterior interosseous artery',
    exercises: [
      {
        name: 'Finger extension against a band',
        kind: 'isolation',
        equipment: 'Rubber band or extensor trainer',
        cue: 'Loop a band around the fingers and open the hand. Almost always neglected relative to grip work — worth balancing.',
        motion: 'Finger extension',
      },
      {
        name: 'Reverse wrist curl (assisted role)',
        kind: 'compound',
        equipment: 'Barbell',
        cue: 'Contributes to wrist extension when the fingers are relaxed.',
        motion: 'Wrist extension',
      },
    ],
    antagonists: ['l_flexor_digitorum_superficialis', 'l_flexor_digitorum_profundus'],
    synergists: ['l_extensor_carpi_ulnaris'],
    clinical:
      'Avulsion of the terminal slip at the DIP joint causes mallet finger; disruption of the central slip at the PIP joint causes a boutonnière deformity.',
  },
  {
    id: 'l_abductor_pollicis_longus',
    name: 'Abductor pollicis longus',
    latin: 'Musculus abductor pollicis longus',
    side: 'left',
    group: 'Deep forearm extensors',
    region: 'forearm',
    layer: 3,
    girth: 0.008,
    path: [
      p('l_elbow', [0.22, 0.945, -0.016]),
      via('l_radioulnar', [0.238, 0.845, -0.005]),
      p('l_thumb', [0.256, 0.79, 0.008]),
    ],
    originDesc: 'Posterior surfaces of the ulna, radius and interosseous membrane',
    insertionDesc: 'Base of the 1st metacarpal (radial side)',
    actions: [
      { joint: 'l_thumb_cmc', motion: 'abduction', role: 'prime' },
      { joint: 'l_thumb_cmc', motion: 'extension', role: 'assist' },
      { joint: 'l_wrist', motion: 'radial deviation', role: 'assist' },
    ],
    innervation: 'Posterior interosseous branch of the radial nerve (C7, C8)',
    nerve: 'l_radial',
    bloodSupply: 'Posterior interosseous artery',
    exercises: [
      {
        name: 'Thumb abduction against a band',
        kind: 'isolation',
        equipment: 'Light band',
        cue: 'Hand flat on a table, move the thumb away in the plane of the palm.',
        motion: 'Thumb abduction',
      },
      {
        name: 'Radial deviation with hammer',
        kind: 'compound',
        equipment: 'Hammer',
        cue: 'Also loads the wrist extensors; useful for de Quervain rehabilitation once pain settles.',
        motion: 'Radial deviation',
      },
    ],
    clinical:
      'Together with extensor pollicis brevis it occupies the first extensor compartment — the site of de Quervain tenosynovitis, positive on Finkelstein\'s test.',
  },
  {
    id: 'l_extensor_pollicis_longus',
    name: 'Extensor pollicis longus',
    latin: 'Musculus extensor pollicis longus',
    side: 'left',
    group: 'Deep forearm extensors',
    region: 'forearm',
    layer: 3,
    girth: 0.007,
    path: [
      p('l_elbow', [0.212, 0.94, -0.018]),
      via('l_radioulnar', [0.236, 0.83, -0.006]),
      p('l_thumb', [0.275, 0.72, 0.018]),
    ],
    originDesc: 'Posterior surface of the middle ulna and the interosseous membrane',
    insertionDesc: 'Dorsal base of the distal phalanx of the thumb',
    actions: [
      { joint: 'l_thumb_cmc', motion: 'extension', role: 'prime' },
      { joint: 'l_wrist', motion: 'extension', role: 'assist' },
    ],
    innervation: 'Posterior interosseous branch of the radial nerve (C7, C8)',
    nerve: 'l_radial',
    bloodSupply: 'Posterior interosseous artery',
    exercises: [
      {
        name: 'Thumb "hitch-hike" extension',
        kind: 'isolation',
        equipment: 'Band or none',
        cue: 'Make a fist, then lift the thumb up and back as far as it will go.',
        motion: 'Thumb extension',
      },
    ],
    antagonists: ['l_flexor_pollicis_longus'],
    clinical:
      'Its tendon defines the ulnar border of the anatomical snuffbox and can rupture after a distal radius fracture as it hooks around Lister\'s tubercle.',
  },
  // ================================================================= HAND intrinsics
  {
    id: 'l_thenar',
    name: 'Thenar group (abductor pollicis brevis, opponens, flexor pollicis brevis)',
    latin: 'Musculi thenares',
    side: 'left',
    group: 'Hand intrinsics',
    region: 'hand',
    layer: 2,
    girth: 0.012,
    path: [
      p('l_wrist', [0.232, 0.8, 0.02]),
      p('l_thumb', [0.265, 0.755, 0.028]),
    ],
    originDesc: 'Flexor retinaculum, scaphoid and trapezium',
    insertionDesc: 'Proximal phalanx and 1st metacarpal of the thumb',
    actions: [
      { joint: 'l_thumb_cmc', motion: 'abduction', role: 'prime' },
      { joint: 'l_thumb_cmc', motion: 'opposition', role: 'prime' },
      { joint: 'l_thumb_cmc', motion: 'flexion', role: 'assist' },
    ],
    innervation: 'Recurrent branch of the median nerve (C8, T1)',
    nerve: 'l_median',
    bloodSupply: 'Superficial palmar arch, princeps pollicis artery',
    palpation: 'The fleshy ball at the base of the thumb.',
    exercises: [
      {
        name: 'Thumb opposition against putty',
        kind: 'isolation',
        equipment: 'Therapy putty',
        cue: 'Press the thumb pad to each fingertip in turn — the movement that defines the human hand.',
        motion: 'Thumb opposition',
      },
      {
        name: 'Pinch grip hold',
        kind: 'isolation',
        equipment: 'Plates or pinch block',
        cue: 'Loaded isometric opposition; a strong predictor of overall hand function.',
        motion: 'Thumb opposition (isometric)',
      },
    ],
    clinical:
      'Thenar wasting with loss of opposition is the hallmark of advanced carpal tunnel syndrome — the recurrent motor branch is the most vulnerable part of the median nerve.',
  },
  {
    id: 'l_interossei',
    name: 'Interossei and lumbricals',
    latin: 'Musculi interossei et lumbricales',
    side: 'left',
    group: 'Hand intrinsics',
    region: 'hand',
    layer: 3,
    girth: 0.008,
    path: [
      p('l_wrist', [0.24, 0.765, -0.004]),
      p('l_fingers', [0.238, 0.71, 0.0]),
    ],
    originDesc: 'Shafts of the metacarpals (interossei) and the FDP tendons (lumbricals)',
    insertionDesc: 'Extensor expansions and the bases of the proximal phalanges',
    actions: [
      { joint: 'l_mcp', motion: 'abduction', role: 'prime' },
      { joint: 'l_mcp', motion: 'flexion', role: 'assist' },
      { joint: 'l_pip', motion: 'extension', role: 'prime' },
    ],
    innervation: 'Deep branch of the ulnar nerve (C8, T1); the two radial lumbricals by the median nerve',
    nerve: 'l_ulnar',
    bloodSupply: 'Deep palmar arch',
    exercises: [
      {
        name: 'Finger abduction against a band',
        kind: 'isolation',
        equipment: 'Small band or rubber ring',
        cue: 'Spread the fingers against resistance — dorsal interossei abduct ("DAB").',
        motion: 'Finger abduction',
      },
      {
        name: 'Intrinsic-plus ("table-top") hold',
        kind: 'activation',
        equipment: 'None',
        cue: 'MCPs at 90° with the IP joints straight. Tests and trains the lumbricals and interossei together.',
        motion: 'MCP flexion with IP extension',
      },
      {
        name: 'Froment\'s sign',
        kind: 'manual test',
        equipment: 'Sheet of paper',
        cue: 'Pinch paper between thumb and index; thumb IP flexion substituting for adductor pollicis indicates ulnar palsy.',
        motion: 'Thumb adduction',
      },
    ],
    clinical:
      'Ulnar nerve palsy produces the claw hand: the interossei can no longer flex the MCPs or extend the IPs, so extensor digitorum and the long flexors act unopposed.',
  },
];
