/**
 * Peripheral nerves and plexuses. Paths are anchored to rig nodes exactly like muscles,
 * so nerves travel with the pose and you can see how a course changes when a limb moves.
 */

import { p, via } from './muscleHelpers';
import type { NerveDef, Vec3 } from './types';

const swap = (id: string) => (id.startsWith('l_') ? `r_${id.slice(2)}` : id);

const LEFT_NERVES: NerveDef[] = [
  // ============================================================== BRACHIAL PLEXUS
  {
    id: 'l_brachial_plexus',
    name: 'Brachial plexus',
    latin: 'Plexus brachialis',
    side: 'left',
    roots: 'C5–T1',
    kind: 'plexus',
    radius: 0.005,
    path: [
      p('neck', [0.018, 1.474, -0.028]),
      via('neck', [0.058, 1.44, -0.008]),
      via('chest', [0.108, 1.398, 0.022]),
      p('l_scapula', [0.158, 1.358, 0.02]),
    ],
    course:
      'Roots emerge between the anterior and middle scalenes, unite into upper, middle and lower trunks over the first rib, split into anterior and posterior divisions behind the clavicle, form the lateral, posterior and medial cords around the axillary artery, and finally give the five terminal branches.',
    motorSupply: ['All muscles of the upper limb and shoulder girdle except trapezius'],
    sensorySupply: 'The whole upper limb except the skin over the shoulder cap (supraclavicular nerves, C3–C4)',
    muscles: [],
    clinical:
      'Upper trunk (C5–C6) injury from a shoulder-depressing force gives Erb\'s palsy — the "waiter\'s tip" posture. Lower trunk (C8–T1) traction gives Klumpke\'s palsy with a claw hand and possibly Horner\'s syndrome.',
  },
  {
    id: 'l_axillary',
    name: 'Axillary nerve',
    latin: 'Nervus axillaris',
    side: 'left',
    roots: 'C5–C6',
    plexus: 'Brachial plexus, posterior cord',
    kind: 'mixed',
    radius: 0.0028,
    path: [
      p('l_scapula', [0.16, 1.372, 0.014]),
      via('l_shoulder', [0.172, 1.376, -0.022]),
      p('l_shoulder', [0.202, 1.31, -0.02]),
    ],
    course:
      'Leaves the posterior cord, passes through the quadrangular space with the posterior circumflex humeral artery, and wraps around the surgical neck of the humerus deep to the deltoid.',
    motorSupply: ['Deltoid (all three heads)', 'Teres minor'],
    sensorySupply: 'Skin over the lower deltoid — the "regimental badge" area',
    muscles: ['l_deltoid_anterior', 'l_deltoid_middle', 'l_deltoid_posterior', 'l_teres_minor'],
    clinical:
      'Injured in anterior shoulder dislocation and surgical-neck fractures. Always test sensation over the regimental badge patch before and after reducing a dislocated shoulder.',
  },
  {
    id: 'l_musculocutaneous',
    name: 'Musculocutaneous nerve',
    latin: 'Nervus musculocutaneus',
    side: 'left',
    roots: 'C5–C7',
    plexus: 'Brachial plexus, lateral cord',
    kind: 'mixed',
    radius: 0.0026,
    path: [
      p('l_scapula', [0.158, 1.36, 0.022]),
      via('l_shoulder', [0.185, 1.26, 0.022]),
      p('l_shoulder', [0.212, 1.12, 0.018]),
    ],
    course:
      'Pierces coracobrachialis, then runs between biceps brachii and brachialis before emerging lateral to the biceps tendon as the lateral cutaneous nerve of the forearm.',
    motorSupply: ['Coracobrachialis', 'Biceps brachii', 'Brachialis'],
    sensorySupply: 'Lateral forearm',
    muscles: ['l_biceps_long', 'l_biceps_short', 'l_brachialis', 'l_coracobrachialis'],
    clinical:
      'Rarely injured in isolation. When it is, elbow flexion is weak but not lost — brachioradialis (radial nerve) still works.',
  },
  {
    id: 'l_median',
    name: 'Median nerve',
    latin: 'Nervus medianus',
    side: 'left',
    roots: 'C6–T1',
    plexus: 'Brachial plexus, lateral and medial cords',
    kind: 'mixed',
    radius: 0.003,
    path: [
      p('l_scapula', [0.158, 1.35, 0.02]),
      via('l_shoulder', [0.186, 1.2, 0.016]),
      via('l_elbow', [0.2, 1.08, 0.013]),
      via('l_elbow', [0.215, 0.9, 0.016]),
      via('l_wrist', [0.222, 0.8, 0.019]),
      p('l_fingers', [0.23, 0.72, 0.021]),
    ],
    course:
      'Descends the medial arm with the brachial artery giving no branches, crosses the cubital fossa, passes between the two heads of pronator teres, runs between FDS and FDP, then enters the hand through the carpal tunnel.',
    motorSupply: [
      'All anterior forearm muscles except flexor carpi ulnaris and the medial half of FDP',
      'Thenar muscles',
      'Lateral two lumbricals',
    ],
    sensorySupply: 'Palmar surface of the lateral three and a half digits and the corresponding palm',
    muscles: [
      'l_pronator_teres',
      'l_pronator_quadratus',
      'l_flexor_carpi_radialis',
      'l_palmaris_longus',
      'l_flexor_digitorum_superficialis',
      'l_flexor_pollicis_longus',
      'l_thenar',
    ],
    clinical:
      'Carpal tunnel syndrome is the commonest entrapment neuropathy: night-time tingling in the lateral three and a half digits, sparing the palm because the palmar cutaneous branch passes *over* the retinaculum. Advanced cases show thenar wasting.',
  },
  {
    id: 'l_ulnar',
    name: 'Ulnar nerve',
    latin: 'Nervus ulnaris',
    side: 'left',
    roots: 'C8–T1',
    plexus: 'Brachial plexus, medial cord',
    kind: 'mixed',
    radius: 0.0028,
    path: [
      p('l_scapula', [0.158, 1.345, 0.01]),
      via('l_shoulder', [0.18, 1.2, 0.0]),
      via('l_shoulder', [0.19, 1.095, -0.018]),
      via('l_elbow', [0.2, 0.92, 0.008]),
      via('l_wrist', [0.205, 0.8, 0.013]),
      p('l_fingers', [0.215, 0.72, 0.013]),
    ],
    course:
      'Runs down the medial arm, passes behind the medial epicondyle in the cubital tunnel, travels with flexor carpi ulnaris, and enters the hand superficial to the flexor retinaculum through Guyon\'s canal.',
    motorSupply: [
      'Flexor carpi ulnaris',
      'Medial half of flexor digitorum profundus',
      'All intrinsic hand muscles except the thenar group and the lateral two lumbricals',
    ],
    sensorySupply: 'Medial one and a half digits, palmar and dorsal',
    muscles: ['l_flexor_carpi_ulnaris', 'l_flexor_digitorum_profundus', 'l_interossei'],
    clinical:
      'Compression at the cubital tunnel is second only to carpal tunnel in frequency. The ulnar paradox: a *distal* lesion causes more obvious clawing than a proximal one, because the proximal lesion also denervates FDP and so weakens the very flexion that produces the claw.',
  },
  {
    id: 'l_radial',
    name: 'Radial nerve',
    latin: 'Nervus radialis',
    side: 'left',
    roots: 'C5–T1',
    plexus: 'Brachial plexus, posterior cord',
    kind: 'mixed',
    radius: 0.003,
    path: [
      p('l_scapula', [0.164, 1.35, -0.006]),
      via('l_shoulder', [0.19, 1.24, -0.026]),
      via('l_shoulder', [0.226, 1.12, -0.004]),
      via('l_elbow', [0.235, 1.02, -0.004]),
      p('l_radioulnar', [0.235, 0.83, -0.012]),
    ],
    course:
      'The largest branch of the plexus. Spirals around the posterior humerus in the radial groove, pierces the lateral intermuscular septum, and divides at the elbow into a superficial sensory branch and the deep (posterior interosseous) motor branch which passes through supinator.',
    motorSupply: [
      'Triceps brachii and anconeus',
      'Brachioradialis and extensor carpi radialis longus',
      'All posterior forearm (extensor) muscles via the posterior interosseous nerve',
    ],
    sensorySupply: 'Posterior arm and forearm, and the dorsal lateral hand',
    muscles: [
      'l_triceps_long',
      'l_triceps_lateral',
      'l_triceps_medial',
      'l_anconeus',
      'l_brachioradialis',
      'l_supinator',
      'l_extensor_carpi_radialis_longus',
      'l_extensor_carpi_radialis_brevis',
      'l_extensor_carpi_ulnaris',
      'l_extensor_digitorum',
      'l_abductor_pollicis_longus',
      'l_extensor_pollicis_longus',
    ],
    clinical:
      'Mid-shaft humeral fracture or "Saturday night palsy" (compression against a chair back) causes wrist drop with triceps spared, because the triceps branches leave above the groove. A posterior interosseous lesion gives finger drop with intact wrist extension and no sensory loss.',
  },
  {
    id: 'l_suprascapular',
    name: 'Suprascapular nerve',
    latin: 'Nervus suprascapularis',
    side: 'left',
    roots: 'C5–C6',
    plexus: 'Brachial plexus, upper trunk',
    kind: 'motor',
    radius: 0.002,
    path: [
      p('l_scapula', [0.09, 1.412, -0.03]),
      via('l_scapula', [0.085, 1.386, -0.055]),
      p('l_scapula', [0.09, 1.31, -0.062]),
    ],
    course: 'Passes through the suprascapular notch beneath the superior transverse scapular ligament, then round the spinoglenoid notch.',
    motorSupply: ['Supraspinatus', 'Infraspinatus'],
    sensorySupply: 'Glenohumeral and acromioclavicular joints (no skin)',
    muscles: ['l_supraspinatus', 'l_infraspinatus'],
    clinical:
      'Entrapment at the spinoglenoid notch (often from a paralabral cyst in volleyball players) wastes only infraspinatus; entrapment at the suprascapular notch affects both muscles.',
  },
  {
    id: 'l_long_thoracic',
    name: 'Long thoracic nerve',
    latin: 'Nervus thoracicus longus',
    side: 'left',
    roots: 'C5–C7',
    plexus: 'Brachial plexus, roots',
    kind: 'motor',
    radius: 0.002,
    path: [
      p('neck', [0.04, 1.442, -0.012]),
      via('chest', [0.072, 1.35, 0.03]),
      p('thorax', [0.088, 1.22, 0.045]),
    ],
    course: 'Descends on the superficial surface of serratus anterior along the lateral chest wall — exposed and unprotected.',
    motorSupply: ['Serratus anterior'],
    sensorySupply: 'None',
    muscles: ['l_serratus_anterior'],
    clinical:
      'Its superficial course makes it vulnerable to blunt trauma, carrying heavy backpacks, and axillary surgery. Injury produces winging of the scapula and loss of full overhead reach.',
  },
  {
    id: 'l_thoracodorsal',
    name: 'Thoracodorsal nerve',
    latin: 'Nervus thoracodorsalis',
    side: 'left',
    roots: 'C6–C8',
    plexus: 'Brachial plexus, posterior cord',
    kind: 'motor',
    radius: 0.002,
    path: [
      p('l_scapula', [0.148, 1.35, 0.006]),
      p('thorax', [0.11, 1.28, -0.04]),
    ],
    course: 'Runs down the posterior axillary wall on the deep surface of latissimus dorsi with the thoracodorsal artery.',
    motorSupply: ['Latissimus dorsi'],
    sensorySupply: 'None',
    muscles: ['l_lat_dorsi'],
    clinical: 'At risk during axillary node clearance in breast surgery; the resulting latissimus weakness impairs pushing up from a chair.',
  },
  {
    id: 'l_dorsal_scapular',
    name: 'Dorsal scapular nerve',
    latin: 'Nervus dorsalis scapulae',
    side: 'left',
    roots: 'C4–C5',
    plexus: 'Brachial plexus, roots',
    kind: 'motor',
    radius: 0.0018,
    path: [
      p('neck', [0.03, 1.462, -0.022]),
      p('l_scapula', [0.05, 1.34, -0.062]),
    ],
    course: 'Pierces the middle scalene and descends deep to levator scapulae along the medial border of the scapula.',
    motorSupply: ['Rhomboid major and minor', 'Levator scapulae (partly)'],
    sensorySupply: 'None',
    muscles: ['l_rhomboid_major', 'l_rhomboid_minor', 'l_levator_scapulae'],
    clinical:
      'Injury gives a subtle lateral scapular translation — the scapula sits further from the spine, the mirror image of long thoracic palsy.',
  },
  {
    id: 'l_accessory',
    name: 'Accessory nerve (CN XI)',
    latin: 'Nervus accessorius',
    side: 'left',
    roots: 'Cranial root plus spinal roots C1–C5',
    kind: 'motor',
    radius: 0.0022,
    path: [
      p('head', [0.046, 1.53, -0.03]),
      via('neck', [0.042, 1.44, -0.05]),
      p('l_scapula', [0.09, 1.38, -0.055]),
    ],
    course:
      'Leaves the skull through the jugular foramen, crosses the posterior triangle of the neck superficially between sternocleidomastoid and trapezius.',
    motorSupply: ['Sternocleidomastoid', 'Trapezius (all parts)'],
    sensorySupply: 'None',
    muscles: ['l_sternocleidomastoid', 'l_trapezius_upper', 'l_trapezius_middle', 'l_trapezius_lower'],
    clinical:
      'Its superficial course in the posterior triangle makes it the classic iatrogenic injury of lymph node biopsy — producing a drooping shoulder, inability to shrug and painful scapular winging.',
  },
  {
    id: 'l_pectoral',
    name: 'Medial and lateral pectoral nerves',
    latin: 'Nervi pectorales',
    side: 'left',
    roots: 'C5–T1',
    plexus: 'Brachial plexus, lateral and medial cords',
    kind: 'motor',
    radius: 0.0018,
    path: [
      p('chest', [0.1, 1.39, 0.04]),
      p('chest', [0.08, 1.32, 0.066]),
    ],
    course: 'Pass forward to the deep surface of the pectoral muscles; the medial nerve pierces pectoralis minor.',
    motorSupply: ['Pectoralis major', 'Pectoralis minor'],
    sensorySupply: 'None',
    muscles: ['l_pec_major_clavicular', 'l_pec_major_sternal', 'l_pec_minor'],
    clinical:
      'Confusingly named for the cords they arise from, not their position — the *lateral* pectoral nerve lies medial to the *medial* one.',
  },
  {
    id: 'l_subscapular',
    name: 'Upper and lower subscapular nerves',
    latin: 'Nervi subscapulares',
    side: 'left',
    roots: 'C5–C6',
    plexus: 'Brachial plexus, posterior cord',
    kind: 'motor',
    radius: 0.0018,
    path: [
      p('l_scapula', [0.13, 1.35, 0.01]),
      p('l_scapula', [0.09, 1.31, -0.03]),
    ],
    course: 'Short branches passing directly backwards into the subscapular fossa.',
    motorSupply: ['Subscapularis', 'Teres major'],
    sensorySupply: 'None',
    muscles: ['l_subscapularis', 'l_teres_major'],
  },
  // ================================================================ TRUNK NERVES
  {
    id: 'l_dorsal_rami',
    name: 'Posterior (dorsal) rami',
    latin: 'Rami posteriores',
    side: 'left',
    roots: 'Every spinal level, C1–S5',
    kind: 'mixed',
    radius: 0.002,
    path: [
      p('lumbar', [0.01, 1.1, -0.038]),
      p('lumbar', [0.045, 1.088, -0.056]),
    ],
    course: 'Each spinal nerve divides immediately into an anterior and a posterior ramus; the posterior ramus turns back to the deep back.',
    motorSupply: ['Erector spinae', 'Transversospinalis group (multifidus, rotatores, semispinalis)', 'Splenius'],
    sensorySupply: 'A strip of skin either side of the midline of the back',
    muscles: ['l_iliocostalis', 'l_longissimus', 'l_spinalis', 'l_multifidus'],
    clinical:
      'The medial branch of the posterior ramus supplies the facet joints — the target of medial branch blocks and radiofrequency denervation for facet-mediated back pain.',
  },
  // ============================================================ LUMBOSACRAL PLEXUS
  {
    id: 'l_lumbar_plexus',
    name: 'Lumbar plexus',
    latin: 'Plexus lumbalis',
    side: 'left',
    roots: 'L1–L4 (with a contribution from T12)',
    kind: 'plexus',
    radius: 0.004,
    path: [
      p('lumbar', [0.022, 1.08, -0.018]),
      via('pelvis', [0.05, 1.0, 0.0]),
      p('pelvis', [0.075, 0.95, 0.03]),
    ],
    course: 'Formed within the substance of psoas major; its branches emerge from the medial and lateral borders of that muscle.',
    motorSupply: ['Anterior and medial thigh muscles', 'Iliopsoas', 'Lower abdominal wall'],
    sensorySupply: 'Lower abdomen, anterior and medial thigh, medial leg',
    muscles: ['l_psoas_major', 'l_iliacus'],
    clinical:
      'Because it lies inside psoas, a psoas haematoma (e.g. on anticoagulants) can compress it and mimic an acute femoral neuropathy.',
  },
  {
    id: 'l_femoral',
    name: 'Femoral nerve',
    latin: 'Nervus femoralis',
    side: 'left',
    roots: 'L2–L4',
    plexus: 'Lumbar plexus',
    kind: 'mixed',
    radius: 0.0032,
    path: [
      p('pelvis', [0.05, 1.0, 0.012]),
      via('pelvis', [0.075, 0.932, 0.052]),
      via('l_hip', [0.09, 0.87, 0.046]),
      p('l_hip', [0.1, 0.72, 0.03]),
    ],
    course:
      'Emerges from the lateral border of psoas, passes deep to the inguinal ligament lateral to the femoral artery, and divides almost immediately into anterior and posterior divisions in the femoral triangle.',
    motorSupply: ['Iliacus', 'Sartorius', 'Pectineus', 'All four quadriceps heads'],
    sensorySupply: 'Anterior thigh and, via the saphenous nerve, the medial leg and foot',
    muscles: [
      'l_iliacus',
      'l_sartorius',
      'l_pectineus',
      'l_rectus_femoris',
      'l_vastus_lateralis',
      'l_vastus_medialis',
      'l_vastus_intermedius',
    ],
    clinical:
      'Injury abolishes the knee jerk and knee extension, making stairs and slopes very difficult. Remember the femoral triangle order from lateral to medial: Nerve, Artery, Vein, Empty space, Lymphatics — "NAVEL".',
  },
  {
    id: 'l_saphenous',
    name: 'Saphenous nerve',
    latin: 'Nervus saphenus',
    side: 'left',
    roots: 'L3–L4',
    plexus: 'Lumbar plexus (femoral nerve)',
    kind: 'sensory',
    radius: 0.0018,
    path: [
      p('l_hip', [0.09, 0.8, 0.03]),
      via('l_knee', [0.078, 0.45, 0.02]),
      p('l_ankle', [0.078, 0.1, 0.02]),
    ],
    course: 'The longest cutaneous branch of the femoral nerve; travels through the adductor canal then subcutaneously with the great saphenous vein.',
    motorSupply: [],
    sensorySupply: 'Medial knee, leg and the medial border of the foot',
    muscles: [],
    clinical:
      'Its infrapatellar branch is often injured in knee arthroscopy and ACL graft harvest, leaving numbness lateral to the incision.',
  },
  {
    id: 'l_obturator',
    name: 'Obturator nerve',
    latin: 'Nervus obturatorius',
    side: 'left',
    roots: 'L2–L4',
    plexus: 'Lumbar plexus',
    kind: 'mixed',
    radius: 0.0026,
    path: [
      p('pelvis', [0.045, 0.99, -0.006]),
      via('pelvis', [0.045, 0.9, 0.042]),
      p('l_hip', [0.06, 0.82, 0.0]),
    ],
    course: 'Emerges from the medial border of psoas, runs along the lateral pelvic wall and leaves through the obturator canal.',
    motorSupply: ['Adductor longus, brevis and magnus (adductor part)', 'Gracilis', 'Obturator externus'],
    sensorySupply: 'Medial thigh',
    muscles: ['l_adductor_longus', 'l_adductor_brevis', 'l_adductor_magnus', 'l_gracilis'],
    clinical:
      'Hip pathology can refer pain to the medial knee along this nerve — a classic trap when a child with a slipped femoral epiphysis presents complaining of knee pain.',
  },
  {
    id: 'l_lateral_femoral_cutaneous',
    name: 'Lateral femoral cutaneous nerve',
    latin: 'Nervus cutaneus femoris lateralis',
    side: 'left',
    roots: 'L2–L3',
    plexus: 'Lumbar plexus',
    kind: 'sensory',
    radius: 0.0016,
    path: [
      p('pelvis', [0.06, 1.0, 0.02]),
      via('pelvis', [0.105, 0.99, 0.07]),
      p('l_hip', [0.12, 0.85, 0.04]),
    ],
    course: 'Crosses iliacus and passes under the inguinal ligament just medial to the ASIS.',
    motorSupply: [],
    sensorySupply: 'Lateral thigh',
    muscles: [],
    clinical:
      'Compression at the inguinal ligament causes meralgia paraesthetica — burning numbness over the lateral thigh, provoked by tight belts, obesity or pregnancy.',
  },
  {
    id: 'l_superior_gluteal',
    name: 'Superior gluteal nerve',
    latin: 'Nervus gluteus superior',
    side: 'left',
    roots: 'L4–S1',
    plexus: 'Sacral plexus',
    kind: 'motor',
    radius: 0.002,
    path: [
      p('pelvis', [0.05, 0.966, -0.04]),
      p('pelvis', [0.095, 0.99, -0.02]),
    ],
    course: 'Leaves the pelvis through the greater sciatic foramen *above* piriformis with the superior gluteal vessels.',
    motorSupply: ['Gluteus medius', 'Gluteus minimus', 'Tensor fasciae latae'],
    sensorySupply: 'None',
    muscles: ['l_gluteus_medius', 'l_gluteus_minimus', 'l_tensor_fasciae_latae'],
    clinical:
      'Injury (e.g. by a badly placed intramuscular injection) produces a positive Trendelenburg sign — the pelvis drops on the *opposite* side during stance on the affected leg.',
  },
  {
    id: 'l_inferior_gluteal',
    name: 'Inferior gluteal nerve',
    latin: 'Nervus gluteus inferior',
    side: 'left',
    roots: 'L5–S2',
    plexus: 'Sacral plexus',
    kind: 'motor',
    radius: 0.002,
    path: [
      p('pelvis', [0.05, 0.945, -0.046]),
      p('pelvis', [0.085, 0.93, -0.05]),
    ],
    course: 'Leaves the pelvis through the greater sciatic foramen *below* piriformis.',
    motorSupply: ['Gluteus maximus'],
    sensorySupply: 'None',
    muscles: ['l_gluteus_maximus'],
    clinical: 'Injury gives difficulty rising from sitting, climbing stairs and running — the powerful hip-extension tasks.',
  },
  {
    id: 'l_sciatic',
    name: 'Sciatic nerve',
    latin: 'Nervus ischiadicus',
    side: 'left',
    roots: 'L4–S3',
    plexus: 'Sacral plexus',
    kind: 'mixed',
    radius: 0.0055,
    path: [
      p('pelvis', [0.045, 0.96, -0.045]),
      via('pelvis', [0.075, 0.925, -0.046]),
      via('l_hip', [0.085, 0.85, -0.045]),
      via('l_hip', [0.095, 0.65, -0.04]),
      p('l_knee', [0.1, 0.5, -0.03]),
    ],
    course:
      'The thickest nerve in the body. Leaves the pelvis below piriformis, descends midway between the ischial tuberosity and the greater trochanter, and divides into tibial and common peroneal nerves at the apex of the popliteal fossa.',
    motorSupply: ['All hamstrings', 'The hamstring part of adductor magnus', 'Everything below the knee'],
    sensorySupply: 'Posterior thigh (via branches) and, through its divisions, the whole leg and foot except the medial strip served by the saphenous nerve',
    muscles: ['l_biceps_femoris_long', 'l_semitendinosus', 'l_semimembranosus', 'l_adductor_magnus'],
    clinical:
      'Radicular pain along its course ("sciatica") is far more often caused by an L5/S1 disc than by the nerve itself. Intramuscular injections go in the upper outer quadrant of the buttock precisely to avoid it.',
  },
  {
    id: 'l_tibial',
    name: 'Tibial nerve',
    latin: 'Nervus tibialis',
    side: 'left',
    roots: 'L4–S3',
    plexus: 'Sacral plexus (sciatic nerve)',
    kind: 'mixed',
    radius: 0.0034,
    path: [
      p('l_knee', [0.1, 0.5, -0.03]),
      via('l_knee', [0.1, 0.3, -0.035]),
      via('l_ankle', [0.085, 0.075, -0.02]),
      p('l_ankle', [0.085, 0.03, 0.02]),
    ],
    course:
      'Runs straight down the popliteal fossa, deep to soleus in the posterior compartment, then behind the medial malleolus in the tarsal tunnel where it divides into medial and lateral plantar nerves.',
    motorSupply: [
      'All posterior compartment leg muscles — gastrocnemius, soleus, plantaris, popliteus, tibialis posterior, FDL, FHL',
      'All intrinsic foot muscles of the sole',
    ],
    sensorySupply: 'Sole of the foot, and the posterolateral leg via the sural nerve',
    muscles: [
      'l_gastrocnemius_medial',
      'l_gastrocnemius_lateral',
      'l_soleus',
      'l_plantaris',
      'l_popliteus',
      'l_tibialis_posterior',
      'l_flexor_digitorum_longus_leg',
      'l_flexor_hallucis_longus',
      'l_foot_intrinsics',
    ],
    clinical:
      'Tarsal tunnel syndrome causes burning sole pain worse at night. Remember the tarsal tunnel contents front to back: "Tom, Dick And Very Nervous Harry" — Tibialis posterior, flexor Digitorum longus, Artery, Vein, Nerve, flexor Hallucis longus.',
  },
  {
    id: 'l_common_peroneal',
    name: 'Common peroneal (fibular) nerve',
    latin: 'Nervus fibularis communis',
    side: 'left',
    roots: 'L4–S2',
    plexus: 'Sacral plexus (sciatic nerve)',
    kind: 'mixed',
    radius: 0.003,
    path: [
      p('l_knee', [0.105, 0.5, -0.03]),
      via('l_knee', [0.126, 0.44, -0.012]),
      p('l_knee', [0.122, 0.4, 0.005]),
    ],
    course: 'Follows the medial border of biceps femoris, then winds subcutaneously around the neck of the fibula before dividing into deep and superficial branches.',
    motorSupply: ['Short head of biceps femoris', 'Then everything via its two divisions'],
    sensorySupply: 'Lateral leg and the dorsum of the foot',
    muscles: ['l_biceps_femoris_short'],
    clinical:
      'The most commonly injured nerve in the lower limb, because at the fibular neck it lies against bone with no padding. A plaster cast, prolonged leg crossing or a fibular neck fracture causes foot drop with sensory loss on the dorsum.',
  },
  {
    id: 'l_deep_peroneal',
    name: 'Deep peroneal (fibular) nerve',
    latin: 'Nervus fibularis profundus',
    side: 'left',
    roots: 'L4–S1',
    plexus: 'Sacral plexus',
    kind: 'mixed',
    radius: 0.0024,
    path: [
      p('l_knee', [0.12, 0.4, 0.008]),
      via('l_knee', [0.108, 0.2, 0.02]),
      via('l_ankle', [0.098, 0.085, 0.03]),
      p('l_ankle', [0.09, 0.03, 0.1]),
    ],
    course: 'Pierces the anterior intermuscular septum and descends on the interosseous membrane with the anterior tibial artery.',
    motorSupply: ['Tibialis anterior', 'Extensor digitorum longus', 'Extensor hallucis longus', 'Peroneus tertius'],
    sensorySupply: 'The web space between the first and second toes only',
    muscles: ['l_tibialis_anterior', 'l_extensor_digitorum_longus', 'l_extensor_hallucis_longus'],
    clinical:
      'Its tiny sensory territory in the first web space is a precise test point — numbness there localises the lesion to this branch.',
  },
  {
    id: 'l_superficial_peroneal',
    name: 'Superficial peroneal (fibular) nerve',
    latin: 'Nervus fibularis superficialis',
    side: 'left',
    roots: 'L4–S1',
    plexus: 'Sacral plexus',
    kind: 'mixed',
    radius: 0.0022,
    path: [
      p('l_knee', [0.124, 0.4, 0.0]),
      via('l_knee', [0.122, 0.2, 0.005]),
      p('l_ankle', [0.112, 0.08, 0.02]),
    ],
    course: 'Descends within the lateral compartment, then pierces the deep fascia in the lower third of the leg to become cutaneous.',
    motorSupply: ['Peroneus longus', 'Peroneus brevis'],
    sensorySupply: 'Most of the dorsum of the foot',
    muscles: ['l_peroneus_longus', 'l_peroneus_brevis'],
    clinical: 'Isolated injury causes weak eversion and a tendency to recurrent inversion sprains.',
  },
  {
    id: 'l_sural',
    name: 'Sural nerve',
    latin: 'Nervus suralis',
    side: 'left',
    roots: 'S1–S2',
    plexus: 'Sacral plexus',
    kind: 'sensory',
    radius: 0.0016,
    path: [
      p('l_knee', [0.1, 0.38, -0.036]),
      via('l_ankle', [0.11, 0.1, -0.03]),
      p('l_ankle', [0.12, 0.05, 0.0]),
    ],
    course: 'Formed from tibial and common peroneal contributions, it runs subcutaneously beside the small saphenous vein behind the lateral malleolus.',
    motorSupply: [],
    sensorySupply: 'Posterolateral leg and the lateral border of the foot',
    muscles: [],
    clinical: 'The standard donor nerve for nerve grafting and the usual site for nerve biopsy, because the sensory loss it leaves is trivial.',
  },
];

const CENTER_NERVES: NerveDef[] = [
  {
    id: 'spinal_cord',
    name: 'Spinal cord and cauda equina',
    latin: 'Medulla spinalis',
    side: 'center',
    roots: 'C1–Co1',
    kind: 'cord',
    radius: 0.009,
    path: [
      p('head', [0, 1.56, -0.028]),
      via('neck', [0, 1.46, -0.03]),
      via('thorax', [0, 1.3, -0.04]),
      via('thorax', [0, 1.16, -0.036]),
      via('lumbar', [0, 1.03, -0.03]),
      p('pelvis', [0, 0.955, -0.04]),
    ],
    course:
      'Runs from the foramen magnum to about L1/L2 in the adult, where it tapers as the conus medullaris; below that the lumbar and sacral roots continue as the cauda equina.',
    motorSupply: ['Everything — via 31 pairs of spinal nerves'],
    sensorySupply: 'The entire body below the head',
    muscles: [],
    clinical:
      'The cord ends at L1/L2, which is why a lumbar puncture is performed at L3/L4 or below — the needle parts the cauda equina rather than piercing the cord. Cauda equina syndrome (saddle anaesthesia, urinary retention, bilateral leg symptoms) is a surgical emergency.',
  },
  {
    id: 'phrenic',
    name: 'Phrenic nerve',
    latin: 'Nervus phrenicus',
    side: 'center',
    roots: 'C3–C5',
    plexus: 'Cervical plexus',
    kind: 'mixed',
    radius: 0.0022,
    path: [
      p('neck', [0.024, 1.45, 0.0]),
      via('chest', [0.03, 1.33, 0.02]),
      p('thorax', [0.02, 1.26, 0.01]),
    ],
    course: 'Descends on the anterior surface of the anterior scalene, enters the thorax and runs over the pericardium to the diaphragm.',
    motorSupply: ['Diaphragm (the sole motor supply)'],
    sensorySupply: 'Central diaphragm, pericardium and mediastinal pleura',
    muscles: ['diaphragm'],
    clinical:
      '"C3, 4, 5 keeps the diaphragm alive." Irritation of the diaphragm refers pain to the shoulder tip, because C3–C5 also supply that skin — the reason a ruptured spleen can present as left shoulder pain.',
  },
  {
    id: 'intercostal',
    name: 'Intercostal nerves',
    latin: 'Nervi intercostales',
    side: 'center',
    roots: 'T1–T11 (plus the subcostal nerve, T12)',
    kind: 'mixed',
    radius: 0.002,
    path: [
      p('thorax', [0.02, 1.28, -0.05]),
      via('thorax', [0.062, 1.262, 0.0]),
      p('thorax', [0.05, 1.24, 0.06]),
    ],
    course: 'The anterior rami of T1–T11 run in the costal groove on the lower border of each rib between the internal and innermost intercostal layers.',
    motorSupply: ['Intercostal muscles', 'Anterolateral abdominal wall (T7–T12)'],
    sensorySupply: 'Chest and abdominal wall skin in a segmental (dermatomal) pattern',
    muscles: ['l_intercostals', 'r_intercostals', 'l_rectus_abdominis', 'r_rectus_abdominis', 'l_external_oblique', 'r_external_oblique'],
    clinical:
      'The intercostal bundle sits in the groove under each rib — chest drains and needles go over the top of the rib below to avoid it. Shingles follows a single intercostal dermatome.',
  },
  {
    id: 'pudendal',
    name: 'Pudendal nerve',
    latin: 'Nervus pudendus',
    side: 'center',
    roots: 'S2–S4',
    plexus: 'Sacral plexus',
    kind: 'mixed',
    radius: 0.0022,
    path: [
      p('pelvis', [0.036, 0.9, -0.045]),
      via('pelvis', [0.0, 0.868, 0.005]),
      p('pelvis', [-0.036, 0.9, -0.045]),
    ],
    course:
      'Leaves the pelvis through the greater sciatic foramen, hooks around the sacrospinous ligament, and re-enters through the lesser sciatic foramen into the pudendal (Alcock\'s) canal.',
    motorSupply: ['Pelvic floor muscles', 'External urethral and anal sphincters'],
    sensorySupply: 'Perineum and external genitalia',
    muscles: ['pelvic_floor'],
    clinical:
      '"S2, 3, 4 keep the faeces off the floor." A pudendal block for childbirth is delivered at the ischial spine, palpable per vaginam.',
  },
];

function mirrorNerve(n: NerveDef): NerveDef {
  return {
    ...n,
    id: swap(n.id),
    side: 'right',
    path: n.path.map((pt) => ({
      node: swap(pt.node),
      pos: [-pt.pos[0], pt.pos[1], pt.pos[2]] as Vec3,
      via: pt.via,
    })),
    muscles: n.muscles.map(swap),
  };
}

export const NERVES: NerveDef[] = [
  ...CENTER_NERVES,
  ...LEFT_NERVES,
  ...LEFT_NERVES.map(mirrorNerve),
];
